### ISSUE TITLE
Work Modal - Enhancements

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1001]
**As a** user

**I want** to add and make changes to Work

**so that** I have a database that is up to date

### Scenario 1: 

GIVEN 'All Works' tab is open
WHEN I click on 'Create Work' button
THEN 'Create Work' Modal appear with the following information:

- "Create Work" as modal title
- EA Act (Dropdown) (Ghost text "Select EA Act") (required)
- Worktype (Dropdown) (Ghost text "e.g. EAC Assessment") (required)
- Start Date (Date Picker) (Ghost text "MM-DD-YYYY") (required)
- Project (dropdown) (required)
- Responsible Ministry (dropdown) (required)
- Federal Involvement (dropdown) (required)
- Federal Act (dropdown) (required)

- Title (Ghost text "Work Title") (required)
- Project Description (Ghost text "Description will be shown on all reports") (required)
- EPIC Description (Ghost text "Provide a description if differs from the report")
- CAC Required (toggle) (Default inactive) with the following text on hover - 'Select if there is sufficient community interest in this Work to establish a Community Advisory Committee (CAC)'

- EAO Team (dropdown) (required)
- Responsible EPD (dropdown) (required)
- Work Lead (dropdown) (required)
- Decision Maker (dropdown) (required)

- Active (toggle) (default active)
- High Priority (toggle) (default inactive) with the following text on hover - 'Work marked High Priority will have extra milestones appear on Reports'

### Scenario 2:
 
GIVEN 'All Works' tab is open
WHEN I click on 'Edit' button on any Work
THEN 'Project Name - WorkType' Modal appears with the following changes to the current version:

- Modal title is 'Work title' dash 'Worktype'
- Work Title is the combination of 'Work title' - 'Worktype'

- Responsible EPD (dropdown) disabled with the Special History lock button
- Work Lead (dropdown) disabled with the Special History lock button

### Screenshot 

Create Work
![image](https://github.com/bcgov/EPIC.track/assets/126211473/2ced37ff-7656-4b07-98ce-45c0232c735c)

Edit Work
![image](https://github.com/bcgov/EPIC.track/assets/126211473/90bccbec-c91f-4b3b-b55c-3ac80aec242a)

**Comment by maria-kuzmenko** [comment]
Icon

Lock icon - [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdC9WIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--de86fd98d75d9c0be34b96d4cfe1aa9fc6a06947/lock-keyhole-bold.svg)

**Comment by maria-kuzmenko** [comment]
link to prototype

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/Workplan?type=design&node-id=3378-115841&mode=design
