### ISSUE TITLE
Current Accordion Phases - Days left appearance

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1022]
**As a** User

**I want** to see how many days are left in the current phase

**so that** I can plan my time accordingly

### Scenario 1: 

GIVEN Workplan is open with current and future phases
WHEN the countdown for days hasn't started
THEN I see the same values for Days left / total

### Screenshot Scenario 1: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdi8vIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--245fab415056c430902c49b89395c1e8b896f719/Screen%20Shot%202023-10-03%20at%203.47.11%20PM.png)
 
### Scenario 2:

GIVEN Workplan is open with current and future phases
WHEN the countdown for days has started
THEN I see same the countdown for Days left 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0FBQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a0109586da9d8953869da79a6be64eece5729f5/Screen%20Shot%202023-10-03%20at%203.49.50%20PM.png)

### Scenario 3a:

GIVEN Workplan is open with current and future phases
WHEN A Suspension type of Milestone is added to the phase
THEN Days left countdown is frozen for the number of days that are put to the Suspension 
AND pause icon appears next to days left with the colour changing to #858A8C

### Scenario 3b:

GIVEN Suspension type of Milestone is added to the phase
WHEN I open the Phase
THEN I see a warning message above buttons and grid

'The Work is suspended'
'You will need to at a **Resumption Milestone** to resume this Work.'

### Scenario 4a:

GIVEN Workplan is open with current and future phases
WHEN Days left are negative and no Extension milestone is added
THEN Days Left are displayed as 0 and the number of days that are over the Total is put separately 
AND warning icon appears next to days left with the colour changing to #674901

### Scenario 4b:

GIVEN Days left are negative and no Extension milestone is added
WHEN I open the Phase
THEN I see a warning message above the buttons and grid

'This Phase is over the legislated time limit'
'You will need to add an **Extension Milestone** to finish this Phase..'

### Scenario 5:

GIVEN Workplan is open with current and future phases
WHEN An Extension type of Milestone is added to the phase
THEN Both Days Left and the Total is increased by the number of days added

**Comment by maria-kuzmenko** [comment]
Link to the prototype

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/For-Development?type=design&node-id=3967-175&mode=design

**Comment by maria-kuzmenko** [comment]
@dinesh-aot , you might be able to export icons directly from developers mode, but selecting them and choosing 'Export as SVG'.
Please let me know whether this works, as currenty Zenhub has some issues with uploading screenshots

**Comment by maria-kuzmenko** [comment]
@Connor1892 , we're checking this one only for Project Notification

there are some bugs for CEO's and Minister's Designation - I've created a separate card for it.
