### ISSUE TITLE
Task Events - Changes as part of WorkPhase concept

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1027]
**Overview**
We have made a change to the db structure with respect to having a unique identifier for the milestone events and task events. So far , we have been keeping workid and phaseid for that. Now that we may have duplicate phases in the same work, it is not possible to keep those fields as the unique identifiers. 
We will have workPhaseId as the unique identifier moving forward and that change has to be integrated in the TASK EVENTS feature.

**Comment by Connor1892** [comment]
I cannot edit any of the fields for a task from a template. I created a new work, imported tasks from template, and attempted to change the existing fields.

When I add a new task, I am able to do all the expected edits.
