### ISSUE TITLE
Resource Forecast - Jobs Created columns

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1028]
---
We need a column in the Resource forecast for how many jobs the Project has created.
Key here is Project not Work.
Will require a new field in the database for projects

Columns needed:
- Est. FTEs in construction
- Est. FTEs in operation

FTE Construction should be to the right of Capital investment.
then FTE Operation should be to the right of that.
so they go in between Capital investment and EA type

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
FTE Construction should be to the right of Capital investment. then FTE Operation should be to the right of that.
so they go in between Capital investment and EA type @salabh-aot  Please position the new fields as mentioned
