### ISSUE TITLE
Create/ Edit Project Modal - Jobs created Modal

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1029]
---
need to add a new field to the Project modal for Jobs Created.
will require a new field in the database for Projects

Fields needed:
- Est. FTEs in constructions
- Est. FTEs in operations

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
@maria-kuzmenko designs modification needed here

**Comment by maria-kuzmenko** [comment]
@Connor1892, what are jobs?
