### ISSUE TITLE
Workplan Page - Default page view to 'View all'

### ISSUE THREAD

**Issue by maria-kuzmenko** [bcgov/EPIC-FLOW#1047]
**As a** user

**I want** to be able to see the whole list of tasks and milestones

**so that** I can understand what I need to work on

### Scenario 1: 

GIVEN All Works Tab is open
WHEN I click on any Work Name
THEN I am redirected to that work and the current phase of that work is opened showing the grid with all tasks and milestones by default

### Scenario 2: 

GIVEN Workplan page is open
WHEN I click on Rows per page options
THEN I see the following options available:
- 15
- View All

**Comment by jadmsaadaot** [comment]
Instead of adding a view all option, I defaulted the page size to the nearest greater page number, and if all are smaller I added at the end of the page size options the nearest greater and multiple of five page number. In any case you should be able to see all the rows by default
