### ISSUE TITLE
Remove hover option for Filters

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1067]
### Scenario 1: 

GIVEN Workplan page is open
WHEN I hover over in-grid filters such as 'Type', 'Start Date', 'End Date', 'Days', 'Assigned', 'Responsibility', 'Progress'
THEN I don't see the hover option

**Comment by dinesh-aot** [comment]
Only title, assigned and responsibility column should need to have hover options as per the current requirement.
