### ISSUE TITLE
Confirmation dialogs when adding/updating events

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1069]
**Overview**
1. if the updated date will cause any events fall beyond the phase end date - show confirmation dialog

***Scenario 1***

GIVEN Milestone Modal is open
WHEN I select Anticipated Date OR Actual Date that will cause any events fall beyond the phase end date
THEN I see the warning message within the modal: 

'Selecting this date will extend subsequent Milestones beyond the legislated time limit. You might need to add an Extension Milestone to complete the Phase.'

2. if the actual is given - show confirmation dialog

***Scenario 2***
GIVEN Actual date for Milestone is selected
WHEN I press 'Save' button
THEN I see 'Lock this Milestone?' modal with the text

'Entering an actual date will lock this Milestone. Once locked, you will only be able to edit the description and notes field.'

**Comment by maria-kuzmenko** [comment]
@dinesh-aot, link to prototype

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/For-Development?type=design&node-id=4500-5973&mode=design

**Comment by maria-kuzmenko** [comment]
@dinesh-aot, link to prototype

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/For-Development?type=design&node-id=4500-5973&mode=design
