### ISSUE TITLE
Milestone Modals - Adding Suspension/Resumption

### ISSUE THREAD

**Issue by maria-kuzmenko** [bcgov/EPIC-FLOW#1075]
**As a** user

**I want** to add a Suspension milestone to the system

**so that** The work can be paused

### Scenario 1: 

GIVEN Add Milestone modal is open
WHEN I select Suspension type of Milestone
THEN I see the following fields pertain to this type of Milestone:

- High Priority toggle switched on by default

- Anticipated Date
- Actual Date
- Act Section (Dropdown), mandatory
- Reason (Text Field: 60/60 characters left)

### Scenario 2: 

GIVEN Actual Date for the Suspension Modal is added
WHEN I click on 'Add Milestone'
THEN I see Resumption as the only available Milestone type with the following fields

- High Priority toggle switched on by default

- Anticipated Date
- Actual Date

**Comment by maria-kuzmenko** [comment]
@dinesh-aot 

Can't add screenshots, so there is a link to the design
https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/For-Development?type=design&node-id=4497-5529&mode=design

**Comment by Connor1892** [comment]
I'm getting error messages every time I try to lock Extensions or Suspensions.

**Comment by maria-kuzmenko** [comment]
@Connor1892, Dinesh might have changed something based on talks with Geoff, he was showing me it yesterday from his local machine

**Comment by Connor1892** [comment]
I can add both types to the workplan, but I couldn't lock them with actual dates.
@dinesh-aot if I missed something can we go through it together tomorrow?

**Comment by maria-kuzmenko** [comment]
@Connor1892 , use Project Notification new works to test this one - for CEO's and Minister's designation I've created a bug ticket - we found some stuff

**Comment by Connor1892** [comment]
not working for me in Project notification either. @dinesh-aot I'd love us to look at this after scrum tomorrow if possible

**Comment by maria-kuzmenko** [comment]
@Connor1892, have you created a new project notification Work? It should be new to work, make sure all previous phases/Milestones are completed

Ps. We can go through this tomorrow
