### ISSUE TITLE
First nations in work not loading for the first time - need refresh

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1090]

**Comment by dinesh-aot** [comment]
**To Reproduce**
Find a work with empty first nations
Add one nation
Go to some other menu
Load work plan again and navigate to First nations tab

**Comment by maria-kuzmenko** [comment]
@dinesh-aot , @salabh-aot 

tested - not working in test environment
Add nations, go back to work - 0 team members on Nation tab
