### ISSUE TITLE
Nation Tab - Hoverstate Failure

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1093]
Hover state for First Nation Relationship holder fails if it is overtop of the grid.

we need the contact card need to stay while the mouse is on the card.

---
name: User Story
about: 'User Story '
title: ''
labels: ''
assignees: ''

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
@jadmsaadaot this needs an estimate when you decide to take it.

**Comment by dinesh-aot** [comment]
Fixed elsewhere.
