### ISSUE TITLE
Highlight results on all search filters

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1094]
**As a** User

**I want** see all search options highlighted in yellow

**so that** I can immediately find what I was searching for

### Scenario 1: 

GIVEN **Staff tab** within List Management is open
WHEN I start typing in 'Name' search
THEN I see the searched portion highlighted in yellow 

### Scenario 2: 

GIVEN **First Nations tab** within List Management is open
WHEN I start typing in 'Name' search
THEN I see the searched portion highlighted in yellow 

### Scenario 3: 

GIVEN **Proponents tab** within List Management is open
WHEN I start typing in 'Name' search
THEN I see the searched portion highlighted in yellow 

### Scenario 4: 

GIVEN **Projects tab** within List Management is open
WHEN I start typing in 'Project Name' search
THEN I see the searched portion highlighted in yellow 

### Scenario 5: 

GIVEN **All Works tab** is open
WHEN I start typing in 'Name' search
THEN I see the searched portion highlighted in yellow

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , search behaviour for the above-mentioned scenarios can be found on a Workplan page, Task/Milestone search behaviour

**Comment by Connor1892** [comment]
@TomChapmanGov this is the card
