### ISSUE TITLE
Status Tab - Empty State

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1106]
**As a** user

**I want** to see when there is no Status associated with the Work

**so that** I can add them

### Scenario 1: 

GIVEN I am on the Status tab of the Workplan
WHEN there is no Status for the Work
THEN I see the following text:

You don't have any Status yet
Create your first Status

'+ Status' (Primary)

### Scenario 2:
 
GIVEN I am in a Work
WHEN there is no status added yet
THEN I see explanation icon next to the status tab

### Scenario 3:
 
GIVEN I am on the Status tab
WHEN I look at the right side
THEN I see the tabbed section:
- Status Preview
- Notes (rich text)

### Scenario 4:
 
GIVEN I am on the Status tab
WHEN I have the Status Preview tab open
THEN I see the following:
- refresh button (ghost)
- Report Preview panel
    - Status
    - preview box (with text: "Your status will appear here" (ghost text))

### Validation Rules? 

(If yes, list here)

### Screenshot 

![image](https://github.com/bcgov/EPIC.track/assets/126211473/c9b803a0-9f77-45c3-b01f-39489d370760)

**Comment by maria-kuzmenko** [comment]
link to prototype

https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus)?type=design&node-id=3738-34955&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1106?planning-poker) with Zenhub @jadmsaadaot @saravanpa-aot @TomChapmanGov

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , @TomChapmanGov 

1. we should remove all padding from .jss 5

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTZiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7110c7d1dbefc82ec8d6f1d3865ebf80f65909b/padding.png)

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , @TomChapmanGov 

2. border-radius should be set up to 4px

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek9iQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--118e33baf4d76dab19ee98c3b4064d5e69d90e5c/border-radius.png)

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , @TomChapmanGov 

Uploading the correct icon for the identificator

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeldiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3cf76cfa3035f6baf90079eafb4bd70bcf62bb1/indicator.svg)

**Comment by Connor1892** [comment]
for Scenario 3, the notes don't save.
for Scenario 4, there's no refresh button. has that requirement been removed?

**Comment by maria-kuzmenko** [comment]
nice catch about Scenario 4, @Connor1892 !
