### ISSUE TITLE
Status Tab - First Status

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1107]
**As a** team member

**I want** to add a status to my Work

**so that** I can populate Reports

### Scenario 1: 

GIVEN I am on the Status Tab
WHEN I click the Add Status Button
THEN I see the Add Status Modal with the following:
- Title (Add Status)
- Date (label with todays date)
- Description (Text box) (500 character limit) (Required)
- Save (Primary)
- Cancel (Ghost)

![image](https://github.com/bcgov/EPIC.track/assets/126211473/cb640d0e-71e6-420a-8bd4-87dc19054740)

### Scenario 2:

GIVEN Add status modal is open
WHEN I click on save button
THEN I see the status box with the following:
- Date (prepopulated with TODAY's date. For selection, only the following date range is available - from -14 thru +21)
- Tags ("Need Approval")
- Status text
- Approval button
- Edit button

### Scenario 3:

GIVEN A status is not approved
WHEN I press the edit button
THEN I see the Edit Status Modal with the Description active

![image](https://github.com/bcgov/EPIC.track/assets/126211473/3568fc09-424c-4461-af50-dff1c5b55280)

### Scenario 4:

GIVEN Status tab is open
WHEN there is no approved status from the last X days (X is the Admin Freshness number)
THEN a warning appears with the following:

The Work status is out of date
Please provide an updated status.

![image](https://github.com/bcgov/EPIC.track/assets/126211473/761e5439-13ca-479d-aebb-c4cbf0f3d888)

### Scenario 5:
 
GIVEN I am on the Status tab
WHEN I have the Status Preview tab open
THEN I see the following:
- refresh button (ghost)
- Report Preview panel
    - Status
    - preview box (with text: "Once approved, Status will appear here" (ghost text))

![image](https://github.com/bcgov/EPIC.track/assets/126211473/91d557e9-d907-451a-bbe6-0166f50f1a44)

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
link to prototype

https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus)?type=design&node-id=4702-5076&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1107?planning-poker) with Zenhub @TomChapmanGov @jadmsaadaot @saravanpa-aot
