### ISSUE TITLE
Status Tab - Second Status

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1110]
**As a** team member

**I want** to add a new status to my Work

**so that** I can update Reports

### Scenario 1: 

GIVEN I am on the Status Tab
WHEN I click the Clone Button
THEN I see the Add Status Modal with the following:
- Date (Label with todays date prepopulated)
- Description active

### Scenario 2:

GIVEN Add status modal is open
WHEN I click on save button
THEN I see the status box with the following:
- Date
- Tags ("Need Approval")
- Status text
- Approval button
- Edit button (superuser only)

THEN I see the Status History with the the following:
- date
- green dot icon to show this is the currently approved status
- the previously approved status
- edit button (superuser only)

![image](https://github.com/bcgov/EPIC.track/assets/126211473/3d2bc32f-ac1a-4434-9272-a4e2cace73d5)

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
link to prototype

https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus)?type=design&node-id=4743-7066&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1110?planning-poker) with Zenhub @TomChapmanGov @jadmsaadaot @saravanpa-aot
