### ISSUE TITLE
Status Tab - Status History

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1112]
**As a** team member

**I want** to see old status on my Work

**so that** I can see into the past

### Scenario 1: 

GIVEN I am on the Status Tab
WHEN there are at least 2 old Statuses AND there is an Approval Needed Status
THEN I see the following under Status History:
- the most recent approved status is on top (un-truncated)
- the older statuses are below the edit button
- there is a line connecting the dot icons for the statuses
- the previous statuses are in ghost text
- the previous statuses are truncated
- there is a Read More button for each status that has been truncated

![image](https://github.com/bcgov/EPIC.track/assets/126211473/6371a987-8ef2-48ae-93a5-e085cc816183)

### Scenario 2:

GIVEN I am on the Status Tab
WHEN there are at least 2 old Statuses AND there is an Approved Status
THEN I see the following under Status History:
- the most recent approved status is on top
- there is a line connecting the dot icons for the statuses
- the line and dot icons are grey
- the previous statuses are in ghost text
- the previous statuses are truncated
- there is a Read More button for each status that has been truncated

![image](https://github.com/bcgov/EPIC.track/assets/126211473/d6e3a815-b785-4539-bcbf-6155a84b5eb3)

### Scenario 3:

GIVEN there are old statuses i want to read
WHEN I click on the show more button
THEN I see the old Status expand to full length

![image](https://github.com/bcgov/EPIC.track/assets/126211473/dc7ea9ad-82d9-4a38-bb4c-ee2b73fad8b5)

### Scenario 4:

GIVEN an old status is expanded
WHEN I click on the show less button
THEN I see the Status history return to default view

![image](https://github.com/bcgov/EPIC.track/assets/126211473/f47786f1-8cd7-4b39-b893-937c2fb56313)

![image](https://github.com/bcgov/EPIC.track/assets/126211473/0102c5f1-1ffb-48cc-97c0-d8ce3ab7468f)

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
link to prototype 

https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus)?type=design&node-id=4743-8538&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1112?planning-poker) with Zenhub @TomChapmanGov @jadmsaadaot @saravanpa-aot

**Comment by Connor1892** [comment]
for Scenario 1 we want the first status in the history to be un truncated if it is the approved status
