### ISSUE TITLE
Status Tab - Approved Status

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1113]
**As a** user

**I want** to approve a status

**so that** it will appear on reports

### Scenario 1: 

GIVEN I am on the status tab
WHEN I click 'Approve' button
THEN I see a confirmation Modal with the following:
- Title (Approve this Status)
- Once approved, this status will be automatically added to the Report
- Confirm (Primary)
- Cancel (Ghost)

![image](https://github.com/bcgov/EPIC.track/assets/126211473/80044c1c-67a0-4474-8ba5-f2eb5ab0dab3)

### Scenario 2:

GIVEN approve this status Modal is open
WHEN I click confirm
THEN I see the status box update to the following:
- Date
- Tags ("Approved")
- Status text
- Clone button

THEN I won't see Exclamation icon next to the 'Status' tab

![image](https://github.com/bcgov/EPIC.track/assets/126211473/01f9cffb-81be-414d-97c9-80df0e6b841d)

### Scenario 3:
 
GIVEN I am on the Status tab
WHEN I have the Status Preview tab open
THEN I see the following:
- refresh button (ghost)
- Report Preview panel
    - Status
    - Date (when status was approved)
    - preview box (with most recently approved status)

![image](https://github.com/bcgov/EPIC.track/assets/126211473/0f0bfcd3-3ebd-4b37-b552-309f62892fc7)

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
link to the prototype

https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus)?type=design&node-id=4714-5487&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1113?planning-poker) with Zenhub @TomChapmanGov @jadmsaadaot @saravanpa-aot
