### ISSUE TITLE
Status Tab - Edit Status Superuser

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1114]
**As a** superuser

**I want** to edit/update an approved status

**so that** mistakes can be fixed

### Scenario 1: 
 
GIVEN there is an approved status and I am a superuser
WHEN I select the Edit button
THEN I see Edit Status Modal and the Description is active

### Scenario 2:

GIVEN Edit status Modal is open
WHEN I click Save
THEN I see the status box update to the following:
- Date
- Tags ("Approved")
- Status text
- Clone button
- Edit button

AND Status Preview would be updated based on changes

![image](https://github.com/bcgov/EPIC.track/assets/126211473/ebe6526b-4199-4674-a39e-002fed9678da)

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
link to prototype

https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus)?type=design&node-id=4719-6702&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1114?planning-poker) with Zenhub @TomChapmanGov @jadmsaadaot @saravanpa-aot

**Comment by Connor1892** [comment]
I am set to Developer level permissions but I cannot see the edit button. is it just checking for "Superuser" group?
