### ISSUE TITLE
Issues Tab - Edit Issues Superuser

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1119]
**As a** superuser

**I want** to edit/update an approved Issue

**so that** mistakes can be fixed

### Scenario 1: 
 
GIVEN there is an approved Issue and I am a superuser
WHEN I select the Edit button
THEN I see Edit Issue Modal and the Description is active

### Scenario 2:

GIVEN Edit Issue Modal is open
WHEN I click Save
THEN I see the Issue box update to the following:
- Date
- Tags ("Approved")
- Issue text
- Clone button
- Edit button

AND Issue Preview would be updated based on changes

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
link to prototype

https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus)?type=design&node-id=4771-12964&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1119?planning-poker) with Zenhub @TomChapmanGov @jadmsaadaot @saravanpa-aot
