### ISSUE TITLE
Issues Tab - Second update to Issue

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1120]
**As a** team member

**I want** to add a new Issue to my Work

**so that** I can update Reports

### Scenario 1: 

GIVEN I am on the Issue  Tab
WHEN I click the Clone Button
THEN I see the Add Issue Modal

### Scenario 2:

GIVEN Add Issue modal is open
WHEN I click on save button
THEN I see the Issue box with the following:
- Date
- Tags ("Need Approval")
- Issue text
- Approval button
- Edit button (superuser only)

THEN I see the Issue History with the the following:
- date
- green dot icon to show this is the currently approved Issue 
- the previously approved Issue 
- edit button (superuser only)

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
link to prototype

https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus)?type=design&node-id=4771-13633&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1120?planning-poker) with Zenhub @TomChapmanGov @jadmsaadaot @saravanpa-aot

**Comment by jadmnsaad** [comment]
I will add the edit button for the issue history here https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/1121
