### ISSUE TITLE
Issues Tab - Issue History

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1121]
**As a** team member

**I want** to see old Issues on my Work

**so that** I can see into the past

### Scenario 1: 

GIVEN I am on the Issue Tab
WHEN there are at least 2 old Issues AND there is an Approval Needed Issue 
THEN I see the following under Issue History:
- the most recent approved Issue is on top (un-truncated)
- the older Issues are below the edit button
- there is a line connecting the dot icons for the Issues
- the previous Issues are in ghost text
- the previous Issues are truncated
- there is a Read More button for each Issue that has been truncated

### Scenario 2:

GIVEN I am on the Issue Tab
WHEN there are at least 2 old Issues AND there is an Approved Issue
THEN I see the following under Issues History:
- the most recent approved Issue is on top
- there is a line connecting the dot icons for the Issues
- the line and dot icons are grey
- the previous Issues are in ghost text
- the previous Issues are truncated
- there is a Read More button for each Issue that has been truncated

### Scenario 3:

GIVEN there are old Issues I want to read
WHEN I click on the show more button
THEN I see the old Issue expand to full length

### Scenario 4:

GIVEN an old Issue is expanded
WHEN I click on the show less button
THEN I see the Issue history return to default view

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
link to prototype

https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus)?type=design&node-id=4771-14414&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1121?planning-poker) with Zenhub @TomChapmanGov @jadmsaadaot @saravanpa-aot
