### ISSUE TITLE
Issues Tab - Multiple Issues

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1122]
**As a** User

**I want** See all high level information about multiple issues

**so that** I know which one I need to update

### Scenario 1: 

GIVEN Issue Tab is open
WHEN I click on '+ Issue' button
THEN I see 'Add Issue' Modal with empty values
- Title (Mandatory)
- Description (Mandatory)
- Active Toggle (on by default)
- Hight Priority Toggle (off by default)
- Start Day (Mandatory, date picker)
- Expected Resolution Date (date picker)

### Scenario 2: 

GIVEN Add Issue modal is open
WHEN I click 'Save' AND there more then 1 issue 
THEN I see a list of all issue with collapsed grid sorted from the latest updated date to the oldest

### Scenario 3:
GIVEN Issue Tab is open with multiple issues
WHEN I look at the 30-60-90 Report Preview tab
THEN I see only issues that are 'Active' AND 'High Priority'

### Scenario 4:
GIVEN Issue Tab is open with multiple issues
WHEN I click on Referral Schedule report preview
THEN I see all issues that are 'Active'

**Comment by maria-kuzmenko** [comment]
link to prototype

https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus)?type=design&node-id=4776-15118&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1122?planning-poker) with Zenhub @TomChapmanGov @jadmsaadaot @saravanpa-aot

**Comment by Connor1892** [comment]
if one of these is stale but the others are not, how is that shown here?
