### ISSUE TITLE
Create Work Modal - Title & Description Adjustments

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1133]
---

- title
- work description
- label for project description

### Scenario 1: 

GIVEN All Works tab is open
WHEN I click on any existing Work name
THEN Work modal opens with the following changes to the fields

- **Title** is created by the system in the forma [Project Title] — [Work Type] and can be edited
- Report Description is changed to **Work Description**
- EPIC Description is changed to **Project Description** (pulled from Project Description on Project Modal, disabled)

### Screenshot 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL09GQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--995f462c7de562837440edecc7a53cdef674185f/Screen%20Shot%202023-10-30%20at%204.01.22%20PM.png)

**Comment by maria-kuzmenko** [comment]
@EAO-App-Admin , tagging Geoff here to remind about the ghost text for the 'Work Description'
