### ISSUE TITLE
Complex Actions

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1134]
---
- AddPhase
- SetEventDate
- AddEvent

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
@Connor1892, this one Dinesh is saying can be completed - we are now working on bugs associated with this but as separate tickets. 

this one is about actions when the new events should be created.
