### ISSUE TITLE
Task Template - refresh + double import

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1143]
---
able to accidentally add the same template twice!

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by salabh-aot** [comment]
@dinesh-aot @Connor1892 I was not able to reproduce the issue in Dev environment.
