### ISSUE TITLE
Workplan Tab - Event order

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1152]
---

when 2 or more events fall on the same day, there needs to be a clear order to those same day events.

order is:
- Mandatory/System Generated Milestones by id order,
- optional milestones by id order,
- then Tasks by id order

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
**Overview**
The logic is as follows
- START event and END event should always be in the top and bottom position respectively irrespective of the date value
- Then ascending order of the START DATE
- if events with same dates then
  - MANDATORY milestones get next priority 
  - Multiple MANDATORY milestones on the same date then check its autogenerated system ids to order them to ascending
  - OPTIONAL milestones get next priority
  - Multiple OPTIONAL milestones on the same date then, check its autogenerated system ids to order them to ascending
  - TASKS gets next priority
  - Multiple TASKS events on the same date then, check its autogenerated system ids to order them to
