### ISSUE TITLE
Staff Modal - enhancements

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1159]
---

- Need restrictions/formatting on phone number
- active should be toggle not checkbox

---

**As a** Superuser

**I want** to add Staff member

**so that** we can add them later to Teams

### Scenario 1: 

GIVEN Staff Tab is open
WHEN I click 'Create Staff' button
THEN 'Create Staff' modal appears with the following fields:
- First Name 
- Last Name
- Email
- Phone (ghost text - (xxx) xxx-xxxx), numbers only constraint 
- Position (select dropdown)
- Active Toggle (on by default)

### Scenario 2:
GIVEN 'Create Staff' modal is open
WHEN I put phone number in any formats - (236) 898-43-34, 56787659898, etc
THEN the number should be auto-formated to (236) 898-4334

### Screenshot 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUN5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0f57a05a4a328fb67bb6bd4553db59ecb796ff6/Screen%20Shot%202023-11-07%20at%206.32.57%20PM.png)

**Comment by maria-kuzmenko** [comment]
link to prototype - https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/For-Development?type=design&node-id=4808-3333&mode=design
