### ISSUE TITLE
Actual Date restrictions

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1163]
---

cannot have actual dates in the future. today or before ONLY

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
@dinesh-aot is this being handled in any other Cards you're working on?
@EAO-App-Admin discouvered the bug actually pushes previously locked milestones

**Comment by dinesh-aot** [comment]
**Restrictions**
- Restrict the work start minimum value to June 30, 1995
- Actual date of any event should be set minimum to phase start date and maximum to today

**Comment by EAO-App-Admin** [comment]
Correct!
and phaseStartEvent ACTUAL is minimum June 30, 1995 and maximum TODAY
