### ISSUE TITLE
Change the way current phase is identified in the work plan

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1171]
**Problem**
Currently we are keeping current_phase_id in work entity to identify the current phase. Currently a work plan can have duplicated phases, so this method no longer work. We should either store the work_phase_id in work, or just derive the current phase from the work_phase table itself.

**Possible Solutions**
- Keep the current_work_phase_id in work table and update this field whenever a phase is completed
- Derive this information from the work_phase table itself as the table already has a field called is_completed. 
  SELECT * FROM work_phases WHERE is_completed=false order by id desc limit 1
- Create a flag in work_phase called is_current and set it whenever a work phase is completed

**Comment by maria-kuzmenko** [comment]
ways to reproduce: adding actual dates to events or complete phase one by one - next phase should automatically open
