### ISSUE TITLE
Replicate Event Calendar from Redash instance

### ISSUE THREAD

**Issue by salabh-aot** [bcgov/EPIC-FLOW#1172]
Create a working copy of the event calendar from redash, so that it can be analyzed and updated with the new design theme of EPIC.track

**Comment by Connor1892** [comment]
@EAO-App-Admin pls QA this one

**Comment by Connor1892** [comment]
we have all calendar items showing up here.
for the Event Calendar we want to show Milestones, not Calendar Events.

**Comment by Connor1892** [comment]
in future we will have multiple versions of Calendar using different types of events
