### ISSUE TITLE
Button Enhancements

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1175]
---

issues tab report preview buttons
- sizes change when flipping between 30-60-90 and referral schedule previews

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
@djnunez-aot 

not working for Issue Tab, should work the same way as on the Status Tab
