### ISSUE TITLE
Workplan Page - days left warning

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1190]
---

the days left area of the accordion, when it has a warning, is not very noticeable in its dark yellow.
we need to make it pop more to show that a warning is on display

---

**As a** user
**I want** see instantly what phases are out of time
**so that** I can add extension milestone to extend the phase timeline

### Scenario 1: 

GIVEN My Workplans is open
WHEN I click on any Work which timeline is beyond legislative timeline
THEN I see days left in Error/Dark rgba (163.30,34,1) and a exclamation symbol indicator 

### Screenshot 
<img width="1429" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXA5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa784a44cf6fda298cf7472e9575d88ca9959749/Screen%20Shot%202024-02-21%20at%202.50.51%20PM.png" alt="Screen Shot 2024-02-21 at 2.50.51 PM.png" />

**Comment by Connor1892** [comment]
@maria-kuzmenko colour code for new warning colour pls!

**Comment by maria-kuzmenko** [comment]
@djnunez-aot , link to the design - https://www.figma.com/file/XcYynwH7xrO2P30uqewaLS/For-Development?type=design&node-id=41-142&mode=dev

What should be done:
1. Exclamation indicator next to the status should be recoloured into
    background: rgba(252, 237, 238, 1)
     exclamation mark: rgba(163, 30, 34, 1)

2. This component we are reusing and change a triangle to it
