### ISSUE TITLE
Issues Tab - Start Date

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1191]
---

we want to add start date to the accordion so we know how long an issue has been active

---

**As a** User

**I want** know when the Issues was first created

**so that** understand for how long it has been active

### Scenario 1: 

GIVEN Issue Tab is open 
WHEN I look at the accordion
THEN I see 'Start Date' next to the issue Title

### Screenshot 1:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNSs0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d199c9483824726cb4a19ee27edda2932015767/Screen%20Shot%202023-11-08%20at%2012.03.14%20PM.png)

### Scenario 2: 

GIVEN Issue Tab is open and Issue is added
WHEN I click 'Edit' button
THEN I see 'Start Date' disabled

### Screenshot 2:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkc0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35bfa091ee750e0cd5515d73e644006db2e79665/Screen%20Shot%202023-11-08%20at%2012.04.21%20PM.png)

**Comment by maria-kuzmenko** [comment]
link to prototype - https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus)?type=design&node-id=4771-10105&mode=design
