### ISSUE TITLE
Resource Forecast - inactive works

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1193]
---

inactive works are showing up on the resource forecast

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
**Logic**
is ACTIVE;
WORK Started (ANTICIPATED/ACTUAL in 1st Phase PHASE START EVENT) BEFORE the Report Date + 6 MONTHS!!!!!
WORK did not END (ACTUAL in last "ACTIVE" Phase PHASE END EVENT) BEFORE the Report Date

**Comment by dinesh-aot** [comment]
The downloaded file is corrupted @salabh-aot
