### ISSUE TITLE
Failing actions on CEO's and Minister's Designation

### ISSUE THREAD

**Issue by maria-kuzmenko** [bcgov/EPIC-FLOW#1197]
**Overview**

**For Aurora LNG Digby Island - Minister's Designation** when adding an Actual date for the next Milestone -  "Minister's Designation Application Initial Review" - produces the error even when the Actual date is same as Anticipated and all previous milestones have actual dates 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDI1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0304d30bc0bda55fa63f0470c8993085d33dd5ce/Screen%20Shot%202023-11-08%20at%201.42.54%20PM.png)

Same issues for "Aurora LNG Digby Island - CEAO's Designation"

**Comment by Connor1892** [comment]
create ceao designation and add actual dates

**Comment by Connor1892** [comment]
I created a CEAO designation, but when trying to lock the second milestone, I can ONLY pick todays date. nothing before or after. I also can't change the month or year.

UPDATE: I'm dumb. figured it out
