### ISSUE TITLE
Create Project - Uniqueness

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1201]
---

Project: Abbreviation needs to enforce uniqueness.

we want to implement a auto-generated code for future projects, but we need to be able to edit for input of existing ones.

@EAO-App-Admin has a schema based on bird watching codes

---

**As a** Superuser

**I want** To create a NEW project in EPIC.track and have the system generate a unique ABBREVIATION for the PROJECT 

**so that** this ABBREVIATION can be used in EDRMS as the project code file to ensure all projects are filed properly and all system created files can be coded with this unique code

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
@dinesh-aot @saravanpa-aot how easy would this be?

**Comment by EAO-App-Admin** [comment]
ABBREVIATION Creation Methods:
1.	3 + 3
2.	1 + 1 + 4
3.	First 6
4.	Special

Method 1:	1st 3 LETTERS OF FIRST WORD IN NAME + FIRST 3 LETTERS OF 2nd WORD IN NAME
Method 2:	1st LETTER OF FIRST WORD IN NAME + 1st LETTER OF 2nd WORD IN NAME + 1st FOUR LETTERS OF THIRD WORD IN NAME
Method 3:	1st 6 LETTERS OF FIRST WORD IN NAME
Method 4:	CREATE CUSTOM CODE FOR PROJECT

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW9hQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--113e997bf2c115e8de86484d306c240e67732ae5/image.png)

**Comment by Connor1892** [comment]
once the Abbreviation is made, only superusers can change it!

**Comment by ethanjorgensen** [comment]
If I put in an incorrect name and check the abbreviation, then correct the name, and then check the abbreviation again, the abbreviation does not update.

Until I save a new project, I need it to update within the modal.

**Comment by jadmnsaad** [comment]
Fixed!
