### ISSUE TITLE
Project Notification - Revised PN phases are not created when More information is needed 

### ISSUE THREAD

**Issue by maria-kuzmenko** [bcgov/EPIC-FLOW#1220]
For Project Notification Work last phase for Decision milestone if a user chooses 'More Information Needed', three phases should be created.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1BHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--42bd8b48c8959a4c0e860462d4c608a4f7287aa7/image.png)
 
Currently:
- Only Revised Project Notification Decision phase is created
- Milestones are locked 
- Milestones are unlock when a task is added
- Milestones are locked again and task is deleted when Actual is put in
- Accordion behaviour is tailored to the Project Notification Decision phase 

Desired effect:
- three phases are created with the same Milestones with Anticipated dates only
- accordions for those phases can be opened and closed while pressing on them
- actual dates can be put in and milestone progress would be tracked
- when tasks are added, they stay in the system

**Comment by maria-kuzmenko** [comment]
video with steps reproduced 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0hHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea381bb3583d29eb243368f88329fc3d0f45ad85/20231110150126311.mp4)

**Comment by carlygreenehill** [comment]
- three phases are created with the same Milestones with Anticipated dates only -- YES
- accordions for those phases can be opened and closed while pressing on them -- YES
- actual dates can be put in and milestone progress would be tracked -- YES
- when tasks are added, they stay in the system -- YES
