### ISSUE TITLE
Status Tab - UI Clean Up

### ISSUE THREAD

**Issue by TomChapmanGov** [bcgov/EPIC-FLOW#1230]
- Status history not showing correctly when 1 status has been approved
- Read More / Read Less behaviour is weird
- Dont expand status preview box to be same height as status history box
- Show More doesnt need to be there if there arent more statuses to show

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
should superusers be able to edit old statuses when there's a later approved one? @maria-kuzmenko
