### ISSUE TITLE
Grid Filters - Projects

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1241]
---

we need the same filter functionality across all application as ones implemented in the Workplan Grid

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

**List Management > Projects**
- Name (Search as in the Workplanpage with yellow highlight)
- Type (Multiselect)
- Subtype (Multiselect)
- ENV Region (Multiselect)
- Active (Title 'Active' should be changed to 'Status' (Multiselect - Select All, Active, Inactive)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by jadmnsaad** [comment]
There might be a scalability issue regarding filters and tables . I noticed some lag when filters are applied in the projects list, it's a long list. We might need to discuss this @Connor1892
