### ISSUE TITLE
List Management - All Pages

### ISSUE THREAD

**Issue by TomChapmanGov** [bcgov/EPIC-FLOW#1265]
List management 'Create' buttons should be disabled for non superusers (or above Tom)
Modals should be view only for non superusers

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
@jadmsaadaot I need an estimate on this

**Comment by ethanjorgensen** [comment]
@jadmsaadaot edit and create still need to be disabled for non-superusers. I am a viewer and can edit/create in List Management.

**Comment by carlygreenehill** [comment]
HERE YOU GO @jadmsaadaot

**Comment by jadmnsaad** [comment]
@Connor1892 @ethanjorgensen  The above comments have been addressed btw, are the issues mentioned still happening?
