### ISSUE TITLE
My Workplans - Empty State

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1277]
**As a** viewer (who is not assigned to any works)

**I want** to see all works (with "Name's Workplans" toggled off) when I come the the My workplans page

**so that** I can still see what is happening in the office

### Scenario 1: 

GIVEN I am not assigned to any work
WHEN I navigate to the My Workplans page
THEN I see the toggle is off AND I see all works

### Screenshot 1
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelh4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--241d0cb3d05a4f3e29631a4b7d28fa0d7c1336a7/Screen%20Shot%202023-11-20%20at%201.59.54%20PM.png)

### Scenario 2:

GIVEN I am assigned to no works
WHEN I toggle the Workplans toggle on
THEN I see the usual Nothing Found message

### Screenshot 2
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemZ4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c65db5e7a45a88b4917f87819cd9ceb61f35c7b/Screen%20Shot%202023-11-20%20at%202.00.20%20PM.png)

**Comment by maria-kuzmenko** [comment]
link to prototype - https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus%2FDashboard)?type=design&node-id=5441-455&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1277?planning-poker) with Zenhub @saravanpa-aot @jadmsaadaot @TomChapmanGov

**Comment by jadmnsaad** [comment]
@maria-kuzmenko @Connor1892 The toggle functionality will be done as part of the search filters task. It's a filter and it requires some of that ground work.
