### ISSUE TITLE
My Workplans - Work Listing Page

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1278]
---
for reference image

---

### Scenario 1: 

GIVEN I was assigned on a team
WHEN I open My Workplans
THEN The toggle [Name's] Workplans is automatically on and I can see 
- Search 
- Search results
- Filters 
- Mock cards

### Screenshot 1:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFh4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e30858bdf23da323167fc4ffabeca4189e6fb575/Screen%20Shot%202023-11-20%20at%202.09.53%20PM.png)
 

### Scenario 2:
GIVEN My Workplans is open and there are more than 6 types of work there
WHEN I start scrolling
THEN More cards appear on lazy loading

**Comment by maria-kuzmenko** [comment]
link to prototype - https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus%2FDashboard)?type=design&node-id=5441-2755&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1278?planning-poker) with Zenhub @saravanpa-aot @jadmsaadaot @TomChapmanGov

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , @TomChapmanGov 
When I'm logging into the application and I'm assigned on Teams, the toggle is still off - should be on automatically

**Comment by jadmnsaad** [comment]
@maria-kuzmenko fixed, can you please review again?

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot, works for me!
@Connor1892 ?
