### ISSUE TITLE
My Workplans - Staff Appearance

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1281]
**As a** user

**I want** to see which staff is on which work

**so that** I know who to contact about a given work

### Scenario 1: 

GIVEN I am on the My workplans page
WHEN I have "Name's Workplans" togged on
THEN I can see the following:
- Team
- Team Lead
- My Staff Icon (primary) (my bubble is first)
- Staff (ghost) (other active assigned staff ordered by date added)
- Update (changed from view because I am on the team)

### Screenshot 1:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzN4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--76180449283c98bfafc4b6caf34baf26818e3e18/Screen%20Shot%202023-11-20%20at%202.57.40%20PM.png)

### Scenario 2:

GIVEN I am on the My workplans page
WHEN I hover over the staff icons
THEN I can see their staff contact card 

### Screenshot 2:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzd4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8bd4031d6a6f12223e424c1c975710f643ea2287/Screen%20Shot%202023-11-20%20at%202.58.04%20PM.png)

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
link to the cards behaviour - https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=1462-2073&mode=design

link to the prototype - https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus%2FDashboard)?type=design&node-id=5443-3964&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1281?planning-poker) with Zenhub @saravanpa-aot @jadmsaadaot @TomChapmanGov

**Comment by Connor1892** [comment]
@jadmsaadaot 
I assigned myself to a work, but I don't show up first, my bubble isn't blue, and I can't toggle the my workplans toggle.

**Comment by jadmnsaad** [comment]
@Connor1892 let's test this together because I can't reproduce the issue

**Comment by jadmsaadaot** [comment]
@Connor1892 let's test this together because I can't reproduce the issue
