### ISSUE TITLE
My Workplans - Search Behaviour

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1282]
**As a** user

**I want** to be able to search the My Workplans page

**so that** I can find the Works I'm looking for

### Scenario 1: 

GIVEN I am on the My Workplans Page
WHEN I type Project name into the search bar (Project restricted)
THEN I will see the suggested results in the dropdown

### Screenshot 1:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDBIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa3c81a63e6c4a7141f881f05df3f08a59101189/Screen%20Shot%202023-11-24%20at%209.26.53%20AM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDhIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--edc0b80444677d18c24e7cd916e31f7cb04f6a50/Screen%20Shot%202023-11-24%20at%209.27.27%20AM.png)

### Scenario 2:

GIVEN I have a list of suggested results
WHEN I select one of the projects from the dropdown
THEN I will see the reduced set of works linked to that project

### Screenshot 2:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUFIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7453e70ad176963b14177ee36473520307adff8/Screen%20Shot%202023-11-24%20at%209.28.10%20AM.png)

### Scenario 3:

GIVEN I have searched for a project
WHEN I select the x button in the search
THEN the search will reset to rest state

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1282?planning-poker) with Zenhub @jadmsaadaot @saravanpa-aot @TomChapmanGov

**Comment by Connor1892** [comment]
can we search by person?
we already do that for the person who is using the system, can it be bundled into the search as well?

**Comment by carlygreenehill** [comment]
@jadmsaadaot flagging some squashing in the search field for long projects names (scenario 2) - using edge on 16" lenovo laptop
![image](https://github.com/bcgov/EPIC.track/assets/101662408/6eddf7e0-d833-45b5-bc75-1bef516dccca)

@maria-kuzmenko  let me know if you want me to make a new/bug ticket, but i think the work for this card is still complete!
