### ISSUE TITLE
My Workplans - Filter Behaviour

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1283]
**As a** user

**I want** to be able to filter the My Workplans page

**so that** I can find the Works I'm looking for

### Scenario 1: 

GIVEN I am on the My Workplans Page
WHEN I look at filters
THEN I will see the following:
- Project Type
- Work Type
- ENV Region
- Team
- Work State

### Scenario 2:

GIVEN I am on the My Workplans Page
WHEN I filter by 4 options
THEN I will see the filter title 

### Scenario 3:

GIVEN I am on the My Workplans Page
WHEN I toggle the "Name's Workplans"
THEN I will see only the Works that I am assigned to as a team member

### Scenario 4:

GIVEN I am on the My Workplans Page
WHEN I toggle the "Name's Workplans" AND I am an EPD
THEN I will see all the Works that have my Team as the Work Team

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1283?planning-poker) with Zenhub @jadmsaadaot @saravanpa-aot @TomChapmanGov

**Comment by jadmnsaad** [comment]
I have merged my code changes for the filters, they all work except the my workplan toggle. I have started working on it and will follow up with its PR soon

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , we need somehow to make the Project Type filtered view in one line as other filters are. 

<img width="1713" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3RjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2282a5102a4633938e4623bfb40f29b436324546/Screen%20Shot%202023-12-13%20at%204.24.59%20PM.png" alt="Screen Shot 2023-12-13 at 4.24.59 PM.png" />

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot, when clicking on 'Clear' button, filter options should be cleared in results automatically without pressing 'Apply' button

**Comment by jadmnsaad** [comment]
@maria-kuzmenko clear issue fixed.

The word wrap in the filter is a fix for the app's filter component, let's do that separately if you agree it wouldn't block this task

**Comment by Connor1892** [comment]
@jadmsaadaot @maria-kuzmenko I can't test Scenario 4. the others all work great for me.

@maria-kuzmenko we need to add the ability to update EPD to Team relationship in an admin menu
