### ISSUE TITLE
My Workplans - Basic Card Implementation

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1286]
**As a** Team Member

**I want** to be able to see all Works in a card view

**so that** I can see all the important information about a work

### Scenario 1: 

GIVEN I am on the My Workplans Page
WHEN I look at a Work card
THEN I see:

- Project Name
- Badge Identifier for Project State
- Work Title & Work State
- Work Phase with days left
- Upcoming milestone with date
- Last status update (empty / filled in)
- IAAC Involvement
- Team
- Lead
- Staff on Work
- Action Button

### Screenshot #1

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWp4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7ad4a38cb99be3f61cabbb2c7fec9662a3c8c62/Screen%20Shot%202023-11-20%20at%202.26.17%20PM.png)

**Comment by maria-kuzmenko** [comment]
Link to Design System - https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=1462-2073&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1286?planning-poker) with Zenhub @saravanpa-aot @jadmsaadaot @TomChapmanGov

**Comment by carlygreenehill** [comment]
If @maria-kuzmenko says this is perfect, then I believe it! The page looks beautiful
