### ISSUE TITLE
Admin Menu - Superuser and up

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1288]
---

only superusers and higher should be able to see the Admin menu item

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by ethanjorgensen** [comment]
@TomChapmanGov I am a viewer, and I can still access the Admin User menu.

**Comment by Connor1892** [comment]
I'm showing up as nothing on Test, but can still see admin menu

**Comment by Connor1892** [comment]
in Dev, I can still see the menu item, but the screen doesn't load data.
once I refreshed it disappeared
