### ISSUE TITLE
Implemment roles in the frontend

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/EPIC-FLOW#1292]
To support https://github.com/bcgov/EPIC.track/issues/662 ,  front end controls have to be access controlled using roles.

The https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/394 can be used as a reference for the implementation

**Comment by maria-kuzmenko** [comment]
we should wait for revised role matrix
