### ISSUE TITLE
Issues Tab - enhancements

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1295]
---

- the history should fencepost on a dot not a line
- if the approved issue is in the history, it should not be truncated
- if you approve an issue that is not the first accordion on the list, then on refresh it gets closed. the most recently interacted with should remain open if possible

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by jadmnsaad** [comment]
@maria-kuzmenko we discussed the history should fencepost on a dot not a line, will leave it for now

**Comment by Connor1892** [comment]
it's ending on a line again in issues.
statuses are correct.
