### ISSUE TITLE
List Management - Staff Page

### ISSUE THREAD

**Issue by TomChapmanGov** [bcgov/EPIC-FLOW#1301]
Reduce width of phone number column
Phone number input:
- Inline errors
- Editing errors

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by jadmnsaad** [comment]
@Connor1892 can you please help by adding some extra clarification and description, I'm not completely certain what to do here
