### ISSUE TITLE
My Workplan & Insights - Under construction

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1308]
**As a** tester

**I want** an under construction page

**so that** users will not assume the system is broken

### Scenario 1: 

GIVEN I am logged in to EPIC.track
WHEN I navigate to the My Workplans page
THEN I see the Screenshot below:

### Scenario 2: 

GIVEN I am logged in to EPIC.track
WHEN I navigate to the Insights page
THEN I see the Screenshot below:

### Screenshot 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzc5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0768817b52efd9cc9ee33382c4505e6f45ad8e8/Screen%20Shot%202023-11-22%20at%209.21.28%20AM.png)

**Comment by maria-kuzmenko** [comment]
link to the prototype - https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus%2FDashboard)?type=design&node-id=5455-6728&mode=design

**Comment by maria-kuzmenko** [comment]
.svg icon

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEQ5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6398dbe9ad8764471a13be08d9229e891c5eb90/development.svg)

**Comment by Connor1892** [comment]
change text under COMING SOON to:
"Our team is developing this feature and will launch it soon"

**Comment by Connor1892** [comment]
@TomChapmanGov can we add this to the About Project tab for Works as well?
