### ISSUE TITLE
Create Work Modal - Responsible Ministry

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1331]
---

Add choice of "None" or "N/A" for "Responsible Ministry"

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot @dinesh-aot 

there is no 'None' option in 'Responsible Ministry' or I'm a blind bat (which can be the case as well).

<img width="643" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnlUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d660a89324a4aeec171b4cb31be40bdc4abbc81d/Screen%20Shot%202024-01-02%20at%203.14.33%20PM.png" alt="Screen Shot 2024-01-02 at 3.14.33 PM.png" />

**Comment by jadmnsaad** [comment]
pending discussion decision with @maria-kuzmenko, discussion point is this task has been done with the interpretation that if we leave a select field as empty or we clear a previously chosen option making the select empty then that is the None option.

@Connor1892 @maria-kuzmenko 
Implications:
- If a we add a none option we should consider consistency, should we add none on all selects? How do we interpret empty selects then
- if we choose empty select as equivalent to choosing none, then should we remove none values that we added to some selects like the Federal Involvement
