### ISSUE TITLE
Status - Roles

### ISSUE THREAD

**Issue by TomChapmanGov** [bcgov/EPIC-FLOW#1332]
Refactor status to use new roles logic

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by ethanjorgensen** [comment]
@TomChapmanGov as a viewer, I can still edit approved statuses!

**Comment by Connor1892** [comment]
I can still edit approved status as a viewer

**Comment by Connor1892** [comment]
the edit button for an approved status needs to have the icon be the same disabled colour as the word

**Comment by Connor1892** [comment]
when I changed Maggie in the Admin menu to superuser, she (who is a viewer in keycloak) completely lost access to the system

**Comment by jadmnsaad** [comment]
Is this is now a duplicate to this https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/1586

**Comment by Connor1892** [comment]
I didn't think so, but I'll agree if you say it now is!
