### ISSUE TITLE
Role Specific pages

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1341]
---

Need to restrict by role the following:

- [x] List management - create button (super+)
- [x] List Management - edit existing (super+)
- [x] All work - create button (super+)
- [x] Status/Issues - edit approved status/issues (super+)
- [x] Task templates - create button (super+)
- [ ] Task Template - action column (super+)
- [x] Task Template - edit existing templates (super+)
- 

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
All these are still true, but I can't check which ones are done or not without the ability to change permissions

**Comment by Connor1892** [comment]
@dinesh-aot the task template actions bar is still accessible. I can delete templates

**Comment by dinesh-aot** [comment]
@djnunez-aot  Please check ROLES.Edit to allow the menu item accessible. Please check the UserList implementation

**Comment by maria-kuzmenko** [comment]
@Connor1892, @djnunez-aot, @dinesh-aot 

As a User, I should be able to open any modal on All Works, Projects etc - I just can't edit it, it will be greyed out. 
Now if I'm not a Superuser, but I want to see Work's details, I can't do it

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeldDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e5ac354409a7685d6691ae8f3b2cea430381e38/Screen%20Shot%202024-02-22%20at%2011.19.04%20AM.png" alt="Screen Shot 2024-02-22 at 11.19.04 AM.png" />

**Comment by Connor1892** [comment]
@maria-kuzmenko 

as a viewer you can see a work's details on the about page. is that enough?

**Comment by maria-kuzmenko** [comment]
@Connor1892 

@EAO-App-Admin said they should be able to open the modal, they just can't edit it. Some of them might be using it to double-check some information. I don't know what can be the use case to totally restrict showing this info. We can discuss

**Comment by Connor1892** [comment]
#1885 has been created!
