### ISSUE TITLE
Work Nation tab - Contact Card

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1342]
---

the contact card doesn't stay when you try to move the mouse onto the hoverstate card.
we need to be able to copy the email or phone number from the hoverstate card

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
Doesn't exist now.

**Comment by Connor1892** [comment]
does this need an estimate? or should this be closed as not planned?
