### ISSUE TITLE
Keep an eye on the Insights loading time

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/EPIC-FLOW#135]

**Comment by dinesh-aot** [comment]
I observed one thing today on redash analytics. I was trying to access analytics through the  formsflow web and getting error. I checked the pod of analytics server and there were some query related issues.
After a while later my debugging, I just logged in to analytics through it's own console and the console was available. Later when I tried to access analytics through formsflow web, it simply worked.

**Comment by dinesh-aot** [comment]
Planning to add more resources to the test environment. That might solve this issue.
