### ISSUE TITLE
Delegation Decision Logic

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1356]
**Overview**
Delegation Decision Logic.
For several WORK, there is a formal “Decision Delegation Event” on who will be responsible for the final WORK DECISION.
When a choice is made in the Decision Delegation Event, the appropriate “Name” needs to be updated to a few locations in the WORK and EVENTs
The “Decision Maker” field in Edit/View WORK modal must be updated to the appropriate “Name” when the ACTION is triggered (the “Name” might come from “CURRENT ACTIVE POSITION ###”)

The “Decision Maker” dropdown in the appropriate (usually final) WORK DECISION (usually the PHASE END EVENT of the LAST PHASE) EVENT modal must be updated to the appropriate “Name” when the ACTION is triggered (the “Name” might come from “CURRENT ACTIVE POSITION ###”)

**Comment by dinesh-aot** [comment]
The chosen decision make should be reflected only on the final decision

**Comment by Connor1892** [comment]
The Final Decision dropdown has the Minister, CEAO, ADM, & EPDs even after assigning it to be the CEAO in a delegation milestone
