### ISSUE TITLE
Special History - Team Tab Edit buttons

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1360]
---

Superuser edit buttons on team tab take user to modal to edit special history

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by jadmnsaad** [comment]
Is there a figma design of this @maria-kuzmenko @Connor1892 ?

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot, yes, we have it on Team tab right now implemented for superuser, just not functional

**Comment by jadmnsaad** [comment]
@maria-kuzmenko if there's a figma design for it can you please share it? any screenshot in the app also would help

**Comment by jadmnsaad** [comment]
@maria-kuzmenko if there's a figma design for it can you please share it? any screenshot in the app also would help
