### ISSUE TITLE
Set the actual date in the event form opens up with a date in the calendar points to the aniticipated date

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1383]

**Comment by dinesh-aot** [comment]
**Overview**
In the event for you can see anticipated date and actual date field.
The anticipated date will be auto filled in but you have to choose the actual. 
Most of the time the actual date would be around the anticipated date. 
The ticket is about to make the actual date picker points to the date in calendar where the anticipated date is set.

**Comment by maria-kuzmenko** [comment]
@dinesh-aot it shows the correct year and month but still point to the last day

<img width="682" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnhjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--123ff612eac8669764862b581e181dffe484d0a1/Screen%20Shot%202023-12-13%20at%203.56.56%20PM.png" alt="Screen Shot 2023-12-13 at 3.56.56 PM.png" />
