### ISSUE TITLE
Set the mindate of the actual date open for the first phase's first event

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1384]
**As a** team member

**I want** some rules around dates

**so that** I can put in the correct dates

### Scenario 1: 

GIVEN I am backdating the first milestone
WHEN I put in the anticipated or actual dates
THEN I need to be able to put any date from the past in.

### Scenario 2:

GIVEN I am backdating the 2nd (or later) milestone
WHEN I put in the anticipated or actual dates
THEN I need to be able to put any date AFTER the Phase_start date.

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
**Overview**
The datepicker date selection should be available for all dates only for the first phase's first event. For both anticipated and actual

**Comment by carlygreenehill** [comment]
"The datepicker date selection should be available for all dates only for the first phase's first event. For both anticipated and actual" @dinesh-aot  The Anticipated Date Picker lets me go back to really really early dates and select them. Is that part ok?

**Comment by Connor1892** [comment]
working in dev but not in test

**Comment by Connor1892** [comment]
Min date should be 1995-06-30 for any work in the system
