### ISSUE TITLE
Endevent anticipated rule should only be checked for legslated phases

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1388]

**Comment by dinesh-aot** [comment]
**How to check**
- Create any work
- Go to a non legislated phase
- try to change the anticipated date of the end event
- You should not get error and it should work as normal
- Go to legislated phase
- Do the same
- You should get an error message
- 
Note: Please comment on the error message as you will see my poor English skills there( lets Charlotte it)

**Comment by maria-kuzmenko** [comment]
@Connor1892, @dinesh-aot, created a card to Charlotte it
