### ISSUE TITLE
For optional milestones , the event form doesn't show the milestone type in the dropdown

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1391]

**Comment by dinesh-aot** [comment]
**How to check**
- Create any type of work
- Add an optional milestone in any date
- Open the added milestone in "Edit" mode
- You should be able to see the milestone type autofilled in the disabled dropdown component

**Comment by carlygreenehill** [comment]
The optional milestone appears autofilled and in the disable dropdown component!
