### ISSUE TITLE
WorkForm Tab index should be fixed

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1393]

**Comment by dinesh-aot** [comment]
Starting from the first control, you should be able to navigate to different controls in the form using your Tab key in the keyboard including the save and cancel buttons @djnunez-aot

**Comment by djnunez-aot** [comment]
Hey @maria-kuzmenko! I was working on this card and was wondering if this hover effect was enough for visual clarity on the save button <img width="430" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3VaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9540f4b6a9b169cf593614a10466d0f050af526f/image.png" alt="image.png" />
 if not we will need to update the styles for this
