### ISSUE TITLE
Create a DEMO Environment for Track

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/EPIC-FLOW#1418]
Set up a new demo environment 
so that
all the latest CODE but a copy of the PROD data so we can check on how it works, but with the caveat that nobody CHANGES the info...

The five (possible) environments for EPIC.system (.track, .inspect, etc.):
DEV:          This environment is mostly for the DEVs for merging new CODE and for UX/UI testing.

TEST:         This is for QA testing and only deviates from the PROD because it doesn’t have the CODE from the current SPRINT.

PROD:       This is the latest QA approved version of the CODE and is the environment where USERs do their actual work.

DEMO:      This environment has an approved version of the PROD code (not necessarily the latest version of the CODE) and either a “safe” dataset (if the DEMO will been seen by viewers that cant see real data) that is kept “clean” for demonstration purposes. The data might be wiped and re-installed on a regular basis to ensure any demos go smoothly.

TRAIN:      This is the same CODE as PROD but with only “list” data so that users can train on any aspects of the application on a clean environment.  There might be different “safe” or “prod” datasets depending on what is being learned.

**Comment by dinesh-aot** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1418?planning-poker) with Zenhub @saravanpa-aot

**Comment by dinesh-aot** [comment]
Added the basic set of configuration/data to start creating works.
