### ISSUE TITLE
Refactor the User listing in "Admin" menu with respect to the latest roles implementation

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1439]

**Comment by Connor1892** [comment]
when I changed Maggie in the Admin menu to superuser, she (who is a viewer in keycloak) completely lost access to the system

**Comment by dinesh-aot** [comment]
@Connor1892 I tried exactly the same in dev environment and I could see maggie has now SuperUser  role assigned. We should sit together to test this.
