### ISSUE TITLE
Create Work - no work created

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1467]
---

when creating party2 for ajax mine assessment, the work did not get created!

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
This happened only once and I think we have gone to production and many different types of works created and no one faced this issue ever. I think we can close this ticket until we see it is happening recurrently
