### ISSUE TITLE
Workplan Page - Accordion days left for Withdrawn/Termination

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1470]
---

when Withdrawing or Terminating a Work, the days left should be x/max where x is the day withdrawn. the phase is still complete, but the fraction should represent the reality.

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
@Connor1892  Could you please check this card. I am not sure this is valid at all or already done

**Comment by Connor1892** [comment]
Still needs to be done!

**Comment by dinesh-aot** [comment]
**How to reproduce**
- Create a project notification
- Go to the first phase
- Just add actual to the first event
- Check the days left value in the accordion header, it must be zero
- Add a new milestone, "Project Withdrawal", put a date a few days later than the first completed event
- This will terminate the work and deactivate all the future events and phases
- Check the days left

**Actual**
- Days left would be shown as the total number of days in the phase

**Expected**
- Days left should be the difference between the last event date and the first event

**Comment by carlygreenehill** [comment]
@Connor1892 -- any comments for Dinesh here?
