### ISSUE TITLE
Workplan Page - Assessment slowdown causing popup delays

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1471]
---

because assessment is so heavy duty, when locking milestones, the final confirmation popup stays too long. long enough to be interactable even after the database change has gone through.

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by jadmnsaad** [comment]
@dinesh-aot @Connor1892 steps to reproduce please?

**Comment by Connor1892** [comment]
@jadmsaadaot dinesh actually fixed this I'm pretty sure.
