### ISSUE TITLE
Status tab - role restrictions

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1472]
---

team member should be able to approve statuses regardless of role (viewer, superuser, etc.)
team member should see edit button (disabled)

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
Duplicate of #1586
