### ISSUE TITLE
Status Tab - report preview

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1473]
---

replace the status preview on status tab with the report preview from issues tab
exact same funtionality

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot 

Reports Preview on Status Tab still have Issues highlighted but that should be Status

**Now:**
<img width="1641" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNStUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e057de9bcb1ff0185e4503746ee0210173646c5/Screen%20Shot%202024-01-02%20at%203.01.09%20PM.png" alt="Screen Shot 2024-01-02 at 3.01.09 PM.png" />

**Should be:**
<img width="1639" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkNUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee2ce2c125a74e2031a06cc28445acd477ab8301/Screen%20Shot%202024-01-02%20at%203.01.45%20PM.png" alt="Screen Shot 2024-01-02 at 3.01.45 PM.png" />

When Status is added and approved, Reports Preivew should show this

<img width="1193" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNldUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38642d99259135318ae1516964862fe11c047dc0/Screen%20Shot%202024-01-02%20at%203.05.31%20PM.png" alt="Screen Shot 2024-01-02 at 3.05.31 PM.png" />

If there are any Issues on this Work, they should appear after the Status without green box and same appearance as the Status has on Issue tab

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot 

Status preview once approved, should appear on both 30-60-90 and Referral Schedule 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG5kQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41e1d450a7c0d144f22d90138fe8ffca0d82b59b/Screen%20Shot%202024-01-18%20at%203.03.02%20PM.png" alt="Screen Shot 2024-01-18 at 3.03.02 PM.png" />

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot 

Report Preview should have the same structure regardless of what tab it is on:

1. Project Description
2. Phase
3. Status
4. Issues

Right now it changes based on what tab it is on
**Status Tab**
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzc0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--442dc19201d39eb2b55cd7ef337faa0a93445876/Screen%20Shot%202024-01-24%20at%204.24.46%20PM.png" alt="Screen Shot 2024-01-24 at 4.24.46 PM.png" />

**Issue Tab**
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0Q1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ccb3ea0db19e68a3bfaea00eecb713903690927/Screen%20Shot%202024-01-24%20at%204.25.52%20PM.png" alt="Screen Shot 2024-01-24 at 4.25.52 PM.png" />

**Comment by jadmnsaad** [comment]
@maria-kuzmenko thank you for letting me. I'm sorry but this last requirement wasn't clear before in the description, in the previous comments, or figma in this task. Can we please approve and close this and open any further clarifications/ requirement in a new task?

**Comment by Connor1892** [comment]
@jadmsaadaot @maria-kuzmenko 
I'm closing this card as complete and have linked #1752 as the new card to finish the refinements for this feature.
