### ISSUE TITLE
Issues Tab - post testing enhancements

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1474]
---

- rename the "Clone" button to "New Update" 
- show History title even when nothing in history
- add Issue title as header in the Report & Report Preview

<img width="1424" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDkxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a241cbfdddd1f062cb017207b3692bf0866ef576/Screen%20Shot%202023-12-19%20at%202.28.16%20PM.png" alt="Screen Shot 2023-12-19 at 2.28.16 PM.png" />

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , 

figma file for reference - https://www.figma.com/file/E92XoEegK2fLQ3odMeyWBD/Development-(Issues_Status_Dashboard)?type=design&node-id=4771-13633&mode=design
