### ISSUE TITLE
Status Tab - post testing enhancements

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1475]
---

- rename the "Clone" button to "+ New Update" 
- show History title even when nothing in history 
- 

<img width="1421" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2QwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1fc35e80375bdd0d040e100b2bf8aad8cf0104f6/Screen%20Shot%202023-12-19%20at%201.51.04%20PM.png" alt="Screen Shot 2023-12-19 at 1.51.04 PM.png" />

**Comment by maria-kuzmenko** [comment]
<img width="50" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2gwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99149e98e254a3e12a44dff3a5491da3c158f18b/status%20history.svg" alt="status history.svg" />

**Comment by maria-kuzmenko** [comment]
link to design - https://www.figma.com/file/E92XoEegK2fLQ3odMeyWBD/Development-(Issues_Status_Dashboard)?type=design&node-id=12-3793&mode=design
