### ISSUE TITLE
My Workplans - Post test card enhancements

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1483]
- [x] Align Project Name in the center
- [x] Change color for Project Name to neutral/dark
- [x] Remove 'Active' status for Project
- [x] Remove icon identifier next to the phase
- [x] Change 'View' button to secondary 'View' button with fixed width of 80px
- [ ] Make fixed margins between Team and Lead of 16px
- [x] Fix weird margins behaviour for the team, staff and lead (now they are super close to the bottom)
- [x] Change font for cards avatar from 800 to 400 (unbold them)

<img width="833" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGwwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55a5500e5180d8099cee2bcd7ebb1154265e75e0/Screen%20Shot%202023-12-19%20at%201.25.32%20PM.png" alt="Screen Shot 2023-12-19 at 1.25.32 PM.png" />

**Comment by maria-kuzmenko** [comment]
@Connor1892 

the unticked bullet point will be addressed in a separate card
