### ISSUE TITLE
Nations Tab - Info + Hoverstate on Active

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1484]
---

we need an info icon next to active on the Add/Edit Nation Modal.
Like a little Information Icon, comes with a hover state | like this >>> [?]

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
@EAO-App-Admin what should be put on the hover state?

**Comment by Connor1892** [comment]
needed to explain what constitutes an "Inactive" Nation

**Comment by carlygreenehill** [comment]
Geoff supplying the Instructions!!! :)

**Comment by Connor1892** [comment]
@djnunez-aot 
From Geoff:

"A Nation is considered INACTIVE if it is no longer being consulted/notified about the PROJECT"

**Comment by maria-kuzmenko** [comment]
@djnunez-aot we have a common component for the information icon at All Works > Create Work
we should have the same implementation for FN Active status

<img width="788" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0ZOQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7955a0e042a618a3debc9be409587fdbb54cf88/Screen%20Shot%202024-04-10%20at%2010.36.55%20AM.png" alt="Screen Shot 2024-04-10 at 10.36.55 AM.png" />

**Comment by djnunez-aot** [comment]
thank you will fix that up

**Comment by Connor1892** [comment]
too much padding between Active & info icon!
should be the same as other modals
