### ISSUE TITLE
About Tab - Super user

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1491]
**As a** Super User

**I want** to be able to edit all the information about a Work and attached Project 

**so that** I don't have to jump to 3 different places to do my updates

### Scenario 1: 

GIVEN I am on the Work Page
WHEN I click on the About tab
THEN I see an Edit button on both:
- Project panel
- Work panel

<img width="1428" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1I2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11eaf1e05f06ecadd50101e0d12bd1657b3afdd8/Screen%20Shot%202023-12-20%20at%2012.45.31%20PM.png" alt="Screen Shot 2023-12-20 at 12.45.31 PM.png" />

![image](https://github.com/bcgov/EPIC.track/assets/126211473/c7c7f180-da57-4824-82a4-8a4242e30bab)

### Scenario 2:

GIVEN I am on the About Page
WHEN I click on the Project Panel's Edit Button
THEN I see the Edit Project Modal

### Scenario 3:

GIVEN I am on the About Page
WHEN I click on the Work Panel's Edit Button
THEN I see the Edit Work Modal

**Comment by maria-kuzmenko** [comment]
link to prototype - https://www.figma.com/file/E92XoEegK2fLQ3odMeyWBD/Development-(Issues_Status_Dashboard)?type=design&node-id=28-5035&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1491?planning-poker) with Zenhub @dinesh-aot @jadmsaadaot @saravanpa-aot

**Comment by dinesh-aot** [comment]
Include the scope of changing the current way of implementation of the Work and Project forms. They are currently tied together to the MasterContext. We should have these forms as regular stand alone forms.

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , edit project modal has some weird margins 

1. Work modal (shows as intended)
<img width="780" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGVIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a27de9f14625feeae15eee475d123e6faadd46d/Screen%20Shot%202024-02-23%20at%209.20.09%20AM.png" alt="Screen Shot 2024-02-23 at 9.20.09 AM.png" />

2. Project Modal (weird margins)
<img width="777" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGlIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd45e1053e7b6092e8fd99869998e18e1724ba7b/Screen%20Shot%202024-02-23%20at%209.20.34%20AM.png" alt="Screen Shot 2024-02-23 at 9.20.34 AM.png" />

**Comment by maria-kuzmenko** [comment]
@Connor1892, we can create a separate ticket for this weird project margins thing of low priority.

**Comment by Connor1892** [comment]
#1913 has been created for the margins
