### ISSUE TITLE
About Tab - Team Member

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1492]
**As a** Team Member

**I want** a place for all the information about a Work and attached Project 

**so that** I am able to see all the information related to my Work in one place

### Scenario 1: 

GIVEN I am on the Work Page for an Assessment or Earlier Worktype
WHEN I click on the About tab
THEN I see the following:
 - Details (default)
 - Calendar (not active. to be added later)

on Details:
- Project panel
- Work panel
- Resources

#### Project Panel:
- Project Creation Date
- Proponent
- Project Description (ability to Read More/Read Less)
- Type
- Subtype
- Location Description (ability to Read More/Read Less)
- ENV Region
- NRS Region
- Abbreviation

#### Work Panel:
- Work Start Date
- Anticipated Referral Date
- Current Milestone (truncated)
- Next Milestone (truncated)
- Work Description (ability to Read More/Read Less)
- EA Act
- Federal Involvement
- Federal Act
- Responsible Ministry
- Decision Makers (title of decision maker, not the name)

<img width="1424" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1o2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--17880c8564c42129ef8aeed74a3310edaf9b1274/Screen%20Shot%202023-12-20%20at%2012.46.11%20PM.png" alt="Screen Shot 2023-12-20 at 12.46.11 PM.png" />

### Scenario 2:
GIVEN I am on the Work Page for a Post Assessment Worktype
WHEN I click on the About tab
THEN I see the following:

#### Project Panel:
- Certificate Number
- Certificate Issued

![image](https://github.com/bcgov/EPIC.track/assets/126211473/0f831013-8986-410a-864f-95ecfa0ebf03)

### Scenario 3:
GIVEN I am on the About tab
WHEN I look at the Resources panel
THEN I see the following:
- Link to EPIC.Public (contextual to jump to the page about this Work)
- Link to eGuide
- EA Act (2018) (contextual to act this work is under)

#### Project Panel:
- Certificate Number
- Certificate Issued

**Comment by maria-kuzmenko** [comment]
link to prototype - https://www.figma.com/file/E92XoEegK2fLQ3odMeyWBD/Development-(Issues_Status_Dashboard)?type=design&node-id=28-5340&mode=design

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot 

a couple of bugs:

- [x] there should be left and right margins of 24px. Now there are multiple divs with their own margins.<img width="687" 
 src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTJqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--554bf052eee6571daae16ceeaff4f043d96788cd/Screen%20Shot%202024-01-05%20at%204.27.00%20PM.png" alt="Screen Shot 2024-01-05 at 4.27.00 PM.png" />

- [x] same for the top padding - should be just 16 px. 

<img width="708" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOStqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1bced3c86623897b9e9af89501b50a229d39b60c/Screen%20Shot%202024-01-05%20at%204.27.50%20PM.png" alt="Screen Shot 2024-01-05 at 4.27.50 PM.png" />

- [x] All font should be the same 
    color: rgb(49, 49, 50);
    font-size: 0.875rem;
    line-height: 1.2rem;
    font-weight: 400;

Now for Project Type, Subtype, Env Region, NRS Region have letter spacing 0.39px
Now for Work Current/Future Milestones, EA Act, Federal Involvement, Federal Act have letter spacing 0.39px

<img width="544" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1NqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d08ad14fa179a3d7c9270723474d52b49adc9169/Screen%20Shot%202024-01-05%20at%204.30.51%20PM.png" alt="Screen Shot 2024-01-05 at 4.30.51 PM.png" />

**Comment by Connor1892** [comment]
@jadmsaadaot 
Work Panel is Missing Work Description

**Comment by jadmnsaad** [comment]
Work Description Added
