### ISSUE TITLE
Make sure all date picker components used in the application is using the shared/Datepicker

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1502]
**Overview**
It is required to make sure all datepickers including both regular date pickers and date pickers in the form ultimately use the common control from share/Datepicker. This is to ensure all the date pickers get some common configurations such as month selection, format of the date ...etc

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , 

1. When I use the date picker while 'Adding Task' on Workplan, there is no option to select month (not a common component)

Steps to reproduce:
1. Open any work -- Click 'Add Task' -- Try to select the month in Start Date and End Date, you will be able to select a year, not a month

**Comment by jadmnsaad** [comment]
@maria-kuzmenko I think this task was more of a technical enhancement. Not very sure if the above is in scope. I tested the workplan form and I can see that I can edit the month
<img width="527" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNitjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--212dd29d02b3d5fa6b271d206132fb88501e9662/image.png" alt="image.png" />

Can you please recheck and share snapshots, and if it's still happening can we create a separate task for it plz?

**Comment by jadmnsaad** [comment]
@maria-kuzmenko looked into this, the component is working fine locally, the code of this task was not deployed to dev as we noticed there's an unrelated issue blocking dev deployment. Once that is fixed this can be tested again. @dinesh-aot is looking into the dev deployment issue

**Comment by jadmnsaad** [comment]
@maria-kuzmenko, we can retest this now, the problem is solved in dev

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , working, thanks!
