### ISSUE TITLE
Make the special field implementation similar across different places in the application

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1504]
**Overview**
Take EPD and LEAD special field implementation as an example and implement the rest of the special fields in the same way.

**Comment by salabh-aot** [comment]
@dinesh-aot all existing implementations of SpecialField are done similar to EPD & Lead implementations after I updated Proponent form component in last commit.  If this ticket is about adding new special fields, can you list them here or link individual tickets for those?
