### ISSUE TITLE
About Page - Current Milestone

### ISSUE THREAD

**Issue by TomChapmanGov** [bcgov/EPIC-FLOW#1512]
Add logic to get the current milestone. (Logic already exists to get next milestone)

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
when I complete a phase, the next milestone shows as blank.

It should show as the first milestone of the next phase.

**Comment by Connor1892** [comment]
when I complete a phase, the current milestone shows as blank.

It should show as last milestone of previous phase.

**Comment by jadmnsaad** [comment]
@Connor1892 if this meets everything already discussed can we please close it? And in case there's anything new can we open a new ticket?
