### ISSUE TITLE
List Management - Staff Modal Save button locks

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1537]
**Describe the bug**
After changing a few entries on the staff table, the save button stops working on the staff modal.

**To Reproduce**
1. Go to List management
2. Click on and change staff member
3. Repeat as necessary

**Expected behavior**
should be able to edit staff indefinately

**Screenshots**

**Additional context**

**Comment by djnunez-aot** [comment]
I tried recreating this bug could not reproduce it would love some help @Connor1892  @dinesh-aot

**Comment by Connor1892** [comment]
seems to be working? @dinesh-aot I'm happy to close this as unplanned if you're okay as well

**Comment by dinesh-aot** [comment]
> seems to be working? @dinesh-aot I'm happy to close this as unplanned if you're okay as well

I will check it again and let you know. Cz I was able to reproduce it before.
