### ISSUE TITLE
List Management - Project Modal Save button failure

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1543]
**Describe the bug**
Every time I press save I get the "Error during processing the request" warning

**To Reproduce**
1. Go to List management (projects)
2. Click on any project name
3. click save

**Expected behavior**
should save and close modal

**Screenshots**

**Additional context**
I updated a special history entry for the angus project from no history to one entry. not sure if bug existed before this or not, but it's happening on other projects too.

**Comment by dinesh-aot** [comment]
Now all the special fields has a default value. So couldn't reproduce this issue. I tried to create a new project with required fields only and it is working. I tried to update the same and still working.
