### ISSUE TITLE
Text changes

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1545]
---

- Change "About Project" Tab to "About" Tab
- create work modal, Project description = remove ghost text & disable field
- change "Teams" tab to "Team" tab
- in About tab, change "Calender" to "Calendar"
- EAC Assessment phase "EAC Assessment Intake" should be renamed to "Pre-Early Engagement"
- George Heyman, Minister of ENV is mispelt as "Hayman"
---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
**Things to do**
- Make change in phase tab and events tab of the excel
- Migration to change the phase name in work phases of the existing works

**Comment by Connor1892** [comment]
Minister of ENV George Heyman is still misspelt.
currently Hayman, should be Heyman

**Comment by dinesh-aot** [comment]
@Connor1892 These changes are no longer needed to be made through database migration in the backend. We have Staff UI to manage their names. You can do this in through the application front end. I will make the corresponding change in the Staff Excel we are maintaining in the teams folder.
