### ISSUE TITLE
Report Previews - Work Description

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1546]
---
Work Description is currently showing only on the 30-60-90 report.
we need it to be shown on the report preview for status & issues

---

**As a** user

**I want** to have the work description on the reports preview

**so that** I have a complete understanding of what will show on reports

### Scenario 1: 

GIVEN I am on a work page
WHEN I navigate to either the Status or Issues tab
THEN I see the Work Description auto populated underneath the Project Description
THEN I see the Phase information under the Work Description

![image](https://github.com/bcgov/EPIC.track/assets/101662408/5c22b567-5015-4d06-9171-adb1cb104899)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
@jadmsaadaot this is already done correct?

**Comment by maria-kuzmenko** [comment]
@Connor1892, we can push this one into the development, no design work is needed other than specifying that Work Description on 30-60-90 and Referral schedule tabs should be pulled right after Project Description.
