### ISSUE TITLE
Issue Tab - Enhancements

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1552]
### Scenario 1: 

GIVEN Issue Tab is opened
WHEN I added an Issue 
THEN I see the following edits:
- the tags (active, Prioirity) are next to the issue title
- Start date is shown instead of last update date
- action and edit button are added to the accordion

### Screenshot 1

<img width="1426" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTZpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9102fe9a251f71111195287edc197518bf4646d9/Screen%20Shot%202024-01-05%20at%2012.12.15%20PM.png" alt="Screen Shot 2024-01-05 at 12.12.15 PM.png" />

### Scenario 2:
GIVEN the issue accordion exists
WHEN I click on the Accordion Edit button
THEN I see the Edit Issue Modal with the Description field hidden

![5362d058-247b-422c-9ced-d3142f79574d](https://github.com/bcgov/EPIC.track/assets/126211473/ee258e73-3d66-435f-9676-bc008129bf3e)

### Scenario 3:
GIVEN the issue accordion is open
WHEN I click on the Description Edit button
THEN I see the update description modal with the date picker and text field and Modal Title 'Edit Description'
THEN I see the Description field has 500 char limit

### Screenshot 3
<img width="616" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXlpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1c361df25cbbe925d957a6e16c574eaa1ea0437/Screen%20Shot%202024-01-05%20at%2012.11.36%20PM.png" alt="Screen Shot 2024-01-05 at 12.11.36 PM.png" />

### Scenario 4:
GIVEN the issue accordion is open
WHEN I click on the New Update button
THEN I see the update issue modal with the date picker and text field and Modal title 'Update Description'
THEN I see the Description field has 500 char limit

### Screenshot 
<img width="609" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWFpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55b929168388824ed168365b4bf9d942a6a8a41f/Screen%20Shot%202024-01-05%20at%2012.10.46%20PM.png" alt="Screen Shot 2024-01-05 at 12.10.46 PM.png" />

**Comment by Connor1892** [comment]
@dinesh-aot this card is not in test yet. Scenario 3 only shows 250 in TEST but the proper 500 in DEV

**Comment by jadmnsaad** [comment]
@Connor1892 if the 500 appears in dev then it's just a deployment issue and no more coding is pending on it right as the ACs are met? Can we close it?
