### ISSUE TITLE
User with VIEWER role should have access to view everything unless he is a team member of a particular work

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1579]
**Overview**
- A user with VIEWER  roles should be able to view the workplan tab, but not make any changes
- But if they are a TEAM MEMBER, then they should be able to edit the work plan

Actions included:
- Add Task
- Add Milestone
- Edit Task
- Edit Milestone
- Row edits

**Comment by maria-kuzmenko** [comment]
@dinesh-aot, 
I tested it with Taya, and though she wasn't able to add tasks or Milestones, she could:
- edit status
- add/edit issues
- add team member

She should not be able to do anything like that if she is not a member of a team

**Comment by jadmnsaad** [comment]
@maria-kuzmenko  This ticket is about only the first tab the workplan tab, 
<img width="1222" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlRkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cea24d1a00153d8759ccadb98d98dd0cc625aa84/image.png" alt="image.png" />

the below ticket is for the status and issues

https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/1586

**Comment by maria-kuzmenko** [comment]
@Connor1892, should we create a separate ticket to disable stuff on the Issues/Status/Team/Nations tabs? 
cause Viewer now can do all those things even if they are not a member of a team

UPD. Connor, I can see that we have the ticket for Issues/Status. Can you create a ticket for Team/Nation tabs?

**Comment by Connor1892** [comment]
@maria-kuzmenko linked both cards as dependant on this one
