### ISSUE TITLE
My Workplans - Search Specificity

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1583]
**Describe the bug**
When searching "Eskay", if I type but don't select from dropdown, when I hit enter the search doesn't show "Eskay Creek"
the functionality should be to show all the projects in the dropdown, but if no option is selected, show all works to which Eskay applies

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jadmnsaad** [comment]
@Connor1892 I couldn't replicate this issue, I was able to enter Eskay and Eskay Creek.  Can you confirm it's still happening?
