### ISSUE TITLE
Status & Issue - Role Permissions

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1586]
**Describe the bug**
Team member viewers should be able to:
- Status
  - add a new status
  - approve status
  - edit un-approved status
- Issues
  - add a new issue accordion
  - update existing issue
  - approve issue
  - edit un-approved issue

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , please fix this scenario

**Bug description:** As a Viewer who is not assigned to a Team, I can click on 'Add Status' button when there is no Status on the Work

**Steps to reproduce:**
1. Log in as a Viewer
2. Pick a Work that you are not a member AND that does not any Status
3. Open Status Tab
4.  You will see a message saying you can add Status
5.  Add Status button is active

**Desired effect:**
Add Status button should be disabled
