### ISSUE TITLE
Staff Page - Enhancements

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1588]
---

Order Positions based on Heiarchy
The correct order is as follows
<img width="484" alt="image" src="https://github.com/bcgov/EPIC.track/assets/97143739/1089fa5f-abb9-4fd4-956c-655a7cc307de">

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
The staff response already has "position" as a nested object in which you will see a field called "sort_order" which can be used to get this done
