### ISSUE TITLE
My Workplans - Assessment Phase Colours

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1589]
---

Colour for the all phases names on My Workplans should have the value of #003366

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by jadmnsaad** [comment]
hmmm does this need a design decision from @maria-kuzmenko?

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot, no, we have the colour phase in Dev it somehow didn't merge for Prod 

PROD view
![Screen Shot 2024-01-17 at 4 13 48 PM](https://github.com/bcgov/EPIC.track/assets/122938967/58d65efe-05c7-47ba-953e-83c74ee116fb)

DEV view
![Screen Shot 2024-01-17 at 4 14 20 PM](https://github.com/bcgov/EPIC.track/assets/122938967/56349081-be98-41ba-95d2-ac861771bb85)

**Comment by jadmnsaad** [comment]
@dinesh-aot this is in Dev but not in Prod, does this mean that we just need to deploy?

**Comment by dinesh-aot** [comment]
@jadmsaadaot  You are right. I am expecting this would be resolved after a deployment to the production. I am waiting for getting a test sign off from test environment for updating the prod. So we can park this ticket for a while and wait for the next production release.

**Comment by jadmnsaad** [comment]
hey @dinesh-aot!, I noticed this is in the sprint backlog now, any update on the above discussion?

**Comment by dinesh-aot** [comment]
The issue is still there in prod after the latest release. So this is something to be investigated.
