### ISSUE TITLE
My Workplans - Work name 

### ISSUE THREAD

**Issue by ethanjorgensen** [bcgov/EPIC-FLOW#1630]
---

it's going to replace the worktype text.
90% of the time it will end up being the same text, but in the 10% of cases where it's an amendment or other weirdness we need to have the work name for things to make sense

---

**As a** Team member

**I want** the Work name to show on the Work cards

**so that** I can tell my Amendments apart

### Scenario 1: 

GIVEN ... I am on My Workplans page
WHEN ... I look at a Work card
THEN ... instead of Work type, I see Work name with the Project name removed

**Comment by jadmnsaad** [comment]
I think this needs a UI design decision. The current design doesn't include a name and it needs to be updated.

https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus%2FDashboard)?node-id=5443%3A3495&mode=dev

**Comment by Connor1892** [comment]
the default work title is X + Y where:
- X = Project Title
- Y = Work type

but sometimes the title needs to be different. for example amendments are identical to each other from the My Workplans page. in these cases the superuser creating the work will add a suffix to the Work title which is Z where:
- Z = specific Identifier

so the result from this ticket is for the Worktype on the Work Card to be replaced with the work title (X+Y+Z) minus the Project Title (X) so we only see Y+Z.

When Z doesn't exist it will just show the Worktype, but when it does it will handle the duplicate title problem.
