### ISSUE TITLE
List Management - Project Page - Add Proponent Name

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1631]
**As a** user

**I want** to be able to filter projects by proponent

**so that** I can see a full list of projects owned by any given proponent

### Scenario 1: 

GIVEN I am on the Project List
WHEN I start filtering
THEN I see the "Proponent" filter to the right of "Subtype"

**Comment by dinesh-aot** [comment]
- Show the proponent field in the grid

**Comment by djnunez-aot** [comment]
@dinesh-aot does this task include fetching proponents from the backend

**Comment by dinesh-aot** [comment]
> @dinesh-aot does this task include fetching proponents from the backend

I don't think. The proponent field is already there in the project response. Shall we use that
Plus, you can place it between SubType and ENV Region fields in the listing

**Comment by maria-kuzmenko** [comment]
@dinesh-aot weird filter behaviour here

<img width="1185" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFRkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5049f24898e8a59e188fb8871262bca83bdf8cb6/Screen%20Shot%202024-01-18%20at%202.59.16%20PM.png" alt="Screen Shot 2024-01-18 at 2.59.16 PM.png" />

**Comment by djnunez-aot** [comment]
<img width="1128" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGpoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6e107c7e86e8303c914094b0aaed54cbfdf7385/image.png" alt="image.png" />
Seems like the issue is some of the proponent names are very long should we set a max width ? @dinesh-aot

**Comment by dinesh-aot** [comment]
@djnunez-aot Lets fix the maxWidth to 328 Px.
