### ISSUE TITLE
API tests for Issues and Status

### ISSUE THREAD

**Issue by saravanpa-aot** [bcgov/EPIC-FLOW#1636]
**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
@saravanpa-aot I need an estimate on this
