### ISSUE TITLE
Remove the Environment Banner from production environment

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1637]
*Overview*
- The current way is to check the keyword in the window.location.hostname which is not good
- We can have env in the config map(environment variable) - check it for "dev, test, demo or localhost" to show the banner

**Comment by maria-kuzmenko** [comment]
@dinesh-aot , prod still have a test banner

<img width="1535" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWJJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d4f251a3597cd5f850c222004ebf3b705bad6ab/Screen%20Shot%202024-01-15%20at%209.33.31%20AM.png" alt="Screen Shot 2024-01-15 at 9.33.31 AM.png" />
