### ISSUE TITLE
Work "Title" is 80 Characters - Should it be 80 or more than that. Lets set it to 150

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1640]
- Change the front end validation
- Put the character counter above the text field
- Change the character limit in the back end using migration

**Comment by dinesh-aot** [comment]
- Change the front end validation
- Put the character counter above the text field
- Change the character limit in the back end using migration

**Comment by djnunez-aot** [comment]
@dinesh-aot In the back end title is already set to 150 
<img width="818" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3pCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8765f8db5ba790584fa0898f5e8a9b134e1cf9f3/image.png" alt="image.png" />

created a pr https://github.com/bcgov/EPIC.track/pull/1659 to address the first two bullet points

**Comment by maria-kuzmenko** [comment]
@dinesh-aot work Title goes into negatives now. Did we discuss to stop at 150?

<img width="1497" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenJkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47aa9316fcea0c19f36d534d89ba4a68fbbc77b0/negativecount.png" alt="negativecount.png" />
