### ISSUE TITLE
Make staff emails lower case

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1642]
*Things to do*
- Make it lower in the database over migration
- Make sure it is all lowercase before you save it in database for future saves
- Make this change in the data excel that we keep

**Comment by Connor1892** [comment]
@dinesh-aot please make sure that the staff list you've got is from the PROD env.
Ryan fixed a bunch of things in PROD and I'm seeing a few of them showing up in DEV & TEST now.
(specifically spaces in emails and some spelling things)
