### ISSUE TITLE
Role Access - As an EAO staff with an IDIR you are granted Viewer role by default

### ISSUE THREAD

**Issue by ethanjorgensen** [bcgov/EPIC-FLOW#1649]
**As a** person with an IDIR who works in the EAO

**I want** to have viewer access to EPIC.track by default

**so that** a white screen does not block me from accessing EPIC.track.

### Scenario 1: 

GIVEN ... you have an IDIR and work in the EAO
WHEN ... you log into EPIC.track
THEN ... you can view EPIC.track

### Scenario 2:
GIVEN ... you have an IDIR and do not work in the EAO
WHEN ... you log into EPIC.track
THEN ... you are met with an error message: Sorry, you don't have permission to access this page; if you think you should have access, please contact the administrator for assistance.

**Comment by dinesh-aot** [comment]
Based on the latest discussion, people should not see data unless we intentionally grant them access. So setting the default role automatically doesn't work. 
Till Jan, the plan is to have blank screen there and Connor or anyone with user management permission in epictrack can login to the app and go to Admin->Users , find the user and assign them appropriate role.

The long term plan is to show them a screen and let them know who to contact to get permission or send an automated email to the sytem email address to let someone know that there is an access request generated and act accordingly.
