### ISSUE TITLE
Make sure all the special fields has the latest entry put in tot he history tables

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1651]
**Overview**
- Proponent Name - Proponent Form
- EPD, LEAD - WorkForm
- ProjectName, Proponent - ProjectForm
- The above mentioned are the current set of special fields in the app as of now
- Create a migration script so that each of them has the latest entry as the first history entry with start date as the MIN_WORK_START_DATE (you will find this constant in the app)

**Comment by Connor1892** [comment]
@saravanpa-aot need an estimate on this

**Comment by Connor1892** [comment]
@saravanpa-aot 
I can see there's an entry in all these fields now, but did it only update the ones that didn't have an entry? is there any risk of the entries making their way to PROD?
I was doing some testing around special history and have junk data in some of these that didn't get overwritten
