### ISSUE TITLE
Refactor the reusable chip components to have less padding

### ISSUE THREAD

**Issue by jadmnsaad** [bcgov/EPIC-FLOW#1656]

**Comment by Connor1892** [comment]
@jadmsaadaot tell me more about that

**Comment by Connor1892** [comment]
can we give this to @djnunez-aot ?

**Comment by Connor1892** [comment]
all chips should be like the ones on status.
Projects page needs to be fixed.

Thanks a lot Jad

**Comment by Connor1892** [comment]
![image](https://github.com/bcgov/EPIC.track/assets/126211473/95a50f95-b32d-4013-8422-e600a9c9f4ca)

@djnunez-aot the inactive chip should be grey not red
