### ISSUE TITLE
Resource Forecast sort order logic

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1669]
**Overview**
The priority of the work types are as follows
- WorkType == 6 and SecondPhase.PhaseStartEvent has Actual Date
- WorkType == 6 and SecondPhase.PhaseStartEvent has no Actual Date
- WorkType == 5
- WorkType == 7
- WorkType == 11
- WorkType == 2
- WorkType == 3
- WorkType == 1
- WorkType == 9
- Then WorkType == 10, 12, 13, 14
All sorted within their category by workTitle by Natural Sort

**Comment by dinesh-aot** [comment]
Refer - [Resource Forecast Report Logic](https://apps.nrs.gov.bc.ca/int/confluence/x/aoB9Cw)

**Comment by Connor1892** [comment]
need to get Correct sort order

**Comment by dinesh-aot** [comment]
@Connor1892 can you provide any details for us to reproduce

**Comment by carlygreenehill** [comment]
BLOCKED:  needs to be reproduced and tested

**Comment by dinesh-aot** [comment]
Change the "EA Type" column of work type "Assessment" if the current phase is Pre-EA(EAC Assessment) to "Pre-EA". 
This change in the result should reflect in the downloaded file also.
