### ISSUE TITLE
Update the frontend changes for new worktypes

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#167]

**Comment by dinesh-aot** [comment]
**Acceptance Criteria**

- Try to load the new work types in UI
- Make sure the data is loading in to the UI as expected
- Make sure the phases, events, and engagements are being loaded as expected.
- Submit a work type and see if it is getting created as task and able to modify it from the task menu and resubmit.

**Comment by salabh-aot** [comment]
Tested the changes. Everything seems to be working fined.
