### ISSUE TITLE
User Admin page redesign - Height of rows changes depending on role

### ISSUE THREAD

**Issue by ethanjorgensen** [bcgov/EPIC-FLOW#1678]
**As an** Instance Admin and System Admin

**I want** the size of the rows displaying the users to appear as the same size (56.800 pixels high)

**so that** there is consistency across users

### Scenario 1: 

GIVEN ... I am an Instance Admin
WHEN ... I am viewing the User page
THEN ... each row that displays the user at 56.800 pixels high

### Scenario 2:
 GIVEN ... I am a System Admin
WHEN ... I am viewing the User page
THEN ... each row that displays the user is 56.800 pixels high

**Comment by maria-kuzmenko** [comment]
@ethanjorgensen , the card is not clear enough. If we are talking just about resizing rows, now UI/UX needed, and this should be specs for devs only
