### ISSUE TITLE
Roles Restriction - Team Member control on Team & FN

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1709]
---

only team members assigned to a work should be able to add/edit team & first nation tabs on that work

Only Team members (and superusers) should be able to:
- add nation
- import nations
- export nations
- add team member
- edit nation
- edit team member
---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , please fix this scenario

**Bug description:** As a Viewer who is not assigned to a Team, I can click on 'Add nation' button when there is no Nation on the Work

**Steps to reproduce:**
1. Log in as a Viewer
2. Pick a Work that you are not a member AND that does not have any Nations in the list
3. Open Nations Tab
4.  You will see a message saying you can add or import nation 
5.  Add Nation button is active

**Desired effect:**
Add Nation button should be disabled

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , @dinesh-aot 

I am sure I saw this button disabled when I'm not a member of that team, but now it is active. 
this one should be disabled

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXlDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ddc11a6547bcdc7ae4801063766416c365df3de/Screen%20Shot%202024-02-22%20at%2011.13.56%20AM.png" alt="Screen Shot 2024-02-22 at 11.13.56 AM.png" />

**Comment by maria-kuzmenko** [comment]
first nations Tab is all good

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTJDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--323ef1b3c9af6b7498be57c97e93f763b6c122d6/Screen%20Shot%202024-02-22%20at%2011.15.16%20AM.png" alt="Screen Shot 2024-02-22 at 11.15.16 AM.png" />

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot, I can Import Nations as a viewer not assigned to a team.

Steps to reproduce:
1. Pick up Work with Project that has multiple different works (29694 Marshall Road Extension)
2. Select Work with no First Nation assigned
3. Open First Nation Tab
4. Import Nations button is active

**Desired effect:** Import Nations button is disabled.


<img width="1724" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnVoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e72ec9b82d2fefb4757128e7d3785c53307d1342/Screen%20Shot%202024-02-29%20at%202.26.48%20PM.png" alt="Screen Shot 2024-02-29 at 2.26.48 PM.png" />
