### ISSUE TITLE
Workplan Page - Viewer persmission problems

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1714]
---

- The Download Workplan button should be disabled for non-team members
- when a viewer looks at the workplan they are not assigned to, they see a select label where the bulk action box is for team members. this should not appear. it should be a disabled checkbox.

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by jadmnsaad** [comment]
"when a viewer looks at the workplan they are not assigned to, they see a select label where the bulk action box is for team members. this should not appear. it should be a disabled checkbox." 

It should not appear or it should be a disabled checkbox

**Comment by Connor1892** [comment]
the select label should not appear.
the disabled checkbox should.
