### ISSUE TITLE
Position of buttons and labels in the work form

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#172]
**Overview**
- Project Form
   - "Type" dropdown placement in the form
   - "FLNR" label change - change to "NRS Region" - Place it near FI 
- Work Form
  - Substitution Act to the "Work Details" Panel
  - Minister label to "Second Responsible Minister"

**Comment by carlygreenehill** [comment]
Need from Business Area (Carly/Geoff/Connor) - Show tooltip on input control to indicate it's purpose - give copyto DInesh

**Comment by carlygreenehill** [comment]
Project Form - CARLY CHECKED IN DEV

- "Type" dropdown placement in the form - NOT DONE!

- ~~"FLNR" label change - change to "NRS Region" - Place it near FI~~ DONE

Work Form

- ~~Substitution Act to the "Work Details" Panel~~ DONE
- ~~Minister label to "Other Responsible Minister"~~ DONE

**Comment by Connor1892** [comment]
![EPIC-FLOW#172](https://user-images.githubusercontent.com/126211473/228330731-3b47b2c6-776d-4046-ad50-160b7c307f92.PNG)
