### ISSUE TITLE
Amendment Worktype - name changes

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1721]
---

Under the phase amendment procedures, the milestones should be called ‘Amendment Procedures’ not ‘Assessment Procedures’

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by jadmnsaad** [comment]
can we add more to the discerption? Not sure I understand which component this about, which page, which scenario?

**Comment by Connor1892** [comment]
Worktype: Amendment -> Phase: Amendment Procedures -> rename 2 milestones. they currently say "assessment procedures", they should say "amendment procedures"

@dinesh-aot was going to do a fix to existing works as well.

**Comment by dinesh-aot** [comment]
**Things to do**
- Make corresponding changes in the amendment excel template
- migration script to find event configurations and update it with "assessment procedures"

**Comment by maria-kuzmenko** [comment]
@dinesh-aot , I can see this name in the phase 'Amendment Application Review (Typical)' - is this the correct one having assessment in it?

<img width="1136" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1pDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ce9ff1686e37552a43994ccad8da759cc9eaf0a/Screen%20Shot%202024-02-08%20at%2011.08.58%20AM.png" alt="Screen Shot 2024-02-08 at 11.08.58 AM.png" />
