### ISSUE TITLE
First Nations Tab - PIN Column update

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1722]
**As a** team member

**I want** to replace the PIN column with a consultation level column

**so that** I can track multiple different levels of First Nation Engagement with my Work

### Scenario 1: 

GIVEN I am on the Work page
WHEN I select the First Nations Tab
THEN I see the second column of the grid is Consultation instead of PIN

### Scenario 2:

GIVEN I am on the First Nation Tab of my Work
WHEN I open the edit nation modal for a nation added to my Work
THEN I see the dropdown is now for Consultation Level

### Scenario 3:

GIVEN I am on the edit nation modal of my Work
WHEN I select the dropdown for Consultation
THEN I see the following options:
1)	PIN
2)	Consult
3)	Metis (federal only)
4)	Other

**Comment by dinesh-aot** [comment]
We can create a new table called "consultation_levels" and put the above mentioned values in it

**Comment by Connor1892** [comment]
Consultation describes the level of interaction a Nation has with a Work.
- PIN means they have a legal right in regards to this work
- Consult means they have no legal right, but are kept informed anyway to maintain relationships
- Metis are only relevant to Federally linked Works (for substituted & coordinated etc.)
- Other is to catch unforeseen future needs
