### ISSUE TITLE
Issue Tab - Restrict past values for posted date for work updates

### ISSUE THREAD

**Issue by jadmnsaad** [bcgov/EPIC-FLOW#1729]
UPDATE FROM CARLY, MARCH 19

We need more information:
 - Date restriction based on when the Issue was approved - can't go backwards 
 
---  

Users now are able to manually add a posted date, this creates a problem where a user can add a date that is  before an existing approved update. We need to handle that

- Add min date prop
- Change ordering of issue updates to order by posted_date

FROM GEOFF:
"Once an Issue/Status has been approved, no UPDATE to this Status/Issue can be "back-dated" and dates before the latest UPDATE are greyed out"

--- 

FYI 
![image](https://github.com/bcgov/EPIC.track/assets/101662408/c1f8afc8-eb21-4c06-bc4e-aa0bdebd91f7)
should include fixing this https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/2005

**Comment by Connor1892** [comment]
if Issue history changes to be displayed by posted date rather than input date, this becomes a big deal!

**Comment by dinesh-aot** [comment]
@Connor1892  Are we waiting for further information on this card?

**Comment by dinesh-aot** [comment]
Need to test it to see if it is already completed
