### ISSUE TITLE
My Workplans - Toggle default for unassigned users

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1750]
**As a** user

**I want** to have the workplans toggle OFF by default is I am not assigned to a Work

**so that** I can see all the works in the system immediately

### Scenario 1: 

GIVEN I have no Work teams
WHEN I log into EPIC.track
THEN I see the toggle off
THEN I see all the works in the system.

**Comment by jadmnsaad** [comment]
@Connor1892  I can meet you in the middle on this.

To do this we have to know initially whether this user is assigned to anything or not. Currently we do not know that. Meaning this toggle doesn't know if the user is assigned to anything or not to decide if it is toggled or not.

What I can do now is initially it will be toggled, if no workplans were loaded we can toggle it off automatically (only for the first time)

and we can have a different conversation whether we want to fetch and store membership data for our user on app log in or something

**Comment by Connor1892** [comment]
that works for me!

confirming when you say only first time, you mean only on page load will it be toggled off and if they toggle it on again it will show the no works found message?

**Comment by jadmnsaad** [comment]
@Connor1892 yes exactly, this auto toggle it off will only happen once on page load if there were no assigned works loaded

**Comment by Connor1892** [comment]
when I am inactive on a work, I still show up on the staff card. this prevents this feature from performing correctly

**Comment by Connor1892** [comment]
@jadmsaadaot do you want a separate bug ticket? or can that fix be done in this card?

**Comment by jadmnsaad** [comment]
@Connor1892 can we please create a separate bug ticket for this "when I am inactive on a work, I still show up on the staff card. this prevents this feature from performing correctly"

**Comment by Connor1892** [comment]
#1865
