### ISSUE TITLE
Prepare Excel template to load data for different 

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#176]
**Overview**
This templates are going to be used to prepare data to be loaded to the EPIC FLOW system. For each form in EPICFLOW, there is going to be an excel template. The column names of the excel would be the field names in the form.

Most of the forms like project, organization, indigenous nation and staff is going to be simple and easy to create. 

Work form has a different hierarchy of data, which needs some special attention. 
Also, there are some fields in some form are a reference from a different look up table such as responsible_epd in organization is the staff, so, when creating the template it is important to provide another lookup excel where you can find the most recent version all the lookup tables.

# Sub Tasks
- [x] #270
- [x] #271
- [x] #273
- [x] #274

**Comment by carlygreenehill** [comment]
Let's come back to this card to see if we need to close it, and let 272 exist on its own.
