### ISSUE TITLE
Integrate New phase colors

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1761]
**Overview**
Assessment
Early Engagement - d4e0e2
Readiness Decision - f6dad8
Proponent Time - d3d4d5
Process Planning - c0cddc
Application Review - d2e4f3
Effects Assessment & Recommendation - f9e9c4
Decision - cbe0cf

Ammendment
All Phases - e4dfec

**Comment by dinesh-aot** [comment]
[Colours for Reports - EPIC.track (1).xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2M5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab84602edc9777bfa0384ad72fa890ff3d98e195/Colours%20for%20Reports%20-%20EPIC.track%20%281%29.xlsx)

The excel sheet contains the finalized colors for assessment and amendment work types. 
- Update the Assessment and Amendment event template excel colors
- Add a new input field in the Resource Forecast API for accepting the opactity(25%)
- Make the corresponding API change in the front end as well(hard code the opacity required for resource forecast as 25%)
- Please verify the final 25% opacity color produced by the library is same as that of the excel

**Comment by maria-kuzmenko** [comment]
@dinesh-aot 

we discussed with @jadmsaadaot colours and the question is about all Pre-EA works that have this specific colour
https://www.figma.com/file/dwlYoKngyXkuBoEGiEld1h/Design-System?type=design&node-id=167-2285&mode=design

do we have this colour in the system as well?

**Comment by Connor1892** [comment]
@dinesh-aot , for project notification and all PRE-EA works we have the same colour. Please see my comment above.

**Comment by dinesh-aot** [comment]
@maria-kuzmenko All the intake phases are having this color configured #3eb1d7

**Comment by maria-kuzmenko** [comment]
@dinesh-aot yes, all intake phases - CEAO's Designation, Minister's Designation, Pre-EA, Exemption Order, etc

**Comment by dinesh-aot** [comment]
Discussed it and all works in new phases.
