### ISSUE TITLE
MyWorkPlan toggle when user who is not in any teams

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1766]
**Overview**
What should be the default behavior of the "MyWorkPlans" toggle if the user logged in is not part of any teams.

**Comment by jadmnsaad** [comment]
@dinesh-aot this is explained and addressed here https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/1750
