### ISSUE TITLE
SPIKE - Assess Gantt chart libraries in React

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1771]
---
name: User Story
about: 'User Story '
title: ''
labels: ''
assignees: ''

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
@jadmsaadaot pls confirm this estimate

**Comment by jadmnsaad** [comment]
@Connor1892 estimate is good, thanks

**Comment by jadmnsaad** [comment]
some skeleton implementation of the gantt chart:
<img width="637" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWNtQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e18a5eb08c5f767215ad1bfd308bb12315fd2bfc/image.png" alt="image.png" />


<img width="697" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWdtQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3fd5c9fb946ebd1cd1772940a4009c00cad723f2/image.png" alt="image.png" />

<img width="596" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWttQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--905d966993481bae025d392f39a6b7c5be9f1b2b/image.png" alt="image.png" />

<img width="647" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXNtQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a9204c8fc3c9b10cda4160d3a2b286692607246/image.png" alt="image.png" />

**Comment by jadmnsaad** [comment]
Regarding use of libraries, if we chose to. There are these options:

Free libraries:
Best I found is Google Charts: simple and satisfies basic gantt chart needs. Limits us in customizing it.
rest of options are mid

Paid Libraries: Very extensive set of features with the obvious con of having to pay for it
- Bryntum
- DHTMLX

**Comment by jadmnsaad** [comment]
My Feasibility assessment.

I'm confident we can implement it ourselves. Especially confident about implementing our basic needs.  We keep the advantage of being able to further customize it this way. 

con: less certainty and possibility of buggy first versions.

We can always fall back on Google charts if it was buggy and we were very short on time.

**Comment by jadmnsaad** [comment]
https://docs.google.com/presentation/d/1x6pEyPjULSujlWhswQfO2_mFUYUBZ0Xlp3r6-bkjyaA/edit?usp=sharing

**Comment by jadmnsaad** [comment]
https://apps.nrs.gov.bc.ca/int/confluence/pages/viewpage.action?pageId=194511400
