### ISSUE TITLE
Script to load data from Excel template to the EPICFLOW application

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#178]
**Overview**
Develop a script to load data from the Excel and process it using the APIs of formsflow.
Take a reference to the below test script to get an idea of the apis to be called to get the form submission done.
[https://github.com/bcgov/EPIC-FLOW/tree/main/tests/performance/submission-load/src](url)

The work form is going to be most difficult one as it has many relations to be mapped.

**Comment by dinesh-aot** [comment]
Update the project mapper in the migration script based on the latest project template shared

**Comment by carlygreenehill** [comment]
Here's what is left to complete on this card:
- some tweaks

**Comment by carlygreenehill** [comment]
Let's revisit this card to see if we need to close it, and break off other "tweak" issues as we know those may be ongoing.
