### ISSUE TITLE
MyWorkPlan - Non Staff View

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1787]
**Overview**
When a non-staff user login to the application
Go to MyWorkPlan Page
Since the user is not a staff, there should be no work plans listed for him if he chooses to turn the toggle on

**Comment by Connor1892** [comment]
@dinesh-aot what am I testing here?

**Comment by dinesh-aot** [comment]
@Connor1892  I just updated the description above. Let me know if you need help in testing this.
