### ISSUE TITLE
List management - Contact cards

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1791]
---

the names for relationship holders on both nation and proponent pages should have a contact card hoverstate

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
@djnunez-aot, this one is not working properly. 
we have a specific implementation to show it - it should be reflected everywhere

please see video for the reference

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMytCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbfe2de8e3e6424db603b7384f5ed6bb12e3a2fc/20240222090806471.mp4)
