### ISSUE TITLE
Resource Forecast report download failed

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1792]

**Comment by maria-kuzmenko** [comment]
@dinesh-aot , resource forecast doesn't retrieve anything - I clicked on 2024-02-08, got an error message and the spinning wheel is forever there.

**Comment by dinesh-aot** [comment]
@maria-kuzmenko @EAO-App-Admin 
HVC 2040 - EAC Assessment in test environment has second phase inactive due to the decision taken in the pre-ea phase.
We will not have a second phase moving forward. Early Engagement is going to be the first phase. the sort logic will have to be changed accordingly
