### ISSUE TITLE
Resource Forecast - Download Button is broken

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1799]
### UPDATED BY CARLY MARCH 19

**Describe the bug**
When Selecting the download button the system gives an error message

**To Reproduce**

1. Go to RESOURCE FORECAST in PROD ENV
2. Click on DATE PICKER > NOV 6, 2023
3. Observe that the report takes 10 seconds to load
4. Hit Download
5. Red X - notification error appears - no download happens

**Expected behavior**
A downloaded PDF

**Screenshots**

**Additional context**
Not happening in TEST

**Comment by salabh-aot** [comment]
I tested the download button in both DEV & TEST environments. It worked both times. Can you provide more info on how to reproduce? (May be a screen recording will help figure out if it is an edge case for specific dates) @Connor1892 @dinesh-aot

**Comment by Connor1892** [comment]
I can't remember the situation that caused this card to be created, but currently in Dev when I use Oct 1 2023 it just spins forever.

If that's not to do with RF specifically we can kill this card @salabh-aot
