### ISSUE TITLE
Special History - Edit Work Modal - Team Lead

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1815]
**Describe the bug**
Jad couldn't add Brennan Hutchison as a new Lead.

**To Reproduce**
1. Go to edit work modal
2. Click on team lead lock button
3. add a new entry

**Expected behavior**
I should be able to add a new Special History Team Lead, and if I can't, I should see an error message that explains why

**Screenshots**
![image](https://github.com/bcgov/EPIC.track/assets/101662408/47b41072-dc98-4943-8134-a4513a593521)

**Additional context**
lindsey luke (the previous lead) was from: today to: today, brennan was also added today. could it be a 0 day duration problem?

**Comment by salabh-aot** [comment]
Issue happens when we try to add new entry, with from date as last entry's from date + 1 day. Effectively making last entry's time range as a single day. Is this a valid use case?

**Comment by dinesh-aot** [comment]
@salabh-aot I talked to @EAO-App-Admin . The above mentioned scenario will never occur. So we can show an error message if someone chooses to add another entry with the very next day.

**Comment by salabh-aot** [comment]
@dinesh-aot any suggestions on what error message to show? If we need to show below the input field, we only have limited space and only a small message can be shown, like, `Invalid from date`. Another option is to mark the datefield as error (red border) and show an error notification. What are your thoughts?

**Comment by dinesh-aot** [comment]
@maria-kuzmenko any suggestion for the error message.

**Comment by maria-kuzmenko** [comment]
@dinesh-aot , proposed verbiage 

The selected date range must span at least one day. Please ensure that the 'from' and 'to' dates are different to proceed

link to prototype - https://www.figma.com/file/XcYynwH7xrO2P30uqewaLS/For-Development?type=design&node-id=81-1432&mode=design

**Comment by maria-kuzmenko** [comment]
<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekFFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b976c1b031d36b9bb44d7021639fa3fa5ae8bd5f/Screen%20Shot%202024-03-22%20at%201.23.03%20PM.png" alt="Screen Shot 2024-03-22 at 1.23.03 PM.png" />

**Comment by jadmnsaad** [comment]
@Connor1892 we discussed this and we decided to meat further on it with @maria-kuzmenko. 

The issue isn't just when a user doesn't match the to and from dates but when they add a new entry with a from date that is directly after (1 day +) the last entries from date.

How should we handle that is the question

**Comment by jadmnsaad** [comment]
this ticket is linked to this https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/2153

**Comment by jadmnsaad** [comment]
This task is now:

Raise an error in the backend and alert the user when they add  a bad date entry (like +1 day after latest from date)
