### ISSUE TITLE
Displaying the app version in the UI

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1816]
---
name: User Story
about: 'User Story '
title: ''
labels: ''
assignees: ''

---

**As a user of epic.track**

**I want to see the version of the app**

**so that I know which version am I using**

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
bottom of the menu
