### ISSUE TITLE
Add dropdown list of substitution acts in the work primary section

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#182]
**Overview**
Add an optional dropdown field in the work form to choose the Substitution Act if the work has one. The content of the dropdown can be 
- CEAA 2004
- CEAA 2012
- IAA (2019)
- NONE

EDIT FROM CARLY: please move Substitution field to be in Work Details instead of Primary

**Comment by SnehaSuresh-aot** [comment]
![image.png](https://images.zenhubusercontent.com/628dc136794b5129b5a22e56/4040854c-dfdf-49eb-8081-1cbfb4ca7b59)

**Comment by carlygreenehill** [comment]
Add none to list then this card can be complete.

4 choices - NONE then the 3 acts
