### ISSUE TITLE
Insights - Dashboard

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1821]
**As an** Executive

**I want** a dashboard for my insights

**so that** I can navigate easily

### Scenario 1: 

GIVEN I am logged into EPIC.track
WHEN I select the Insights menu item
THEN I see a dashboard of all available Insights

### Validation Rules? 

(If yes, list here)

### Screenshot 

![MicrosoftTeams-image (3)](https://github.com/bcgov/EPIC.track/assets/126211473/3ef83552-53c2-4b7f-901c-184c9f068d3d)

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
link to navigation - https://www.figma.com/file/dwlYoKngyXkuBoEGiEld1h/Design-System?type=design&node-id=975%3A1671&mode=design&t=kjWqhjVkm6E9fwj4-1

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1821?planning-poker) with Zenhub @jadmsaadaot @dinesh-aot @djnunez-aot
