### ISSUE TITLE
Load decision maker based on the responsible ministry chosen in the work to show the staff dropdown in the events grid

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#183]
**Overview**
There are certain milestones which involves decision to made. For such milestones, it should be possible to choose who is going to take that decision and this should be modifiable later. 
It is possible to choose the responsible person from the list of staffs and also can be filtered based on the responsible ministry chosen in the work.

**Comment by carlygreenehill** [comment]
List of names is too long / not filtered enough. Tried by Geoff, need walk through on behaviors with a dev. 

- Decision event completely disappearred

**Comment by EAO-App-Admin** [comment]
List is now filters to only ministers, but doesn't limit the list to just the minister of selected ministry
