### ISSUE TITLE
Work Timeline - General Timeline View

### ISSUE THREAD

**Issue by maria-kuzmenko** [bcgov/EPIC-FLOW#1832]
**As a** User

**I want** to be able to view the work timeline

**so that** I can view all filtered works across the timeline

### Scenario 1: 

Jad's note: please check my comment below

GIVEN My Workplans is open
WHEN I click on Timeline button 
THEN I see all filtered works with phases displayed on the timeline:
- A timeline of years and months
- A work name list section
- A phase bars section

### Screenshot 
<img width="1128" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjFKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f623cbac9d25820e918f10073b9e9259453ace3f/Screen%20Shot%202024-02-09%20at%203.15.40%20PM.png" alt="Screen Shot 2024-02-09 at 3.15.40 PM.png" />

**Comment by maria-kuzmenko** [comment]
link to prototype - https://www.figma.com/file/GsrDa5tsU1xWj8MGPfylCs/Development-(Issues_Status_Dashboard)-(Copy)?type=design&node-id=304-2773&mode=design

**Comment by jadmnsaad** [comment]
@maria-kuzmenko @Connor1892 

I will use this ticket to implement:

- The gantt chart displays the work title on the left
- The Time line exists
- The phase bars appear under the timeline

I will duplicate this to implement the previously put Acceptance Criteria which I'm almost done with.
I just needed to implement the basic structure of this component first

new ticket https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/1856
