### ISSUE TITLE
Text change - Pre-Early Engagement ->Pre-EA

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1838]
---
rename first assessment phase from "Pre-Early Engagement" to "Pre-EA"

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
@salabh-aot  I will do this change
