### ISSUE TITLE
WorkList is not auto refreshing

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1839]
**Describe the bug**
The Work List page is not auto refreshing when you create a new work.

**To Reproduce**
1. Go to AllWorks
2. Click on Add Work Button
3. Check if the newly created work showed up in the list

**Expected behavior**
The newly created work should show without page refresh

**Screenshots**

**Additional context**
Please check if the problem is there in the Project List. This might have originated when you separated the WorkList and ProjectList from MasterContext

**Comment by carlygreenehill** [comment]
@dinesh-aot    I thought we had a similar card in QA that we saw resolved. Just checking if this is duplication. I went to add a new work and got a error notification that work cannot be saved.

**Comment by carlygreenehill** [comment]
DUPLICATE CARD

**Comment by carlygreenehill** [comment]
DUPLICATE CARD
