### ISSUE TITLE
Keep the short status and last updated data in one of the tabs

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#185]
**Overview**
The short status field will be updated many times during the period of a work by multiple users. There should be a way to keep track the history of all these changes and show the latest in the reports with the updated date.

**Comment by dinesh-aot** [comment]
**Overview**
It should contain a status text box and a label which indicate the timestamp on which the status created. Once a status created and submitted it cannot be updated, instead a new status can be created.

**Comment by dinesh-aot** [comment]
Please add a date picker. The date picker should be of the same format as that of other date pickers in the form. 
The label of the date picker should be "Posted Date". When you give id to the date picker take a look at the column name. The database column name should be the id of the date picker control.

**Comment by carlygreenehill** [comment]
Card has been fulfilled. Client has asked for NAME of the user who updated to be listed
