### ISSUE TITLE
Insights - Dashboards

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1850]
**As a** user

**I want** visualizations of the data in EPIC.track

**so that** I can better understand the state of work in the office

### Scenario 1: 

GIVEN I am logged into the system
WHEN I select to the Insights page
THEN I see the Work and Project accordions

#### Scenario 2:

GIVEN I am on the Insights page
WHEN I look at the Work Accordion
THEN I see the following:
    - title: Work Dashboard
    - show more button
    - Tab buttons
        - Staff Button (primary) (selected by default)
        - General button
        - Partners button
    - Pie Charts
        - Work by team
        - Work by Lead
        - Work by Staff

#### Scenario 3:

GIVEN I am on the Insights page
WHEN I look at the Project Accordion
THEN I see the following:
    - title: Project Dashboard
    - show more button
    - Map
        - Project by Region
    - Pie Charts
        - Project by type
        - Project by subtype with filter defaulted to 'Mines'

### Screenshot 

<img width="971" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1dPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48694a84efeaaf33e9b2c35246809d221afce627/Screen%20Shot%202024-02-26%20at%202.59.24%20PM.png" alt="Screen Shot 2024-02-26 at 2.59.24 PM.png" />

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1850?planning-poker) with Zenhub @dinesh-aot @djnunez-aot @jadmsaadaot

**Comment by maria-kuzmenko** [comment]
link to Figma file - https://www.figma.com/file/GsrDa5tsU1xWj8MGPfylCs/Development-(Insights)?type=design&node-id=390-95&mode=design

**Comment by Connor1892** [comment]
@jadmsaadaot 
- Missing the Project Accordion.
- also, pls reorder Work Accordion so that it goes:
General, Staff, Partners

**Comment by jadmnsaad** [comment]
In this task the accordion component was created and the code layout was designed. We can add the project accordion here https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/1854 when we implement the project dashboard. Given this, can we consider this done and closed?

**Comment by Connor1892** [comment]
@jadmsaadaot can we swap the buttons in this card or is there somewhere else you'd like that put?
