### ISSUE TITLE
Insights - Work Dashboard - General

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1851]
**As a** user

**I want** Visualizations for the Work Data in EPIC.track

**so that** I can better understand the state of Works in the system

### Scenario 1: 

GIVEN I am on the Insight page
WHEN I select the see more button on the Work Accordion
THEN I see the accordion expand to full
THEN I see the Work dashboard grid

### Scenario 2:

GIVEN I am on the Insights Page AND I have opened the Work dashboard accordion  AND I have General Selected
WHEN I look to the First Visualization
THEN I see the Work by Type pie chart with the following:
- all active works broken down by worktypes
- a number for each slice that shows how many works are represented
- A colour coded legend that identifies each worktype present

### Scenario 3:

GIVEN I am on the Insights Page AND I have opened the Work dashboard accordion AND I have General Selected
WHEN I look to the Second Visualization
THEN I see the Assessments by Phase pie chart with the following:
- all active works of type Assessment broken down by phase
- a number for each slice that shows how many works are represented
- A colour coded legend that identifies each phase present

### Scenario 4:

GIVEN I am on the Insights Page AND I have opened the Work dashboard accordion AND I have General Selected
WHEN I look below the Visualizations
THEN I see the Work Dashboard grid with the following:
- Work (search)
- Project (dropdown)
- Worktype (dropdown)
- Phase (dropdown)
- Status (dropdown)

### Screenshot 

<img width="956" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmVQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80649c729b33e21a3a38b92f932e91feec38fb14/Screen%20Shot%202024-02-26%20at%204.54.06%20PM.png" alt="Screen Shot 2024-02-26 at 4.54.06 PM.png" />

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1851?planning-poker) with Zenhub @dinesh-aot @djnunez-aot @jadmsaadaot

**Comment by maria-kuzmenko** [comment]
link to Figma - https://www.figma.com/file/GsrDa5tsU1xWj8MGPfylCs/Development-(Insights)?type=design&node-id=392-982&mode=design

**Comment by Connor1892** [comment]
Legend needs to be spaced away from the pie charts so they can show the number

**Comment by Connor1892** [comment]
Show more grid should default to the same as other grids where there is a default ALL option in the pagination.

**Comment by jadmnsaad** [comment]
@Connor1892 fixed in another PR that is currently in review, can we please close this
