### ISSUE TITLE
Insights - Work Dashboard - Partners

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1853]
**As a** user

**I want** Visualizations for the Work Data in EPIC.track

**so that** I can better understand the state of Works in the system

### Scenario 1: 

GIVEN I am on the Insight page
WHEN I select the see more button on the Work Accordion
THEN I see the accordion expand to full
THEN I see the Work dashboard grid

### Scenario 2:

GIVEN I am on the Insights Page AND I have opened the Work dashboard accordion AND I have Partners selected
WHEN I look to the First Visualization
THEN I see the Work by Other Ministry pie chart with the following:
- all active works broken down by Other Ministry
- a number for each slice that shows how many works are represented
- A colour coded legend that identifies each Other Ministry present

### Scenario 3:

GIVEN I am on the Insights Page AND I have opened the Work dashboard accordion AND I have Partners selected
WHEN I look to the Second Visualization
THEN I see the Work by Federal Involvement chart with the following:
 - all active works broken down by Federal Involvement option
- a number for each slice that shows how many works are represented
- A colour coded legend that identifies each Federal Involvement option present

### Scenario 4:

GIVEN I am on the Insights Page AND I have opened the Work dashboard accordion AND I have Partners selected
WHEN I look to the Third Visualization
THEN I see the Nation Involvement by Number of Works bar chart with the following:
- all Nations attached to active Works, sorted by most to fewest
- a bar that shows how many works that Nation is attached to (pulled from Nation tab)

### Scenario 5:

GIVEN I am on the Insights Page AND I have opened the Work dashboard accordion AND I have Partners selected
WHEN I look below the Visualizations
THEN I see the Work Dashboard grid with the following:
- Work (search)
- Other Ministry (dropdown)
- Federal Involvement (dropdown)
- First Nations (dropdown)

### Screenshot 

<img width="908" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkNhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f15e7f9acc6dddea0b66b6ffeba9232ea9f877b/Screen%20Shot%202024-02-28%20at%2011.07.30%20AM.png" alt="Screen Shot 2024-02-28 at 11.07.30 AM.png" />

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1853?planning-poker) with Zenhub @dinesh-aot @djnunez-aot @jadmsaadaot

**Comment by maria-kuzmenko** [comment]
link to Figma - https://www.figma.com/file/GsrDa5tsU1xWj8MGPfylCs/Development-(Insights)?type=design&node-id=430-227&mode=design

**Comment by jadmnsaad** [comment]
@Connor1892 @dinesh-aot  can we please break off having the nations column in the grid to a separate task. We need to add that

**Comment by Connor1892** [comment]
#1953 created

**Comment by dinesh-aot** [comment]
@jadmsaadaot  this is how it looks in my laptop
<img width="1417" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkc5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c78411fe92cc5938914aaebf149c616bb91b01e/image.png" alt="image.png" />

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot, 
1. as per Scenario 5, there should be a column with all first nations associated with this project.
2. Can we have more space for the nation name and have all of them as a string with truncation? Any ideas of how to get rid of the nation being eaten, would be great. 
<img width="910" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0RPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37e4baec646139d5725c9d763493ba61deb59dbe/Screen%20Shot%202024-03-11%20at%201.50.21%20PM.png" alt="Screen Shot 2024-03-11 at 1.50.21 PM.png" />

**Comment by jadmnsaad** [comment]
@maria-kuzmenko thanks for the review, can we please address  that in a bug ticket?

**Comment by jadmnsaad** [comment]
@dinesh-aot can we please open a bug ticket for responsiveness

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , the bug ticket should be added for the responsiveness, but I feel that a column with FNs is within this ticket as this is a part of one of the ACs. What do you think?
