### ISSUE TITLE
Insights - Project Dashboard

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1854]
**As a** user

**I want** Visualizations for the Project Data in EPIC.track

**so that** I can better understand the state of Projects in the system

### Scenario 1: 

GIVEN I am on the Insight page
WHEN I select the see more button on the Project Accordion
THEN I see the accordion expand to full
THEN I see the Project dashboard grid

### Scenario 2: (talk to Kate about this one)

GIVEN I am on the Insights Page AND I have opened the Project dashboard accordion
WHEN I look to the First Visualization
THEN I see the Project by Region map with the following:
- all active Projects broken down by Region
- a number for each area of the map that shows how many Projects are represented
- A colour coded legend that identifies each region present

### Scenario 3:

GIVEN I am on the Insights Page AND I have opened the Project dashboard accordion
WHEN I look to the Second Visualization
THEN I see the Project by Type pie chart with the following:
- all active Projects broken down by Type
- a number for each slice that shows how many Projects are represented
- A colour coded legend that identifies each Type present

### Scenario 4:

GIVEN I am on the Insights Page AND I have opened the Project dashboard accordion
WHEN I look to the Third Visualization
THEN I see the Project by SubType pie chart with the following:
 - a dropdown to select Type
 - all active Projects broken down by SubType of the Type chosen in the dropdown
 - a number for each slice that shows how many Projects are represented
 - A colour coded legend that identifies each Subtype present

### Scenario 5:

GIVEN I am on the Insights Page AND I have opened the Work dashboard accordion 
WHEN I look below the Visualizations
THEN I see the Work Dashboard grid with the following:
- Project (dropdown)
- Type (search)
- Subtype (dropdown)
- Proponent (dropdown)
- Region ENV (dropdown)
- Region NRS (dropdown)

### Screenshot 

<img width="889" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNSthQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b332cc77d030bfbddb8cbdcc5f399e2d81e5a12/Screen%20Shot%202024-02-28%20at%2011.44.36%20AM.png" alt="Screen Shot 2024-02-28 at 11.44.36 AM.png" />

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1854?planning-poker) with Zenhub @dinesh-aot @djnunez-aot @jadmsaadaot

**Comment by maria-kuzmenko** [comment]
link to prototype - https://www.figma.com/file/GsrDa5tsU1xWj8MGPfylCs/Development-(Insights)?type=design&node-id=431-772&mode=design

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , Scenario 4 doesn't work as intended. We should have in the dropdown the list of Types and when the Type is chosen, the pie chart shows Subtypes.

<img width="1311" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFhPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3cc1bc0e75661f3ce350a9e7c91ecb65632ccb06/Screen%20Shot%202024-03-11%20at%201.37.08%20PM.png" alt="Screen Shot 2024-03-11 at 1.37.08 PM.png" />
