### ISSUE TITLE
Work Timeline - Implement phase bar design and add scroll functionality

### ISSUE THREAD

**Issue by jadmnsaad** [bcgov/EPIC-FLOW#1856]
**As a** User

**I want** to be able to view the work timeline

**so that** I can view all filtered works across the timeline

### Scenario 1: 

GIVEN My Workplans is open
WHEN I click on Timeline button 
THEN I see all filtered works with phases displayed on the timeline:
- vertical scroll bar to scroll through the bar section
- horizontal scroll bar to scroll through the timeline
- Use phase colors for the bars

### Screenshot 
<img width="1128" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjFKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f623cbac9d25820e918f10073b9e9259453ace3f/Screen%20Shot%202024-02-09%20at%203.15.40%20PM.png" alt="Screen Shot 2024-02-09 at 3.15.40 PM.png" />

**Comment by Connor1892** [comment]
@jadmsaadaot , @dinesh-aot - all pre-EA worktypes AKA Project Notification, CEAO's Designation, Exemption Order, Minister's Designation should be of the same colour. 

The correct colour right now has only Minister's Designation. Can we make Project Notification same one?

**Comment by jadmnsaad** [comment]
@Connor1892 can we please create a new ticket for this?

**Comment by Connor1892** [comment]
@jadmsaadaot #1944 created and linked
