### ISSUE TITLE
My Workplans - not able to remove Work cards from My Workplans

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1865]
**Describe the bug**
when I am inactive on a work, I still show up on the staff card. this prevents this feature from performing correctly

**To Reproduce**
1. Go to any workplans on My Workplan page
2. Click on team tab
3. make yourself inactive on that work
4. go back to my workplans and see that the work is still there

**Expected behavior**
any works that do not have me as a ACTIVE team member (or as an EPD/Team Lead) should not show on My Workplans

**Screenshots**

**Additional context**

**Comment by Connor1892** [comment]
updating special history should update the team tab for that work

**Comment by dinesh-aot** [comment]
Update the lead in the work page should reflect in team tab in work plan
