### ISSUE TITLE
All Work - title truncation & hoverstate

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1872]
---

we need the title column to act the same way as the list management

---

**As a** user

**I want** to have a hoverstate on All works

**so that** I can see the long title without opening a modal

### Scenario 1: 

GIVEN I navigate to the All Works Page
WHEN I hover over the title of a Work
THEN I see the same functionality as in the List management pages
THEN I see the hoverstate with the full

![image](https://github.com/bcgov/EPIC.track/assets/101662408/9aa87b3b-1ef1-48cd-9159-210ed617d5bd)

### Scenario 2:
 
GIVEN I navigate to the All Works Page
WHEN I hover over the title of a Work
THEN I see the names too long to be displayed have been truncated
THEN I see the hoverstate with the full name of the work

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
@Connor1892  Just wanted to make sure both this scenarios demand to have the hover state for long/short titles.right?

**Comment by Connor1892** [comment]
@dinesh-aot the hoverstate should happen no matter the length of the title. is that the question?
