### ISSUE TITLE
All Filters Expected Ordering

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1874]
---
**CARLY/CONNOR: please add more info to this card - like a table checklist of all pages with Filters/Tables/Filter Headers**

update TableFilter to have natural sort by default

the only exception should be Staff page in List management. (and only because the position filter has already been sorted hieratically)

---

**As a** user

**I want** Natural sorting to be the default on filters

**so that** I know where I can expect to find options in the dropdown

### Scenario 1: 

GIVEN I am interacting with any grid
WHEN I open a filter
THEN I see the options are sorted by natural sort

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
@salabh-aot It would be good to have then naturally sorted from the api itself. The postgres doesn't allow that by default though we can try some custom functions to have this done. Lets discuss

**Comment by dinesh-aot** [comment]
Here are the list of entities to be sorted in different places of epictrack
 - [x]  WorkForm - Responsible Ministry - Sort Order Column
 - [x]  WorkForm - Responsible EPD - Natural Sort
 - [x]  WorkForm - WorkLead - Natural Sort
 - [x]  WorkForm - Decision Maker - Natural Sort
 - [x]  ProponentForm - Relationship Holder - Natural Sort
 - [x]  ProjectForm - Proponents - Natural Sort

**Comment by Connor1892** [comment]
we wanted the default for the filters to be natural sort with only a few exceptions. can it be build into the common component?

here are a few places we found wrongly ordered things:

insights:
- [x] lead - Natural
- [x] officer analyst - Natural
- [x] project - Natural
- [x] current phase - SortOrder of phase_codes table
- [x] other ministry (sort Order)
- [x] nations - Natural
- [x] proponents - Natural
- [x] subtype - Sort Order
- [ ] 

My Workplans
- [x] worktype (sort order)

**Comment by maria-kuzmenko** [comment]
@djnunez-aot , @dinesh-aot 

sorting for Lead appears with duplication (too many Amy Avila). We can't do sorting by Analyst, cause of the non-existance of this column haha

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm94QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae3e56efed128d080f62a07b31df76df430418b4/Screen%20Shot%202024-06-03%20at%201.50.57%20PM.png" alt="Screen Shot 2024-06-03 at 1.50.57 PM.png" />
