### ISSUE TITLE
Existing works work phase has changed due to the change in the phase name

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1877]
**Describe the bug**
Phase name 'EAC Intake' phase name changed to 'Pre-Early Engagement'. In the backend it actually deactivated the 'EAC Intake' and created a new phase called 'Pre-Early Engagement'. Existing work phases are now assigned to a deactivated phase_id. This needs to be updated using migration.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by carlygreenehill** [comment]
![image](https://github.com/bcgov/EPIC.track/assets/101662408/f24525c3-4044-4dbd-a7dd-4d2ae064bfa5)

Looking good!
