### ISSUE TITLE
Work & Project modals for viewers

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1885]
**As a** viewer

**I want** to be able to open the Work modal on All works, and the Project modal in list management: projects

**so that** I can see information about those entities without navigating to a separate page

### Scenario 1: 

GIVEN I am a viewer
WHEN I navigate to the All works Page
THEN I see the name of each work is blue and clickable

### Scenario 2:

GIVEN I am a viewer
WHEN I open the work modal for a given work
THEN I see both the fields and the save button are all disabled

### Scenario 3: 

GIVEN I am a viewer
WHEN I navigate to the List Management:Projects Page
THEN I see the name of each project is blue and clickable

### Scenario 4:

GIVEN I am a viewer
WHEN I open the project modal for a given project
THEN I see both the fields and the save button are all disabled

**Comment by dinesh-aot** [comment]
@Connor1892  The initial plan is to have the titles of all grids grayed out for viewers. So we are changing that behavior intentionally.right?
Plus, are we limiting this change to only works and projects or all the other lists in the application?

**Comment by Connor1892** [comment]
I believe it is just for work and project.
they should be able to open these modals but not change anything on them
