### ISSUE TITLE
Help Page Links

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1887]
---
need to have links to the CMS help pages on some modals to help staff new to the system fill out the fields.

---

**As a** User

**I want** to be able to get and easy access to contextual help pages

**so that** I can get help if needed with the system

### Scenario 1: 

GIVEN Any Application tab is open
WHEN Look in the right bottom corner
THEN I see a floating help button

### Screenshot 1
<img width="1292" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzN0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8fc1b895c8abfcd805d4306b4d2cf60d9af99a09/Screen%20Shot%202024-03-18%20at%204.07.34%20PM.png" alt="Screen Shot 2024-03-18 at 4.07.34 PM.png" />

### Scenario 2: 

GIVEN Scenario 1
WHEN I click on the button
THEN I see the menu option 'Support Center'

### Screenshot 2
<img width="1291" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0h1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8527f3ab5260a06abcdd2b597982a84c0f2773bd/Screen%20Shot%202024-03-18%20at%204.35.16%20PM.png" alt="Screen Shot 2024-03-18 at 4.35.16 PM.png" />

### Scenario 3: 

Jad note: I broke this off to another ticket: https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/2063
GIVEN Scenario 2
WHEN I click on 'Support Center' menu
THEN I help page with the content pertains this page/tab will open in another tab

**Comment by carlygreenehill** [comment]
@maria-kuzmenko --- here is the help card, welcoming your designs <3

**Comment by maria-kuzmenko** [comment]
link to prototype - https://www.figma.com/file/XcYynwH7xrO2P30uqewaLS/For-Development?type=design&node-id=70-854&mode=design

**Comment by Connor1892** [comment]
@maria-kuzmenko @jadmsaadaot should this be in product backlog? or is there something else we need to do to it before it's ready?

**Comment by jadmnsaad** [comment]
@maria-kuzmenko @Connor1892 let's please breakoff Scenario 3 to a separate ticket

**Comment by dinesh-aot** [comment]
@Connor1892  @maria-kuzmenko The worktype level help page navigation doesn't work with this ticket. Jad will create another ticket for that as It is getting more complex. You will be able to see the help pages per url navigations and tab switches with this ticket.
