### ISSUE TITLE
Issues tab - text overflowing panel

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1888]
**Describe the bug**
long strings are overflowing the panel

**To Reproduce**
1. Go to issues tab
2. Put extra long strings in the issues update
3. Save the update

**Expected behavior**
text should truncate when it overflows the panel

**Screenshots**
<img width="1510" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzZPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--627e585e3bdf1a7d301ba3a430405ac9015da6fd/Screen%20Shot%202024-02-26%20at%201.58.12%20PM.png" alt="Screen Shot 2024-02-26 at 1.58.12 PM.png" />

**Additional context**

**Comment by dinesh-aot** [comment]
@maria-kuzmenko  any update on this?

**Comment by maria-kuzmenko** [comment]
@dinesh-aot

yes, but this happens only in DEV env. See screenshots below for your reference.

DEV
![Screen Shot 2024-02-28 at 1 08 59 PM](https://github.com/bcgov/EPIC.track/assets/122938967/f3d17fc0-47d8-46f5-a358-c22042ba5673)

TEST
![Screen Shot 2024-02-28 at 1 09 05 PM](https://github.com/bcgov/EPIC.track/assets/122938967/9f7610ad-5a67-4174-acbd-f74dc4d89bcb)

**Comment by carlygreenehill** [comment]
@maria-kuzmenko  was right!
