### ISSUE TITLE
Insights - API - Works Partners

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1900]
**Overview**
For more info: [https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/1853](url)
Two endpoints required
- /insights/works?group_by=ministry
- /insights/works?group_by=federal_involvement

**Comment by salabh-aot** [comment]
@dinesh-aot   the links are not working
