### ISSUE TITLE
Mork Modal - Work name reset

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1904]
**Describe the bug**
when I opened the modal of an existing work, and change the decision maker, the name resets to the default pre-set.

**To Reproduce**
1. Go to any amendment work modal which has had it's title changed
2. Click on decision maker and change it
3. Scroll up to title

**Expected behavior**
the title should not be effected by changes to other fields

**Screenshots**

**Additional context**

**Comment by jadmnsaad** [comment]
@Connor1892 I tried this multiple times in dev and I really couldn't reproduce the issue. Could you please try again and if it's still happening let's meet on it?

**Comment by Connor1892** [comment]
@jadmsaadaot 
the last of the 29694 works in dev, when you open the modal the title field is the default, not the currently existing title. so saving it replaces the title.

**Comment by Connor1892** [comment]
Jad is a hero
