### ISSUE TITLE
Saving Filters

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1907]
---

We want filters to be remembered if you leave then return to a page

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
@Connor1892  I hope this is in a work plan page that you are referring. Cz we have filters in all the grids. 
Should we save it in the browser level or user level. 
If we save it in the browser level, the user keep seeing this filters as long as they are using the same machine and same browser - Just front end changes are required
If it is in the user level, they keep seeing it from where ever they login(no matter what computer or what browser) - this needs database level changes and api development to create/retrieve the filter as they move between pages

**Comment by Connor1892** [comment]
Browser level pls. user level stuff won't be happening until EPIC.centre.

we need it for the My Workplans page as well as for workplan pages.
