### ISSUE TITLE
Clear all filters

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1908]
**As a** User

**I want** to be able to reset all my filters to default

**so that** I can start from the beginning

### Scenario 1: 

GIVEN My Workplan page is open
WHEN I applied any filter except for the default ones
THEN I see 'Reset to Default' text button

### Screenshot #1
<img width="1053" alt="Screen Shot 2024-03-07 at 1 00 36 PM" src="https://github.com/bcgov/EPIC.track/assets/122938967/7d0b39f4-b783-4b9e-a79f-0fe541bf3565">

### Scenario 2:
GIVEN My Workplan page is open and multiple filters are applied
WHEN I click on 'Reset to Default' text button
THEN All filters are set up to default 
THEN 'Reset to Default' text button disappears

### Screenshot #2
<img width="1002" alt="Screen Shot 2024-03-07 at 1 04 29 PM" src="https://github.com/bcgov/EPIC.track/assets/122938967/421d62e1-b5cf-4c10-a552-86cb46d8ff8a">

**Comment by jadmnsaad** [comment]
Could you add some description to this please @Connor1892

**Comment by Connor1892** [comment]
@maria-kuzmenko we talked about functionality, but I don't know how you want the button positioned.
Pls, remove the UX tag when you've updated this!

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot, @Connor1892 uploaded screenshots and added scenarios
