### ISSUE TITLE
My Workplans - Title Truncation

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1919]
**Describe the bug**
when the screen size changes, everything on the work card gets truncated except for the title

**To Reproduce**
1. Go to my workplans
2. shrink the browser window horizontally
3. look at the title field

**Expected behavior**
the title should truncate nicely like the other fields

**Screenshots**

**Additional context**

**Comment by Connor1892** [comment]
@maria-kuzmenko

**Comment by maria-kuzmenko** [comment]
@djnunez-aot, the title should truncated but there should not be that much of white space. Can we set up fixed width between the title and the 'in progress' to 16px, so truncation will start when it reaches those margins 

<img width="1404" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGZ0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c77a0c35568fa1c73c9d8764f527e29ea51c2a3/Screen%20Shot%202024-03-18%20at%202.04.30%20PM.png" alt="Screen Shot 2024-03-18 at 2.04.30 PM.png" />
