### ISSUE TITLE
Work form Dialog gets closed if there are error when submitting the form

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1920]
**Describe the bug**
The work form gets closed even when there are error occured in the back end.

**To Reproduce**
Steps to reproduce the behavior
1. Set up an error situation in the back end in local environment
2. Create a work and watch the behavior

**Expected behavior**
The form should stay there so that user can correct something and resubmit

**Screenshots**

**Additional context**

**Comment by carlygreenehill** [comment]
@dinesh-aot  is it safe for me to close this one? =)
