### ISSUE TITLE
ChangePhaseEndEvent - Not working(Transition from 2002 Act)

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1922]
**Overview**
"Project transitioning from EA Act 2002" event is not working due to the bug in the action called "ChangePhaseEndEvent" action.

CARLY NOTE:
- the proponent will always land in proponent time. the Transition Order states the next phase they'll "start in" as they transfer into 2018... but chances are they don't have all the right documents to get them into the next step, so they step into proponent time in order to prep for the next stage.

**Comment by Connor1892** [comment]
![image](https://github.com/bcgov/EPIC.track/assets/126211473/24e89a32-8df9-4e99-a469-280bcbf1339f)

after the transition the next phase jumps 2 years.
then later phases go back in time to 2016

**Comment by carlygreenehill** [comment]
@dinesh-aot  is there any way I can test this?

**Comment by dinesh-aot** [comment]
**Steps to test**
- Create a new work - assessment type
- In the first phase put actual for the first event
- Add a new milestone for the transition from 2002 act and put anticipated
- Open the newly added transition milestone and put actual
- Choose the decision make and decision
- Based on the decision you have chosen, a few phases would be deactivated and the next active phase should have the next date as that of the newly added transition 2002 milestone
- If you want to know what phases are deactivated, you should check the event template and action tab
- @carlygreenehill Hope this helps a little

**Comment by carlygreenehill** [comment]
@dinesh-aot + @salabh-aot

Tested on "Angus - Assessment - Carly Test"  ... I chose "transition to Process Planning" on date Jan 4 2023... and I think it worked! Early Engagement and readiness have disappeared, and the start date for Process Planning is Feb 02, 2023.
