### ISSUE TITLE
Work Timeline - Default Sort

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1927]
**As a** user

**I want** the works sorted by start date

**so that** I can always have works in similar timelines stacked together for easier comparison

### Scenario 1: 

GIVEN I am logged in to EPIC.track
WHEN I navigate to the Project Timeline page
THEN I see the works sorted by:
- End Date

**Comment by Connor1892** [comment]
We have it by Start Date because I know we're capturing this on the Work Modal.

End Date would be better if it's not hard to get.

**Comment by jadmnsaad** [comment]
@Connor1892 @maria-kuzmenko any default sorting applied to the timeline view will be also applied to the cards view. Are we okay with that?

**Comment by jadmnsaad** [comment]
@Connor1892 can't sort by end date boss, not easy to  get. I sorted by start_date in descending order

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , @Connor1892 

last update from Geoff per discussion: default sort is **alphabetical**

**Comment by Connor1892** [comment]
@jadmsaadaot @maria-kuzmenko @dinesh-aot 
After Talking with Maria and Dinesh we are going to try start date for default sort.
Alphabetical provides no value so we want to try start date first.

**Comment by Connor1892** [comment]
putting earliest at the bottom is a smart move! keeps the shortest and newest at the top. 😁
