### ISSUE TITLE
Referral Schedule - Staleness Chips Logic

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1932]
**Describe the bug**
any out of date (Red) chip says needs status instead of the last status date.

**To Reproduce**

**Expected behavior**
The Red Chip should still show the last status date (if there is one) on the work

**Screenshots**

**Additional context**

**Comment by dinesh-aot** [comment]
@salabh-aot Even if the work has status updated in a very older date, it still shows "Needs Status" in the chip.

**Comment by Connor1892** [comment]
@dinesh-aot 
do we need to change this logic to check against report date instead of today's date?
If we're looking at actually giving them the correct information for whatever date they choose, then we need to fix the referral schedule in other ways as well. (it shows a yellow status from the 29th when I call a report from the 30th while the real date is the 7th)

**Comment by dinesh-aot** [comment]
**Help to test**
You can adjust the report_date to see the staleness changes. Previously it was based on today's date and now we have changed the staleness based on the report_date. So if you request RF based on an older date, we will check the last status updated date and older report_date to show the staleness.

**Comment by Connor1892** [comment]
the colours are correct, and change correctly for each date chosen.

HOWEVER!!!
the colours are updating on date select instead of on submit.
this can lead to false view of a report on web view.
