### ISSUE TITLE
30-60-90 - Status location

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1933]
**Describe the bug**
the work status is showing under the Work short description instead of under the status tab.
Also, the Decision information tab is empty.

**To Reproduce**

**Expected behavior**
the status should be shown under the status tab,
and the decision information tab should display the facts about why this work is on the report.

**Screenshots**

**Additional context**

**Comment by salabh-aot** [comment]
>  Also, the Decision information tab is empty.

@dinesh-aot  @Connor1892 right now we are taking the `notes` on decision events to show under `Decision information` is this correct?
NB :- There was a bug which caused `work status & decision information` to display under `Work Short Description`, I've created a PR with fixes for it. Can merge it once we get confirmation on the above point.

**Comment by Connor1892** [comment]
confirming this is fixed. @dinesh-aot what do you think about Decision Information?
