### ISSUE TITLE
Assessment Worktype - Federal Involvement Decision Milestone

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1935]
**Describe the bug**
2 of the 3 options appear to be identical, both setting FederalInvolvement to "None". The first one gave an error. the 3rd one worked properly.

**To Reproduce**

**Expected behavior**
we need to change the options to say what the outcome column says instead of the action column. (on the excel) 

**Screenshots**

**Additional context**

**Comment by dinesh-aot** [comment]
Would this ticket become obsolete if are creating new assessment template @Connor1892 @EAO-App-Admin @maria-kuzmenko

**Comment by dinesh-aot** [comment]
Closing this ticket as the new templates will deal with these issues
