### ISSUE TITLE
Work Page - Start Date

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1938]
---

changing the start date in the workplan should update the start date field in the work modal.

- Start Date on "new" WORK, (code)
- 2nd Start Date on Pre-EA(intake) PHASE START EVENT actual, (code)
- 3rd Start Date on EE START PAHSE EVENT actual (action)

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
@Connor1892 By changing the start date in work plan, did you mean changing the start date of the first event in the first phase

**Comment by Connor1892** [comment]
@dinesh-aot @EAO-App-Admin 
the 3rd option is updating based on Day 0 in Pre-EA instead of Day 1 in EE

**Comment by dinesh-aot** [comment]
@Connor1892  If you check the assessment template, you will see it is configured to update the work start date based on Day Zero in Pre-EA. Please check with Geoff if this is intentional or not
