### ISSUE TITLE
Special History - restricted dates

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1943]
**Describe the bug**
A new EPD or Team Lead cannot be added if the ‘From’ date precedes the old EPD or Team Lead’s ‘From’ date.
 
Go to ‘All Works’
Click on any ‘Work’
Scroll down to ‘Responsible EPD’ or ‘Team Lead’
Click the ‘unlock icon’
Click ‘+New Entry’
Click a ‘From’ date that is precedes the old EPD or Team Lead
Click the ‘green checkmark’
No change is made
See error
 
Expected behaviour
When a green checkmark is clicked to update a ‘From’ date on a new EPD or Team Lead (TL) that precedes the old EPD or TL, the old EPD or TL’s ‘To’ date updates from ‘Today’ to one day before the new EPD or TL’s ‘From’ date.

**Comment by carlygreenehill** [comment]
Well done!
