### ISSUE TITLE
Work Timeline - Worktype Colours

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1944]
---
all pre-EA worktypes AKA Project Notification, CEAO's Designation, Exemption Order, Minister's Designation should be of the same colour.

The correct colour right now has only Minister's Designation. Can we make Project Notification same one?

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by carlygreenehill** [comment]
@maria-kuzmenko  Dinesh has questions for you!

**Comment by dinesh-aot** [comment]
Verified it and all the latest phases having correct colors.
