### ISSUE TITLE
Extension Milestone type not working

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1959]
**Overview**
Example work in production which didn't work 
https://system.eao.gov.bc.ca/work-plan?work_id=15

Test the extension scenarios

**Comment by dinesh-aot** [comment]
**Help to test**
- Create an assessment work
- Go pass the pre-ea phase
- Add extension event in the Early Engagement and see if it works as expected
- **let me know, if you are not sure how extension works**

**Comment by Connor1892** [comment]
after adding a 30 day extension, the Summary of engagement would not let us move the anticipated to august 1st or 2nd.

![image](https://github.com/bcgov/EPIC.track/assets/126211473/9a3e2106-0d6b-4bca-ae4c-bb746648d17b)
