### ISSUE TITLE
Additional Params - Project Notification - Event Templates

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1967]
**Overview**
Add additional params to the latest Project Notification
Upload it in the local using the event template import API
Create work
Check work plan
Complete one entire workplan
Check maximum possible actions and decisions

**Comment by dinesh-aot** [comment]
**Help to test**
- Create a new Project Notification work
- Compare it with the latest project notification template
- The latest project template can be found in our github report, go to epictrack-api/api/src/template/event_templates/project_notification/002_Project_notification.xlsx
- **Let me know if you need me to find the file**

**Comment by Connor1892** [comment]
last 2 decisions failed from paramenters
