### ISSUE TITLE
Additional Params - Assessment - Event Templates

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1968]
**Overview**
Add additional params to the latest Assessment
Upload it in the local using the event template import API
Create work
Check work plan
Complete one entire workplan
Check maximum possible actions and decisions

**Comment by carlygreenehill** [comment]
FOR QA CARLY:

- Get the template from Dinesh (download)
- Create an Assessment in TEST
- See if you see the same set of mandatory milestones
- NEXT LEVEL: See if the outputs are the same as the excel
