### ISSUE TITLE
New milestone visibility called "SUGGESTED"

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1981]
**Overview**
New visibility for milestone called "SUGGESTED" to be added. The new "SUGGESTED" has the following properties
- It should be created when a new work plan is generated
- It should be possible to remove the suggested as long as no actual date is entered

**Comment by carlygreenehill** [comment]
@dinesh-aot   can you upload the list of suggested milestones so i can take a peek in test?
