### ISSUE TITLE
Prevent Issues from being back dated after approval

### ISSUE THREAD

**Issue by djnunez-aot** [bcgov/EPIC-FLOW#2005]
**Describe the bug**
Once an Issue/Status has been approved, no UPDATE to this Status/Issue can be "back-dated" and dates before the latest APPROVED UPDATE are greyed out

**To Reproduce**

1. Go to Issues Tab
2. Find a current Issue
3. Try to add an update, make the update IN THE PAST
4. No save happens, no error message either

**Expected behavior**

We want to see an error message because UPDATES to an Issue (eg. the Cupcake Issue) should not happen in the past.

**Screenshots**

**Additional context**

<img width="996" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3J5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b89a8aa66c891e57562c1bce5a6c902b7777d1e/image.png" alt="image.png" />

connected to #1729

**Comment by jadmnsaad** [comment]
Solved here https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/1729
