### ISSUE TITLE
Remove extra loader in resource forecast

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#2009]
**Overview**
When you "Submit" or "Download" in the resource forecast, there will be two spinner showing while the data is loading. Currently show a loader for all the put, post, delete requests. In resource forecast there is an additional spinner loading for the "submit" and "download"(both are POSTs). 

It should be possible to remove it at the table level in the common table component.

**Comment by djnunez-aot** [comment]
Loader is removed but is not working for regular fetching
