### ISSUE TITLE
Insights - Work Dashboard - Staff - Count Bug

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/EPIC-FLOW#2016]
**Describe the bug**
From the Staff Insights page, I can see counts for Work by Lead and Work by Staff. However, when I go to filter by Lead or Officer/Analyst in the grid below, the # of results come back differently. 

Related to #1852

This is likely related to Scenario 3 & 4 - let's have a chat at DAILY SCRUM on Thurs March 21 

**To Reproduce**

1. Go to Insights Tab 
2. Click on the Staff page
3. Scroll down to the Grid to filter by Officer/Analyst or Team Lead
4. See counts differ between Grid and Graphs

**Expected behavior**
Same counts and no Team Leads counted toward Officer/Analyst and vice versa

**Screenshots**

**Additional context**

---

SCENARIO 2 - Grid is pulling inactive works in GENERAL

**Comment by Connor1892** [comment]
when searching for jad in the officer/ analyst column, it shows 0 results. but the graphic claims he's on 3 works. when you check the table he's in there with other staff.
the filter should pick up when he's in the cell, not just when it's ONLY him in the cell.

**Comment by Connor1892** [comment]
also we cannot confirm the staff showing are correct, because the names of the works are all duplicates. not sure which card introduced this.
