### ISSUE TITLE
Fix Insights - Work Lists should always be Active

### ISSUE THREAD

**Issue by jadmnsaad** [bcgov/EPIC-FLOW#2017]
Right now the Work lists in all tabs are including inactive works. It should only be active

**Comment by Connor1892** [comment]
if we don't have the ability to show inactive works, then we should remove the column.

I think we should give them the ability to incorporate inactive works, but just have the default be only active.

**Comment by Connor1892** [comment]
for V1 we will go with the removing the status column.
