### ISSUE TITLE
Side Menu - Collapsable

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2057]
---

Arrow on top of page to collapse
collapsed menu only shows Icons.
clicking anywhere blue on the menu expands the menu
clicking on any entry that has a dropdown expands the menu and opens the dropdown
clicking on any entry that does not have a dropdown keeps the menu collapsed and navigates you.

---

**As a** User

**I want** collapse main menu

**so that** I have more space in the grid

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 
<img width="606" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0llQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f6406b9df108171cc72298c12580ccc9fdf255d/Screen%20Shot%202024-03-28%20at%202.27.27%20PM.png" alt="Screen Shot 2024-03-28 at 2.27.27 PM.png" />

**Comment by maria-kuzmenko** [comment]
link to the design system - https://www.figma.com/file/dwlYoKngyXkuBoEGiEld1h/Design-System?type=design&node-id=547-334&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/2057?planning-poker) with Zenhub @dinesh-aot @djnunez-aot @jadmsaadaot
