### ISSUE TITLE
Work Timeline - Hover Information

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2058]
**As a** user

**I want** to see more information when hovering over each phase

**so that** I can be more informed

### Scenario 1: 

GIVEN I am on the Work Timeline
WHEN I hover over a COMPLETED phase
THEN I see the following:
- Work name
- Phase name
- Phase start date
- Phase end date
- Days

### Screenshot 1:
<img width="1208" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXE2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ca4faac2ca2817d0ce18a9f68616255715b3b2b/Screen%20Shot%202024-05-06%20at%203.28.30%20PM.png" alt="Screen Shot 2024-05-06 at 3.28.30 PM.png" />

### Scenario 2:

GIVEN I am on the Work Timeline
WHEN I hover over a CURRENT phase
THEN I see the following:
- Work name
- Phase name
- Phase start date
- Phase Anticipated end date
- Days
- Current Milestone
- Next Milestone

### Screenshot 2:
<img width="1219" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTI2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a8b14e7efe6bfd36eb03a4f0de888f74b4ef1ef/Screen%20Shot%202024-05-06%20at%203.29.38%20PM.png" alt="Screen Shot 2024-05-06 at 3.29.38 PM.png" />

### Scenario 3: 

GIVEN I am on the Work Timeline
WHEN I hover over a FUTURE phase
THEN I see the following:
- Work name
- Phase name
- Phase anticipated start date
- Phase anticipated end date
- Days

### Screenshot 3:
<img width="1257" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNis2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65d020be5d780442c940da58172417fede464983/Screen%20Shot%202024-05-06%20at%203.42.15%20PM.png" alt="Screen Shot 2024-05-06 at 3.42.15 PM.png" />

**Comment by jadmnsaad** [comment]
@Connor1892 @maria-kuzmenko description is still empty here, can we please add some?

**Comment by Connor1892** [comment]
@maria-kuzmenko ready for screenshots

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , @Connor1892 link to prototype - https://www.figma.com/file/GsrDa5tsU1xWj8MGPfylCs/Development-(Insights)?type=design&node-id=534-389&mode=design

**Comment by jadmnsaad** [comment]
@maria-kuzmenko @Connor1892  For the sake of this ticket I have created a one tooltip with common information from the design.
<img width="487" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1B4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--287691087c49ef05f02353b01adb1c2c1f37fce6/image.png" alt="image.png" />


Let's create a new ticket to add different information depending on the phase.

**Comment by jadmnsaad** [comment]
I created this https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/2257 to further customize the tooltip according to the phase
