### ISSUE TITLE
Special History - Size problems

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2059]
**Describe the bug**
the Special history dropdown in the project modal is cut to half the modal size. this makes it very hard to use

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Connor1892** [comment]
on Edit Project Modal, if I open both both Name and Proponent, I can type and change the name and lock it again when locking the proponent again.

opening the Name pushes the proponent down to the next line.

we should not be able to have both special histories at the same time.

**Comment by djnunez-aot** [comment]
@Connor1892  the name pushing down the proponent is something i discussed with Jad, it would take a very large redesign of the component might not be worth our efforts. Working on the rest of the changes.

**Comment by Connor1892** [comment]
all fields should be disabled when special history is open.
see Edit Work modal as example.
