### ISSUE TITLE
Help Page Links - Connect floating help button to help pages

### ISSUE THREAD

**Issue by jadmnsaad** [bcgov/EPIC-FLOW#2063]
---
need to have links to the CMS help pages on some modals to help staff new to the system fill out the fields.

---

**As a** User

**I want** to be able to get and easy access to contextual help pages

**so that** I can get help if needed with the system

### Scenario: 

GIVEN floating help button was clicked on
WHEN I click on 'Support Center' menu
THEN I help page with the content pertains this page/tab will open in another tab

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/2063?planning-poker) with Zenhub @dinesh-aot @djnunez-aot @jadmsaadaot
