### ISSUE TITLE
Decision Milestones - Prepopulated Decision Dropdowns if only 1 option

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2084]
---

after selecting an actual date
when choosing a decision maker
the decision field will prepopulate ONLY IF there is 1 option available

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
**Tips for development**
Create a sample assessment
In Workplan -> Add Milestone -> Project Withdrawal
When you put the actual date, you will see a decision dropdown with only one value
In such cases, preselect that value instead of wanting the user to select it
