### ISSUE TITLE
Help Page - connect to help page according to work type

### ISSUE THREAD

**Issue by jadmnsaad** [bcgov/EPIC-FLOW#2098]
---
Need to navigate to help page according to work type

---

**As a** User

**I want** to be able to get and easy access to contextual help pages

**so that** I can get help if needed with the system

### Scenario 1: 

GIVEN I am on the workplan tab in
WHEN I click on the help button and click on support center
THEN I should be navigated to the help page that corresponds to the work type

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot redirected to some other page that doesn't work 

https://intranet.gov.bc.ca/eao/digital-services/support-for-epic-system/support-for-epic-track/milestone-definitions/project-notification

<img width="1663" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDFnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4d22ce288ef5e4aa0ac950a93d2ed53f129df69/Screen%20Shot%202024-04-15%20at%209.50.55%20AM.png" alt="Screen Shot 2024-04-15 at 9.50.55 AM.png" />

**Comment by jadmnsaad** [comment]
@maria-kuzmenko this is fixed
