### ISSUE TITLE
confetti on anticipated

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2137]
**Describe the bug**
the confetti is appearing on the anticipated date save

**To Reproduce**

**Expected behavior**
only happen on actual date save!

**Screenshots**

**Additional context**

**Comment by djnunez-aot** [comment]
@dinesh-aot  @Connor1892  is this still happening with the confetti fix?

**Comment by dinesh-aot** [comment]
@maria-kuzmenko I think this issue doesn't exist now

**Comment by maria-kuzmenko** [comment]
@dinesh-aot correct
