### ISSUE TITLE
Team Tab - Co-Lead

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2140]
---

need to create a new entry for Co-Lead.

give Work edit access to the EPD & Lead in the Team Information section.
they are not visible in the grid, but still have edit permissions.

remove Jad's backend checks
disable the auto insert of team lead at work creation

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
when changing the EPD and Lead in Special history, the old Lead and EPD disappear from the grid.
are they real? in which case they should now show as inactive on the grid.
if they are fake entries put there just in the display, then they can remain hidden in the special history.

**Comment by jadmnsaad** [comment]
@Connor1892 whether a change or a new entry is added the old team lead/ epd should show inactive in the grid. I just tested that and confirmed this behavior. I couldn't reproduce a case where a change happens and the old entries disappear. Can we meet on this and test it together?

I've tested it in dev. Maybe you tested this in Test and the changes haven't been pushed there?

**Comment by Connor1892** [comment]
needs to refresh grid when going to team tab

**Comment by Connor1892** [comment]
team tab grid is not refreshing in test.

**Comment by jadmnsaad** [comment]
@Connor1892 changes not pushed to Test yet, can we test and confirm in dev?
