### ISSUE TITLE
Workplan - Days left bug

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2142]
**Describe the bug**
the days are displaying wrong. we got a negative 19 days and a 0 days.

**To Reproduce**

**Expected behavior**
minimum days should be 1.

**Screenshots**
Test Env: work_id=99

**Additional context**

**Comment by Connor1892** [comment]
@dinesh-aot 
still getting 0 days. did Geoff change the requirement from the 1 day minimum?

**Comment by dinesh-aot** [comment]
@Connor1892 Yes, it is decided to have zero if a phase start and finish at the same day. Cz EAO consider one day if it is a full day.
