### ISSUE TITLE
Project Insights shows INACTIVE projects

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#2157]
**Overview**
The "Show More" in Projects within the "Insights" shows INACTIVE projects. The insights supposed to have only active projects. 

**Expected**
Only active projects should be shown in the insights

**Actual**
Shows all active/inactive in the project insights

**Comment by Connor1892** [comment]
it needed a refresh to show the fix. why is the insights page not reloading on entry?

**Comment by jadmnsaad** [comment]
@Connor1892 because the results might have been cached. The cache lasts for 5 minutes
