### ISSUE TITLE
Workplan Page - ordering of same day task events

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2164]
---

we need to give them a way to reorder same day task events.

We want to replace the ordering in the Phase Accordions from creation time to natural sort.
With always task before milestone on same day

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by jadmnsaad** [comment]
can we make the description clearer? Is there a wireframe for this? "we need to give them a way to reorder same day task events" how? what button do they click?

**Comment by jadmnsaad** [comment]
@Connor1892 @maria-kuzmenko I have a few questions in my prior comment, could you please add some clarity to this? We can maybe meet and discuss this
