### ISSUE TITLE
Current phase is not being set correctly when phases are deactivated and new phases are added

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#2171]
**Overview**
In certain milestones, based on the decision taken, a few of the anticipated phases might get deactivated and new phases will be added. In such scenarios, the added new phase could be the current phase. 
Failure in setting the newly added phase as the current phase causes issues in many places

1. The "Days/left" is showing incorrect in the phase accordion
2. The current phase will not be automatically opened up on loading the workplan
3. The data in the report preview in status and issues tabs will become incorrect
4. Eventually, the report taken will have incorrect phase mentioned
5. MyDashboard will also show false information about the current phase and upcoming milestone
6. 

**DevNote**
Create another method called "PostActions" and set the current phase always after actions are executed

**Comment by Connor1892** [comment]
on My Workplans it's showing correct milestone but the wrong date.
we closed the intake of Ministers designation (Ajax Mine - blah 2) and now the Card view is showing the first milestone of App review, but the date of the end milestone.
