### ISSUE TITLE
Work Staff - fix grid

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2176]
---
remove second EPD column
fix work name column

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
@djnunez-aot 
we need hover states for truncated text

**Comment by dinesh-aot** [comment]
@djnunez-aot  Can you move the work_title column to the first index in the grid

**Comment by Connor1892** [comment]
@djnunez-aot 
still looking for hoverstates on truncated test. (ie: officer/analyst, project, etc.)

**Comment by Connor1892** [comment]
@djnunez-aot 
can't test.
Work-staff page is not showing any results.
