### ISSUE TITLE
Milestone - Link to Created Works

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2179]
---

when a milestone creates a new work, the milestone should have a link to the new work that was created

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
@Connor1892 Let me know when you are testing this. I can help you to make sure the backend stores the link between the works
