### ISSUE TITLE
Insights - show more fixes

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2189]
---

- [x] Change Lead Column to Lead/ Co-lead (single column if possible
- [x] make the graphic for staff match officer analyst colunm
- [x] staff graphic should not include where staff are leads/ co-leads
- [x] Staff tab should have the work title as a link

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
#2016 prevents us from testing this

**Comment by Connor1892** [comment]
when opening the show more for staff we will see one work's title for all works: changing the team fixed it, then changing it back to CAIR made them all show as the second work instead of the first

**Comment by maria-kuzmenko** [comment]
<img width="1599" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0xHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60569ef6f90dfad8b621dca8e29c0fe9b858f122/Screen%20Shot%202024-05-08%20at%204.16.01%20PM.png" alt="Screen Shot 2024-05-08 at 4.16.01 PM.png" />

**Comment by Connor1892** [comment]
![image](https://github.com/bcgov/EPIC.track/assets/126211473/471e86a5-0acc-43fb-82f4-6e73642729c3)
