### ISSUE TITLE
My Tasks - menu item

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2198]
**As a** user

**I want** a place where all my tasks from all works are in one place

**so that** I can stay on top of my work

### Scenario 1: 

GIVEN I log into EPIC.track
WHEN I reach the landing page (my workplans)
THEN I see the My Tasks menu item under the My Workplans menu item

### Screenshot 1
<img width="1300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMis1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6db7a7f9b87197e12c6a3b7cb1a49510d3446d8/Screen%20Shot%202024-05-06%20at%2010.25.46%20AM.png" alt="Screen Shot 2024-05-06 at 10.25.46 AM.png" />

### Scenario 2:
GIVEN I log into EPIC.track
WHEN I click on the My Tasks menu item
THEN I see the My Tasks Page with Task Grid

### Screenshot 2
<img width="1298" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0M1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d31d50fd02954ca096aef2b45f7847a906c75c1e/Screen%20Shot%202024-05-06%20at%2010.26.15%20AM.png" alt="Screen Shot 2024-05-06 at 10.26.15 AM.png" />

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
link to the prototype - https://www.figma.com/file/XcYynwH7xrO2P30uqewaLS/For-Development?type=design&node-id=109-983&mode=design

**Comment by Connor1892** [comment]
Reports should still be bundled with insights.
My tasks is correct, but all works should be on it's own
