### ISSUE TITLE
My Tasks - Grid

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2200]
**As a** user

**I want** a place where all my tasks from all works are in one place

**so that** I can stay on top of my work

### Scenario 1: 

GIVEN I am on the My Tasks Page
WHEN I look at the grid
THEN I see the following:
- Task (active link to bring up task modal)
- Start Date (default sorted earliest to latest)
- End date 
- Progress (default filter to show only 'In Progress' and 'Not Started')
- Assigned (default filter to only me)
- Notes 
- Work (only works where I am active on team tab are showing and available to filter by)

### Screenshot 1
<img width="1298" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzY1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbea805cbbe456e000f20d3ac68d320187888275/Screen%20Shot%202024-05-06%20at%2010.26.15%20AM.png" alt="Screen Shot 2024-05-06 at 10.26.15 AM.png" />

### Scenario 2:

GIVEN I am on the My Tasks page
WHEN I change the filter on the Assigned column
THEN I see all tasks assigned to everyone on the selected works

### Screenshot #2
<img width="1299" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEM1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6135f0dc19b9ba1f8523f79bb1536575e9b6a5af/Screen%20Shot%202024-05-06%20at%2010.40.37%20AM.png" alt="Screen Shot 2024-05-06 at 10.40.37 AM.png" />

**Comment by maria-kuzmenko** [comment]
link to prototype - https://www.figma.com/file/XcYynwH7xrO2P30uqewaLS/For-Development?type=design&node-id=128-2835&mode=design

**Comment by Connor1892** [comment]
default sort should be by start date only.
