### ISSUE TITLE
My Tasks - Task Modals

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2201]
**As a** user

**I want** a place where all my tasks from all works are in one place

**so that** I can stay on top of my work

### Scenario 1: 

GIVEN I am on the My Tasks page
WHEN I click on the active task title
THEN I see the Task modal for that task

### Screenshot 1
<img width="1297" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGU1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e418cd4357f4cdade89d3d9693b2c1825190975e/Screen%20Shot%202024-05-06%20at%2010.46.49%20AM.png" alt="Screen Shot 2024-05-06 at 10.46.49 AM.png" />

### Scenario 2:

GIVEN I have a Task Modal open
WHEN I make edits to the fields
THEN the only options are the ones that would show if I had opened the modal from that work's workplan

### Scenario 3:

GIVEN I have a Task Modal open
WHEN I make edits to the fields
THEN the edits I save will alter the task in the workplan

**Comment by maria-kuzmenko** [comment]
link to prototype - https://www.figma.com/file/XcYynwH7xrO2P30uqewaLS/For-Development?type=design&node-id=128-1031&mode=design

**Comment by maria-kuzmenko** [comment]
@djnunez-aot 
can you, please, fix the size of the modal - same as we use when you open task modal in the workplan grid?
See compared screenshots for the reference. 

Task Modal in Workplan grid
<img width="498" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOElPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a1d467eedb218faf2552cb94e42c8417fe1d2db/Screen%20Shot%202024-05-24%20at%2010.16.10%20AM.png" alt="Screen Shot 2024-05-24 at 10.16.10 AM.png" />

Task Modal in Tasks
<img width="591" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE1PQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8fb6996bfc4a7648cd95b68e5ac06040d0af0d8/Screen%20Shot%202024-05-24%20at%2010.15.55%20AM.png" alt="Screen Shot 2024-05-24 at 10.15.55 AM.png" />
