### ISSUE TITLE
My Workplans - page is crashing on load

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2207]
**Describe the bug**
something with the lazyloading is crashing test.

**To Reproduce**
1. Go to my workplans
2. Scroll down
3. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jadmnsaad** [comment]
currentWorkPhaseInfo is being undefined and so doing currentWorkPhaseInfo.work_phase.name is throwing an error
