### ISSUE TITLE
First nation Modal - + Add Nation Ghost Text

### ISSUE THREAD

**Issue by ethanjorgensen** [bcgov/EPIC-FLOW#2245]
**Describe the bug**
Capitalization for +Add Nation modal First nations ghost text

**To Reproduce**
1. Go to 'First Nation' tab in a Work
2. Click on '+ Add Nation' button
3. Find 'Nation*' field
4. See 'Search for first nation' ghost text

**Expected behavior**
The text should show First nation, not first nation.

**Additional context**
_FOR FUTURE REFERENCE_
First Nation = ethnicity
First nation = entity

**Comment by MarkFeleaMotetGov** [comment]
@ethanjorgensen I did some research and I don't see anything mention capitalizing just "First" in "First nation". I think it would be correct to correct this to "First Nation" (both words capitalized).

I could be missing something, but just wanted to confirm before making the change.

**Comment by maria-kuzmenko** [comment]
@MarkFeleaMotetGov 
Should it be 'First nation' in both ghost text and alert?

@ethanjorgensen, is this correct?


<img width="563" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmNPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a7e1cc2bb1b4d501695b1568895c48edf08a25e/Screen%20Shot%202024-05-24%20at%2010.06.39%20AM.png" alt="Screen Shot 2024-05-24 at 10.06.39 AM.png" />

**Comment by MarkFeleaMotetGov** [comment]
99.99612% sure it's **F**irst **N**ation. I'll update the alert text to be capitalized too.
