### ISSUE TITLE
Event Modal - Comment Period fields locking

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2249]
**Describe the bug**
fields 'Number of Responses', 'Topic' for Milestone 'Comment Period'
fields 'Number of Attendees' for Milestones 'Virtual Information Session' and 'Open House' 
should not be locked once the Milestone has actual date.

**To Reproduce**
1. Go to Work https://epictrack-test.apps.gold.devops.gov.bc.ca/work-plan?work_id=13
2. Open Early Engagement Phase
3. Click on 'Comment Period' Milestone
4. Scroll down to 'Number of Responses' and 'Topic'
5. They both are greyed out

**Expected behavior**
Fields 'Number of Responses' and 'Topic' should not be greyed out in case users want to update this information

**Screenshots**
<img width="482" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK01QQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea828d6228ca0c687959ef2d7c15e83f28988d19/Screen%20Shot%202024-05-24%20at%204.04.39%20PM.png" alt="Screen Shot 2024-05-24 at 4.04.39 PM.png" />

**To Reproduce**
1. Go to Work https://epictrack-test.apps.gold.devops.gov.bc.ca/work-plan?work_id=13
2. Open Early Engagement Phase
3. Click on 'Virtual Informaton Session' and 'Open House' Milestone
4. Scroll down to 'Number of Attendees'
5. It is greyed out

**Expected behavior**
Field 'Number of Attendees' should not be greyed out in case users want to update this information

**Comment by jadmnsaad** [comment]
Description : ( @Connor1892

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot Updated

**Comment by maria-kuzmenko** [comment]
@Connor1892 interesting enough, I can see that days left for Topic, apparently, is not working hmhm.
It works when you type, but when you put actual, it locks and shows again 150/150 though Title is fine.
