### ISSUE TITLE
Work Timeline - Tooltip information based on phase

### ISSUE THREAD

**Issue by jadmnsaad** [bcgov/EPIC-FLOW#2257]
**As a** user

**I want** to see more information when hovering over each phase

**so that** I can be more informed

### Scenario 1: 

GIVEN I am on the Work Timeline
WHEN I hover over a COMPLETED phase
THEN I see the following:
- Work name
- Phase name
- Phase start date
- Phase end date
- Days

### Screenshot 1:
<img width="1208" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXE2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ca4faac2ca2817d0ce18a9f68616255715b3b2b/Screen%20Shot%202024-05-06%20at%203.28.30%20PM.png" alt="Screen Shot 2024-05-06 at 3.28.30 PM.png" />

### Scenario 2:

GIVEN I am on the Work Timeline
WHEN I hover over a CURRENT phase
THEN I see the following:
- Work name
- Phase name
- Phase start date
- Phase Anticipated end date
- Days
- Current Milestone
- Next Milestone

### Screenshot 2:
<img width="1219" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTI2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a8b14e7efe6bfd36eb03a4f0de888f74b4ef1ef/Screen%20Shot%202024-05-06%20at%203.29.38%20PM.png" alt="Screen Shot 2024-05-06 at 3.29.38 PM.png" />

### Scenario 3: 

GIVEN I am on the Work Timeline
WHEN I hover over a FUTURE phase
THEN I see the following:
- Work name
- Phase name
- Phase anticipated start date
- Phase anticipated end date
- Days

### Screenshot 3:
<img width="1257" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNis2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65d020be5d780442c940da58172417fede464983/Screen%20Shot%202024-05-06%20at%203.42.15%20PM.png" alt="Screen Shot 2024-05-06 at 3.42.15 PM.png" />

**Comment by jadmnsaad** [comment]
https://www.figma.com/file/GsrDa5tsU1xWj8MGPfylCs/Development-(Insights)?type=design&node-id=534-389&mode=design

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot hover state is amazing!

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , @dinesh-aot we have some discrepancy with the days here. Can we make it same thing everywhere or this is some day '0' calculation happening in place?

On the Grid it shows 28
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUFPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f948068181f4e0e9e076d111ef34f0dfdca2e2eb/Screen%20Shot%202024-05-24%20at%2010.29.27%20AM.png" alt="Screen Shot 2024-05-24 at 10.29.27 AM.png" />

and on the hover, it is +1 day
<img width="1321" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35b2c54c72013bf6476fd5cde9c274722823637e/Screen%20Shot%202024-05-24%20at%2010.30.03%20AM.png" alt="Screen Shot 2024-05-24 at 10.30.03 AM.png" />

**Comment by jadmnsaad** [comment]
@maria-kuzmenko how do you count the days? is jan 30 counted? is feb 27 counted?

**Comment by jadmnsaad** [comment]
@maria-kuzmenko also can we please open a new ticket for this if the ACs have been met? Once we agree on how we reflect the days even the taskbars might need to adjust and better handle that in something new
