### ISSUE TITLE
Work State - Inactive when Complete

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2267]
---

when the work state changes to:
- complete
- closed
- terminated
- withdrawn

then we need the Work status to automatically become inactive.

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
@Connor1892 Are you talking about workplan status tab? if so, should we keep the issues open if the work is in one of the above mentioned states?
By deactive, did you mean to to let the user see the content by navigating the status tab and not letting them edit, approve or add new statuses?

**Comment by Connor1892** [comment]
@dinesh-aot like in the All Works grid!

**Comment by Connor1892** [comment]
we also need to remove the active check from the My Workplans page. if all dead works are inactive, then filtering by Terminated will never show anything.

Also reinstituting the default sort on All Works page for active work
