### ISSUE TITLE
Phase End Milestone - Confetti forever

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2273]
**Describe the bug**

Keep getting confetti if you make description changes to the locked end event

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Connor1892** [comment]
@djnunez-aot what is the estimate here?

**Comment by carlygreenehill** [comment]
@Connor1892   please note that @djnunez-aot is now on holiday!
