### ISSUE TITLE
Insights - Staff Grid not loading

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2281]
**Describe the bug**
the show more grid is not populating any data!!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by maria-kuzmenko** [comment]
@djnunez-aot , we lost somewhere Analyst column, we used to have it and it is in the graph above...

<img width="1873" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmd4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80e7ff491ce82f220cb9fb9d912385914700800c/Screen%20Shot%202024-06-03%20at%201.47.40%20PM.png" alt="Screen Shot 2024-06-03 at 1.47.40 PM.png" />
