### ISSUE TITLE
UI Change - App version update

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2310]
**As a** User

**I want** to see what version the app is

**so that** I can live up to my expectations

### Scenario 1: 

GIVEN The menu item is open
WHEN look at the menu items
THEN I see text 'Version: 'current version number' with margin_bottom 40px and font Subheading/Regular

### Screenshot 1:
<img width="1294" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDVWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--adb21bf2466c6b247bdd8500d09dbc14ad897e53/Screen%20Shot%202024-06-11%20at%201.32.20%20PM.png" alt="Screen Shot 2024-06-11 at 1.32.20 PM.png" />

### Scenario 2:
GIVEN The menu item is closed
WHEN look at the menu items
THEN I see text 'current version number' with margin_bottom 40px and font Subheading/Regular

### Screenshot 2:
<img width="1167" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUZWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c93156e2da7beee3946e30845a2584c34a6da6fd/Screen%20Shot%202024-06-11%20at%201.33.58%20PM.png" alt="Screen Shot 2024-06-11 at 1.33.58 PM.png" />

**Comment by jadmnsaad** [comment]
Version update to what?

**Comment by Connor1892** [comment]
@maria-kuzmenko to add screen

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot https://www.figma.com/design/XcYynwH7xrO2P30uqewaLS/For-Development?node-id=203-2449
