### ISSUE TITLE
Workplan - Overdue Warning for non-legislated phases

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2358]
---
overdue/past due warnings on non-legislated phases should be purple instead of red.
@maria-kuzmenko will decide on colourcodes.

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
@tom0827 , @Connor1892 

MA is using this hex for purple chips, we can borrow that - #4006AC
