### ISSUE TITLE
Reports - Referral Schedule Download Corrupted

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2365]
**Describe the bug**
The download for the Referral Schedule cannot be opened.
all other reports are working fine.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="517" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFFJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e20aec65a4304a5f2c6d24ed3ab22ffd6fa9a4a/image.png" alt="image.png" />

**Additional context**

**Comment by tom0827** [comment]
downloads working in prod
