### ISSUE TITLE
Project Notification - Notification Review - Comment Period

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2379]
---
The EAO has updated the Project Notification policy and there is a small change needed for the Project Notification WORK event configuration.  For the “Comment Period” event listed in PHASE 2 (Notification Review), the event itself must be changed to “Suggested” and the standard length of the Comment Period should be changed to 21 days.

•	“Notification Review | Comment Period” is now SUGGESTED
•	“Notification Review | Comment Period” is now 21 days

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
apparently this fix might already have been done. can someone confirm?

**Comment by tom0827** [comment]
New template has been uploaded into dev and test environments
