### ISSUE TITLE
API to export the data in a way that it can be reimported to another EPICFLOW environment

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#308]
**Overview**
It should be possible to export the data from postgres database in a format that it can be re-imported to the another environment . 
The output excel formats are available. 
we have now
- Staff
- Proponent
- Project
- INs
- Works

**Comment by carlygreenehill** [comment]
This will be needed for PROD > to take Test data (that has been manipulated while in EPIC FLOW, and pull to new prod env)
