### ISSUE TITLE
APIs for checking uniqueness in the forms

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#347]
the list is below (this will change over time and with updates to labels and data requirements):

Add EAO Staff - CONCAT "First Name", "Last Name"
Add Indigenous Nation - "Name"
Add New Work - "Title"
Add Project - "Name"
Add Proponent/Certificate Holder - "Name"

**Comment by dinesh-aot** [comment]
Uniqueness of work form should be based on title only. 
Indigenou nations check doesn't work

**Comment by salabh-aot** [comment]
For work, the other validation was added a while back to prevent work with same work type and project getting created. Is this validation no longer needed?
