### ISSUE TITLE
Comments on the first draft of resource forecast PDF output

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#443]
**Overview**
- Please check the title where it says the month on the top left corner - it should be the report date's month
- The black panel should contain the count of each work type in a pair of parenthesis

## Question to EA Team
- Please check the attached pdf to see if there is any changes or corrections required
- Should it be Sector(SUB) or Type(SUB) 
- Please check the rest of the column headers
- Please check the PDF layout size to see if this is what we expect

[https://app.zenhub.com/files/497089911/2f3c13d6-2c3e-4666-8801-6cca5bd5155f/download](https://app.zenhub.com/files/497089911/2f3c13d6-2c3e-4666-8801-6cca5bd5155f/download)

**Comment by dinesh-aot** [comment]
- Still the right of the pdf is getting cut off

**Comment by Connor1892** [comment]
will fixing the names in the team member section shrink the table by enough?
(removing the non-analysts/officers)
