### ISSUE TITLE
Report PDF Margin

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#467]
**As a** superuser

**I want** the margins on all report PDFs to be a minimum of 1/4 inch on each side

**so that** reports can be printed on any modern printer

### Scenario 1: 

GIVEN the resource forecast
WHEN printing on 11 x 17 paper
THEN the margin must be 1/4 inch

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by salabh-aot** [comment]
Added 3/4 inch margin on both sides. Please verify.
