### ISSUE TITLE
Resource Forecast Column Content

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#469]
**As a** superuser

**I want** the content of the resource forecast to use 'short_name', or wrap correctly

**so that** all possible entries are displayed properly

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by salabh-aot** [comment]
Adjusted the report such that columns will have fixed width and content will wrap instead of overflowing.

**Comment by Connor1892** [comment]
Is this pushed to Dev? when I download it's still not wrapping and overflowing the page.
Also seems to have undone the work on #634
