### ISSUE TITLE
30-60-90 Report

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#475]
**As a** Superuser

**I want** to be able to create, view, modify, and download a 30-60-90 Report in the Report Section of EPIC.flow

**so that** a 30-60-90 Report can be created for various audiences based on a chosen start date. 

## Geoff Note
The 30-60-90 report uses:
•	All Work that has an anticipated decision date that is within X+90,
•	All “Watched” Work that have anticipated events flagged as “Reportable” (ticket #479) within X+90,
•	Work “Title” of all Work that meet the above criteria,
•	Work Type “Work Report Title” of all Work that meet the above criteria,
•	Work “Short Description” of all Work that meet the above criteria,
•	Work “Status” based on the day closest to X without being past X (X or less) of all Work that meet the above criteria,
•	“Anticipated Date” from all Decision Events that fall within X+90 of all Work that meet the above criteria,
•	“Decision Information” (ticket #477) from Decision Events that fall within X+90 of all Work that meet the above criteria,
•	Engagement Start and End Dates from “Watched Work” (ticket #476) within X+90,
•	Comment Period “PCP Explanation” (ticket #480) from Watched Work that fall within X+90,

![image.png](https://images.zenhubusercontent.com/63fe4eac600d24d741b223ee/473c95e6-ccc1-422f-a804-9bcf9334cbe1)

### Scenario 1: 

GIVEN: There is a need for a 30-60-90 Based on April 1, 2023
WHEN: April 1st is selected on the Report Webview Page
THEN: The system will generate a 30-60-90 Report with all the correct information based on the chosen date (April 1, 2023 thru June 30, 2023) for every Work that has a Decision or a Watched Reportable event in that date range.

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
[April.30-60-90_EAO_FINAL.pdf](https://github.com/bcgov/EPIC-FLOW/files/11142706/April.30-60-90_EAO_FINAL.pdf)

**Comment by dinesh-aot** [comment]
**Tasks**
- Create Report API - 5
- Create UI - 3
- Create PDF Report - 5
