### ISSUE TITLE
Remaining Worktypes Pt1

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#493]
[https://app.zenhub.com/files/497089911/b07178b7-0c55-4378-8eb4-3789c81cb651/download]
(https://app.zenhub.com/files/497089911/682c70e6-a08b-4dc6-a4e1-884b05bcba4a/download)

We are using the Events 2018 tab from the attached excel for TR2.

Priority:

- ~Project notification~ *check to see any differences
- ~EAC extension~
- ~Exemption order~ -- lighter workload
- ~Typical Amendment~ 
- ~Complex Amendment~ *check to see any differences
- ~EAC/Order Transfer~

**Comment by EAO-App-Admin** [comment]
Can we get the duration of each phase, color code, whether it is legislated or not:
- Project Notification - 60 day duration (legislated) - no color as of yet
- EAC Extension - 120 day duration (non-legislated) - Post Certificate Green
- Exemption Order - same phase duration as Assessment (90-365-60) - same colors as Assessment - ends at Readiness Decision
- Simple Amendment - 60 day duration (non-legislated) - Post Certificate Green
- Typical Amendment - 180 day duration (non-legislated) - Post Certificate Green
- Complex Amendment - 365 day duration (non-legislated) - Post Certificate Green
- EAC/Order Transfer - 60 day duration (non-legislated) - Post Certificate Green
