### ISSUE TITLE
decision_by logic has to be corrected in RR(Referral Report)

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#571]
**How to reproduce**
- Create an assessment work
- Add events in such a way that the next major decision should be the referral
- Update the status of the work
- Get the RR according the posted date logic of the status field

**Expectation**
- The decision by field of the report should show the value shown in the "Other Responsible Minster" field in the work form

**Actual**
- It shows the value selected in the "Decision Maker" field in the Teams tab

**Comment by Connor1892** [comment]
needs to be updated to track instead of flow
