### ISSUE TITLE
30-60-90 WebView Tweaks

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#578]
- Differentiating the works on the webview if there are multiple for a project.
 - there seems to be doubling up on works/projects shown. is this purposeful?

**Comment by EAO-App-Admin** [comment]
Label for webview 30-60-90 item is:
[workTitle] - [eventTitle]: event actualDate OR IF NULL anticipatedDate

**Comment by Connor1892** [comment]
would to be possible to indicate what the date means?
maybe: next event: 2023-04-12

**Comment by EAO-App-Admin** [comment]
If we have something like
Site C Clean Energy - Amendment 09 Decision: July 14, 2023 

what are we missing in terms of explaining the date?

**Comment by Connor1892** [comment]
the Baldy Ridge one isn't a decision and wasn't immediately clear.
is there a way to make it obvious across all possible options?

if this is all going to be refactored when Maria gets to it though then it's fine for the interim.
