### ISSUE TITLE
Resource Forecast Referral changes

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#590]
**As a** team member

**I want** to see the referral phase in the resource forecast

**so that** I know when the work is going to be referred

### Scenario 1: 

GIVEN the Cariboo amendment refers on 2023-04-19
WHEN selecting the RF on 2023-04-02
THEN I see the Cariboo amendment on the RF

### Scenario 2:

GIVEN a work is on the RF
WHEN the work is referring in April
THEN I see "referred" in the Q1&Q2 sections of the report from May onward

### Scenario 3:

GIVEN a work has been referred but not decided
WHEN I see the work on the RF
THEN I see "referred" in the Q1&Q2 sections of the report from May onward

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
when looking at 2023-02-28 we can see Cariboo Gold is referred and coloured green.
but when going 2023-03-01 we now see Cariboo Gold is referred without a colour.

**Comment by salabh-aot** [comment]
When tested, Cariboo Gold is listed with Green color (report date: March 1, 2023) and below that a new row is listed with `Project Notification` which has phaseColor set to white in database. Can you verify? Please let know if phaseColor for `Project Notification` needs to be updated.
![rf march 1.png](https://images.zenhubusercontent.com/6202b06eee5f0a9edd03c138/dc63b17f-394c-4a50-bbc5-611cac5fb89a)

**Comment by Connor1892** [comment]
the resource forecast now looks correct on the webview, and the PDF colours are correct, but I've hidden all the rows and it's lost the project name:
[EAO_Resource_Forecast-2023-03-01.pdf](https://github.com/bcgov/EPIC.track/files/11602382/EAO_Resource_Forecast-2023-03-01.pdf)
