### ISSUE TITLE
Add existence check in staff with email address

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#598]
**As a** team member

**I want** Epic.track to validate new staff member by email

**so that** we don't introduce duplicates into the system

### Scenario 1: 

GIVEN I enter the same staff member twice
WHEN I attempt to submit the second one
THEN I will not be able to press submit

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
#495
