### ISSUE TITLE
Devops Tasks

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#601]
- ~Clean up the helm charts~
- Convert the build config as helm chart
- ~Create helm charts for the reports-api~
- ~Repository rename~
- Reports-api rename
- ~Github action to trigger CD(webhook)~
- Create Readme files

- Patroni installation
- Github Action CD
- Github Action CI
- Backup containers
- Remove forms-flow references

**Comment by Connor1892** [comment]
for Saravan
