### ISSUE TITLE
Default Sorts on EA Type

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#639]
**As a** team member

**I want** a default sort on the Resource Forecast

**so that** I can easily see and prep the Resource Forecast for export

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
EA Type -> Project Name ( Sort )
