### ISSUE TITLE
Default Rows on Grids

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#640]
**As a** Team Member

**I want** the default number of rows on grids to be 'all'

**so that** I can scroll instead of having to manipulate the options in the bottom right every time

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
Show everything by default unless there is a specific request.

**Comment by dinesh-aot** [comment]
Natural sort always

**Comment by dinesh-aot** [comment]
https://en.wikipedia.org/wiki/Natural_sort_order
