### ISSUE TITLE
Searchable fields on the Update work Modal

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#641]
**As a** Team Member

**I want** to be able to search the fields on the update work modal

**so that** it is easy to find and select my options when updating/making work

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
Make it auto complete always
