### ISSUE TITLE
Look into the default order per list

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#642]
**As a** team member

**I want** there to be a default order for each page of the data management pages

**so that** they are easier to read and find entries

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
staff - lastname, firstname asc natural sort
IN - name 
Proponent - Name
Project - Name
Work - Project, Name
