### ISSUE TITLE
Resource Forecast PDF switching/dropping columns

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#647]
Recreate: Hide all columns except EA type. you will see that the columns are misaligned.

---

**As a** super user

**I want** to be able to hide all the resourcing columns without breaking the PDF report

**so that** I can create custom reports for export

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
non-hidable - project name, type, ea type, env region

**Comment by Connor1892** [comment]
The Bug is reproduceable by hiding all the columns associated with EAO resourcing.
