### ISSUE TITLE
Roles Implementation

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#662]
**As a** Instance admin

**I want** superusers to have roles

**so that** I can silo their responsibilities

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
List of Super user types:
- HR
- IPE
- T12
- DST
- AA

changes:
Staff -> HR, AA, DST
Nations -> IPE
Reports -> T12, DST

**Comment by Connor1892** [comment]
System Admin Role needs to be made

**Comment by saravanpa-aot** [comment]
ROLE | Permission
-- | --
Developer | godlike
System Admin | super powers across all apps
Instance Admin | super powers in 1 app
Superuser | CRU powers in 1 app
Team Member | CRU powers in "things" they are assigned to
Viewer | See all, change nothing

**Comment by dinesh-aot** [comment]
https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/394
