### ISSUE TITLE
Audit Trail Spike

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#666]
---
Historical Lvls:
1. Have
2. Have
3. Need
---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
![image](https://github.com/bcgov/EPIC.track/assets/126211473/4dc2cbe3-fe6e-4712-8e3b-91deee2e4fa5)

**Comment by Connor1892** [comment]
![Audit Trail spike](https://github.com/bcgov/EPIC.track/assets/126211473/e0a3b4ce-22b6-425c-886f-fc226b8c3e4d)

**Comment by dinesh-aot** [comment]
1) Have history table  - 5
2) Create special field table for project - 2
3) API for special field management - 5
4) UI to manage the history of the special fields - 5
