### ISSUE TITLE
Reporting breaking in future dates

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#684]
---
Referral Schedule has no data on 2023-10-31
Resource Forecast shows fine on 2023-10-31, but has an error screen on 2023-11-01
---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
The issue still exists when you chose 2024-11-01. I think it is the month calculation issue. If the month index starts from 0 then there is no month as 12. I think you are adding the current month which is 11 + 1. Please check. @salabh-aot

**Comment by dinesh-aot** [comment]
@salabh-aot  Now it is happening on 2024-12-05
