### ISSUE TITLE
Title check for work

### ISSUE THREAD

**Issue by SachinChaudharyEAO** [bcgov/EPIC-FLOW#723]
As a team member

I want EpicTrack to validate new Work Title.

so that we don't introduce duplicates into the system

Acceptance Criteria
Scenario 1:
GIVEN I enter the same work title twice
WHEN I attempt to submit the second one
THEN I will not be able to press submit

Validation Rules?
(If yes, list here)

Screenshot
(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
when attempting to add a second work with the same name, I get a forever loading screen.
there are no error messages or fix it options.

**Comment by dinesh-aot** [comment]
The latest update for the above fix wasn't properly tagged. Could you please try this again @Connor1892
