### ISSUE TITLE
Phase End date error popup

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#726]
**As a** team member

**I want** to see an error message when I put a milestone outside phase end date

**so that** milestones never fall outside the phase

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by c-woodberg** [comment]
Please wordsmith as required (I'm not sure that I fully understand task/the relationship between milestones and phase in the system, but I have been _so_ brave and had a crack at this!):
 
**Use "Oops" and "You" - No Solution**
1. Oops! You have entered a milestone date that falls after the phase end date. _(If this is a specifically an **after** phase problem)_
2. Oops! You have entered a milestone date that falls outside of the phase start or end dates. _(If this is a **before** or **after** phase problem)_

**Use "Oops" and "You" - Plus Solution**
3. Oops! You have entered a milestone date that falls after the phase end date. You can adjust the milestone date or update the phase end date.   _(If this is a specifically an **after** phase problem)_
4. 2. Oops! You have entered a milestone date that falls outside of the phase start or end dates. You can adjust the milestone date or update the phase start/end dates. _(If this is a **before** or **after** phase problem)_

**Use "Error" and no "You"  - No Solution/With Solution**
5. Error: The milestone date falls after the phase end date. 
6. Error: The milestone date falls outside of the phase start or end dates.
7. Error: The milestone date falls after the phase end date. Adjust the milestone date or update the phase end date.
8. Error: The milestone date falls outside of the phase start or end dates. Adjust the milestone date or update the phase start/end dates.

**Comment by Connor1892** [comment]
what about:
"The milestone date is after the end of the phase. An extension is required to use this date."

this gives them context & a solution?
