### ISSUE TITLE
Celebratory Fireworks when Phase completed

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#752]
---

when phase closes the accordion should move to closed phases with toggle flipped to showing.

celebration animation shows every time the work is opened for 24hours after the phase is closed

https://alampros.github.io/react-confetti/?path=/story/props-demos--knobs

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
confetti for phase?
Fireworks for work?

**Comment by dinesh-aot** [comment]
@djnunez-aot Can you take a look at the below mentioned library for the fireworks
https://www.kirilv.com/canvas-confetti/
It has wide verities of fireworks and animations. 
Regarding the implementation, these are my thoughts @jadmsaadaot  Please add your comments
- Create both fireworks and confetty as components or single components with passing parameters to distinguish
- Fireworks should be shown in the entire application level, so can it be in the root level and triggered by redux state and keep it for a specific duration and goes off
- Show confetty only when a phase gets completed, it can be shown within the phase accordion

**Comment by Connor1892** [comment]
@djnunez-aot MARIA IS SO BETRAYED BY THE LACK OF FIREWORKS AND CONFETTI!!!!

**Comment by Connor1892** [comment]
no displays for both for old works and newly created.
