### ISSUE TITLE
Workplan Page - Component Layout UI

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#773]
**As a** User

**I want** to be able to see basic information about this work

**so that** I can navigate the work and live my life

### Scenario 1: 

GIVEN I am logged in and is on the "My Workplans" page
WHEN I click on a Work card's "Update" button
THEN I will see the following information:
- "Title of the Work"
- "Workplan" tab (active)
- "Status" tab (disabled)
- "Issues" tab (disabled)
- "About Project" tab (disabled)
- "Team" tab (with number of assigned team members) (disabled)
- "First Nations" (with a number of assigned nations to the project) (disabled)

**Comment by maria-kuzmenko** [comment]
updated our StyleGuide by adding 'Implementation Specifics' for **Tabs**.

https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=927%3A1622&mode=design&t=tS27aCjaP2vEV2B0-1

**Comment by maria-kuzmenko** [comment]
I've changed default tabs to disabled as we haven't had them implemented yet

**Comment by maria-kuzmenko** [comment]
@dinesh-aot ![Workplan - Component Layout.png](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/0ec42ca8-978a-4c09-8baa-bbdc5053e87f)

1. We have some verbiage changes for Tabs
2. Name of the Work - different color + letter spacing (added in CSS)
3. Can we get rid of the hover state while item is selected? added this twitching?
4. Can we get rid of the box effect that appears while moving through tabs?

**Comment by maria-kuzmenko** [comment]
@dinesh-aot 

can we add Tabs underline behaviour like this by having blue stoke not above the grey one but changing into it? Creates smoother transition

https://codepen.io/tatimblin/pen/oWKdjR
