### ISSUE TITLE
Profile Menu

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#781]
**As a** user

**I want** to be able to quickly see and copy my contact information

**so that** I can live my best life

### Scenario 1: 

GIVEN I am logged in using IDIR
WHEN I hover over or click on the user avatar
THEN the contact card will appear with the following data:
- avatar name (first name last name)
- email with copy icon
- phone number with copy icon

**Comment by maria-kuzmenko** [comment]
Icons for copy

![copy-default.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/7e5ad291-4786-4674-a03c-9fbd22e24bb5)

![copy-hover.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/7aa73834-eb37-444d-8257-545db635fab3)

**Comment by maria-kuzmenko** [comment]
Design Implementation / Bars & Collapsed Phases - 07-07-2023

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/Workplan?type=design&node-id=945%3A64853&mode=design&t=JZsXk2rJzJFDbTBi-1

**Comment by maria-kuzmenko** [comment]
font size for the person's name and 'Contact' should be the same - 14px - Caption 02
![Screen Shot 2023-07-20 at 3.19.48 PM.png](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/32bcaa43-c414-4b85-af77-fa6e6b34efb6)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot , please, double-check the icon - it shows that its dimension is 10px. It does look weirdly tiny

there should be no 'copy' button if we do not have any information

![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/d9535747-53d9-4b28-9642-fad8ed8e208b)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot the icon is not positioned centrally - maybe not .svg was used but font
![Screen Shot 2023-07-20 at 3.24.29 PM.png](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/b4da01e6-c0f3-4a78-8e58-fedb42e241c2)

**Comment by maria-kuzmenko** [comment]
attaching both icons

![copy-default.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/dc467880-c109-4ee8-a20b-c3d0c1dd146a)
![copy-hover.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/a369b5f8-d5f2-423c-a8b8-b371424a7106)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot adding shadow specifics here as well + we need bottom corners with 4px radius as well

![shadow+corners_profile.png](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/a318c34d-c7cb-4311-aed5-08a7525f8c35)
