### ISSUE TITLE
Top bar adjustments

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#782]
**As a** user

**I want** to see what application I am in

**so that** I know what should be done

### Scenario 1: 

WHEN User is logged in through IDIR
THEN they should see the following information left to right:
- BC gov logo on the left
- EPIC.track logo next to it
- their name in the format of "Hello, NAME"
- their avatar (initials in order of first name last name)

### Scenario 2:
 
GIVEN a user is logged into the testing environment through IDIR
WHEN The user comes to EPIC.track
THEN they should see the yellow bar expanded and has the text "This is a TEST environment" with an information icon left of the text.

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
@maria-kuzmenko
we need file attachment

**Comment by maria-kuzmenko** [comment]
GovBC logo White on transparent
![gov_bc_logo.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/9a54058b-2db1-4e8a-b766-f8dd129fe511)

**Comment by maria-kuzmenko** [comment]
EPIC.track logo - White on transparent (you can't preview it, but it's here - just click below)
![Epic.track_logo.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/6efa26bc-6086-4fe2-b232-720433c48683)

**Comment by maria-kuzmenko** [comment]
information icon for the yellow bar

![information.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/a6b58544-19ca-4942-85a3-4d7060b3fe0b)

**Comment by maria-kuzmenko** [comment]
Design Implementation / Bars & Collapsed Phases - 07-07-2023

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/Workplan?type=design&node-id=945%3A64853&mode=design&t=JZsXk2rJzJFDbTBi-1

**Comment by maria-kuzmenko** [comment]
@dinesh-aot , please, double-check shadow value - should be

/* Shadow/XS */
box-shadow: 0px 4px 8px 0px rgba(0, 0, 0, 0.10);

**Comment by maria-kuzmenko** [comment]
@dinesh-aot, adding a screenshot with box-shadow I've changed
![shadow_top menu.png](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/80f83bd3-a7ba-4470-a92c-f683f1c8c7cd)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot 

remove extra shadow
