### ISSUE TITLE
Side bar updates

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#783]
**As a** user

**I want** easy navigation of the system

**so that** I can find what I need

### Scenario 1: 

WHEN the User logs in to EPIC.track in from IDIR
THEN "My Workplans" page is open by default
THEN User can see the side bar with a fixed width and the following menu items from top to bottom:
- "All Work" with the list icon (default)
- "My Workplans" with grid icon (active)
- "Reports" with files icon (default)
- "Insights" with chart - Pie icon (default)
- "List Management" with gear icon (default)

### Scenario 2:

GIVEN the User logged in to EPIC.track in from IDIR
WHEN the user click on reports
THEN they see the following menu items:
- "EA Referral Schedule"
- "Resource Forecast"
- "30-60-90"

### Scenario 3:

GIVEN the "Reports" menu list is open
WHEN I click on "List Management"
THEN "Reports" submenu collapsed
THEN I can see the following menu list:
- "Staff"
- "Indigenous Nations"
- "Proponents"
- "Projects"

**Comment by maria-kuzmenko** [comment]
Design Implementation / Bars & Collapsed Phases - 07-07-2023

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/Workplan?type=design&node-id=945%3A64853&mode=design&t=JZsXk2rJzJFDbTBi-1

**Comment by maria-kuzmenko** [comment]
Icons for side bar - secondary500 (active), white (default), primary500 (hover)

![list.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/b3bfba3f-356f-4383-a5df-b873aa58881a)

![grid.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/20af7f06-b4a8-4b9c-a910-cde920a9c61a)

![files.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/6ffa23cc-d51a-49e0-8916-25aef57740d9)

![chart-pie.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/bcb71b65-dabf-4499-abb1-5af652a3bf73)

![gear.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/2492c8fd-e745-4864-a70f-75b5eb7dfb9d)

**Comment by maria-kuzmenko** [comment]
@maria-kuzmenko provide icons from Admin and Templates

**Comment by maria-kuzmenko** [comment]
@dinesh-aot 

![Screen Shot 2023-07-13 at 10.52.26 AM.png](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/6a375914-7ba5-4247-a988-0c0a6f4406ff)

changes:
- moving My Workplans to the top
- 32px height between groups, 0px height between Menu items within the group
- For List Management, we'll use a different icon, Gear icon goes to the Admin Menu item

**Comment by maria-kuzmenko** [comment]
Template Icon

![file-pen.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/1abe5d28-2223-48ff-9634-4f43b834ef95)

List Management Icon
![file-spreadsheet.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/87f9f54d-0a07-47bc-9c8e-aae120ab0a44)
