### ISSUE TITLE
Confirmation Dialog Redesign

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#784]
**As a** Dev

**I want** a generic component

**so that** I can reuse the correctly styled Confirmation Dialog in multiple places

**Comment by Connor1892** [comment]
link to buttons: https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=500-9476&mode=design&t=DrBRJqUM2xgWnSwO-0

**Comment by maria-kuzmenko** [comment]
Close button for the confirmation window

![close.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/8c605aba-f2bc-44f6-97a4-31c16cdc80e0)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot 

1. Big buttons
2. Ghost button stays the same size when on hover

**Comment by maria-kuzmenko** [comment]
@dinesh-aot 

1. Remove the shadow from 'Delete' button
2. Confirmation text change colour to Neutral Dark - rgb (49,49,50)
