### ISSUE TITLE
Error/success notifications component

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#785]
**As a** Dev

**I want** a generic component to show errors or success notifications

**so that** I have a correctly styled snackbar component that shows up in the bottom right and can be reused across the system

**Comment by Connor1892** [comment]
https://mui.com/material-ui/react-snackbar/

**Comment by Connor1892** [comment]
multiple will show stacked vertically

**Comment by maria-kuzmenko** [comment]
Organisms - For Implementation / 06. Alerts & Notifications

https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=844%3A1552&mode=design&t=9m39IYGdVHvhaZ9c-1

**Comment by maria-kuzmenko** [comment]
icons for Alerts & Notifications

Error
![circle-explamation-bold.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/79334e8b-4df7-4966-b55e-adb9af6d552e)

Information
![circle-information.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/dde2cf1e-6987-4752-8cb7-1eb322e1d126)

Warning
![triangle-exclamation.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/708a139d-f374-43c3-b431-3ffd94dc2ea2)

Success
![check-circle.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/fa0e63ab-d9fb-446f-a064-3458633e29c9)

Close 
![close.svg](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/36ee1970-a20f-4f23-8edc-b425c610460b)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot 

close button is too small on the notifications - should be the same size as the icon - 24*24
![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/19bc0c14-eb29-4625-b575-66fcabfd0302)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot , we still have some old notifications for some things - like, creating a new proponent
![Screen Shot 2023-07-20 at 3.11.19 PM.png](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/41ce9ded-bbc6-4b1a-918e-0af2cde7c410)
