### ISSUE TITLE
Rich text enhancement to notes

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#797]
---

**As a** User

**I want** to user RTE

**so that** I can leave important messages to my team

### Scenario 1: 

GIVEN Workplan page is open
WHEN Open Notes on First Nations / Issues / Status
THEN I see the following UI changes:

**.rdw-editor-toolbar {**
background: #f9f9fb;
margin-bottom: 8px;
padding: 8px 8px 8px;
border-bottom: 1px solid rgb (224, 224, 224); 

### Screenshot 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWV5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6fffaac7eaea92aaa5794bcc61adda9898876c32/Screen%20Shot%202023-11-07%20at%206.42.22%20PM.png)

**element.style {**
height: 485px;
padding: 16px;
resize: vertical;
border: 1px solid rgb(224,224,224);
padding-top: 0px;
border-radius: 4px;

**.public-DraftStyleDefault-block {**
 margin: 8px 0;

### Screenshot 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXl5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa6d44b83c0605dbbe5aeeffcc222fc0f73a4689/Screen%20Shot%202023-11-07%20at%206.46.48%20PM.png)

### Scenario 2: 

GIVEN Workplan page is open
WHEN I click on Notes section
THEN I see the border colour changes to #0070E0

### Screenshot 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk95QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f289e2ade95da55cf6d629a774fcacaad7397517/Screen%20Shot%202023-11-07%20at%206.59.26%20PM.png)

### Scenario 3: 

GIVEN Workplan page is open
WHEN Open Notes on First Nations / Issues / Status
THEN I see the following changes to functionality:

**Remove:**
- Superscript
- Subscript
- Block Type 
- Embedded
- Image

**Change**
- Text font is default to 16px

### Scenario 3: 

GIVEN Notes are open and has text notes 
WHEN I click on any tab
THEN Notes are saved

**Comment by Connor1892** [comment]
@maria-kuzmenko

**Comment by carlygreenehill** [comment]
Rich text working great + notes are saving! I believe the autosave resets the typing cursor to start back at the beginning, so as a user is typing, their sentences can come out sort of garbled. See screenshot:

![image](https://github.com/bcgov/EPIC.track/assets/101662408/c066d555-9f92-4fa9-955a-fd9ab99c5f9a)

**Comment by Connor1892** [comment]
![image](https://github.com/bcgov/EPIC.track/assets/126211473/36212156-43fa-4fb4-af43-f064d92cffe1)

Confirming that these are the final set of options desired?
@maria-kuzmenko
