### ISSUE TITLE
Workplan Page - Phase Accordion

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#815]
**As a** user

**I want** to see the list of phases in this work

**so that** I can live my life

### Scenario 1: 

GIVEN I logged in through IDIR and I am on the "My Workplans" page
WHEN I click on the "Update" or "View" button on a work card
THEN I see a skeleton loader for the list of phases associated with that work (#773)

### Scenario 2:

GIVEN a work page is opened
WHEN skeleton loader is finished loading
THEN I see the "Current & Future Phases" label
THEN I see the current phase expanded and Future phases collapsed with the following information:
- phase name
- start date
- days left
- anticipated referral or decision date (as needed)
- next milestone

### Scenario 3:

GIVEN current phase on workpage is expanded
WHEN I click on any Phase Accordion header
THEN the current Phase Accordion collapses
AND if it was a future phase, that Accordion opens

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
@maria-kuzmenko , add milestone progress svg stuff in here for Dinesh

**Comment by maria-kuzmenko** [comment]
@dinesh-aot list of comments we've discussed:

1. Color change for Work Title to  **Primary/Main rgba(0, 51, 102, 1)**
2. Color change for 'download' and 'template' buttons to **Primary/Accent/Main rgba(26, 90, 150, 1)**
3. Accordion start date - **remove space between date and year**
4. Accordion titles - add **letter-spacing: 0.39px;**
 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBWUE9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--54906b3358a13574974556a4bc28096d1fe56f02/Screen%20Shot%202023-08-11%20at%202.34.31%20PM.png)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot 

1. Look into round corners for inline filters (left and right margins of equally 8px). Can we add +8px for the overall table, so the first column will have a total of 16px left margin and the last column will have a total of 16 px right margin?
2. Look into opened accordion - border change and round corners 
3. We should get rid of horizontal scroll for resolutions 1440+
3. Animation from closed to opened accordion

**Comment by maria-kuzmenko** [comment]
1. Icon change - attached both chevrons
2. Margin between icon and text - 12px (if possible)
3. Height of the text container - 48px (icon in the middle)
4. Height from action buttons to the line to be increased to 24px.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBWUU9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0b579b318576db3dac6cf14535a72877d0f59894/Screen%20Shot%202023-08-11%20at%202.37.37%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBWWs9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ae92875051551183865e6c8f8e0e5181941f0e65/16.svg)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBWW89IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--08383fc4774a4ca291d3e3105a839d2228a7154f/16.svg)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot 

uploading icons for progress:

**not started**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBWkE9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--73f308aba53932ddda665b7e148520e08e86aee8/progress-not%20started.svg)


**in progress**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBWTQ9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a857d09fc05f1614aa28b26d6d339b7779342287/in%20progress.svg)

complete
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBWTg9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--069f13d0e2b57ca1246f3cd5e1a4b33f8d157627/complete.svg)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot 

Tooltips are only shown on the Milestone/Task titles

**Comment by maria-kuzmenko** [comment]
@dinesh-aot  just saw those guys (filter icons) when I start searching/filtering. My guess is, they came from MUI - we need to get rid of them/hide.

![Screen Shot 2023-08-15 at 9.24.26 AM.png](https://images.zenhubusercontent.com/63c71e66a8dc0f235f952b8c/a3f5aa07-4efc-4609-af4e-6a15dbc4dba8)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot , this is for the truncation for the next Milestone - we've discussed it but I forgot to put in in here

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDQ0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2103ead312ace5718ff0ac548b762c8437183bfa/Screen%20Shot%202023-08-24%20at%204.01.00%20PM.png)
