### ISSUE TITLE
Workplan Page - List all tasks/milestones under a phase

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#819]
**As a** user

**I want** to see all legislated milestones

**so that** I can plan what tasks to add to reach those milestones

### Scenario 1: 

GIVEN I am in a workplan page
WHEN I open any phase accordion
THEN I see a grid view of all the legislated milestones with following titles:
- Task/Milestone
- type
- start date
- end date
- days
- assigned
- responsibility
- notes
- progress

### Scenario 2:

GIVEN I am in a workplan page
WHEN I open any phase accordion
THEN I see a checkbox to the left of search/filters
SO THAT I can do multiselect actions on non-milestone events

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
Link to the design library

https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=1163-2228&mode=design

https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=1174-2337&mode=design
