### ISSUE TITLE
Workplan Page - Download Functionality - UI

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#823]
**As a** user

**I want** to be able to download my workplans

**so that** I can save templates

### Scenario 1: 

GIVEN I have any phase accordion open
WHEN I hover over export workplan button
THEN I see a tooltip with "Export workplan to excel"

### Scenario 2: 

GIVEN I have any phase accordion open
WHEN I click on the export workplan button
THEN I see a download progress tracker
THEN I get that phase of my workplan downloaded to my computer in an .xslx format
AND I get a confirmation message

**Comment by dinesh-aot** [comment]
filename: project_name/work_title/phase_name
