### ISSUE TITLE
Workplan Page - API - load filter values

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#825]
---
name: User Story
about: 'User Story '
title: ''
labels: ''
assignees: ''

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by carlygreenehill** [comment]
@Connor1892 not sure how to QA this one. Can you provide recommendations?

**Comment by dinesh-aot** [comment]
[Uploading... MicrosoftTeams-image (5).png]

This card was about loading data to those filters as I highlighted. @carlygreenehill

**Comment by maria-kuzmenko** [comment]
@carlygreenehill , that's what Dinesh refers to

- Assign pulls Active members from Team Tab
- stale list for Responsibility & Status

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU5GQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef11f901b64b9cb678aadcb7d05d5ec594fc1962/Screen%20Shot%202023-10-17%20at%209.17.34%20AM.png)

**Comment by carlygreenehill** [comment]
THERE ARE FILTERS!!! <3
