### ISSUE TITLE
Workplan Page - Add Task UI

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#829]
**As a** user

**I want** to add tasks

**so that** I can customize my workplan

### Scenario 1: 

GIVEN any phase is open 
WHEN I click on "Add Task" button
THEN I see the add task modal with the following:
- modal title: "Add Task" label
- divider bar
- Title label (mandatory) with the input text field 'Title'
- Start Date label with the date picker field 'MM-DD-YYYY'
- Days label with the input text field
- End Date label with the date picker field 'MM-DD-YYYY'
- Progress field (mandatory) with a single select dropdown 'Select your progress'
- Assigned field with the multi-select dropdown 'Select Name'
- Responsibility field with the multi-select dropdown 'Select Responsible Party'
- Notes field with the rich text field
- 2 buttons:
  - 'Cancel' button (ghost)
  - 'Save' button (primary)

**Comment by maria-kuzmenko** [comment]
References for Single and Multi-select dropdowns can be found here - https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=789-812&mode=design

**Comment by maria-kuzmenko** [comment]
References for Task Modal appearance can be found here - 
https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=1030-1893&mode=design
