### ISSUE TITLE
Workplan Page - Add Milestone UI

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#830]
**As a** user

**I want** to add milestones

**so that** I can create reportable events

### Scenario 1: 

GIVEN any phase is open 
WHEN I click on "Add Milestone" button
THEN I see the add milestone modal with the following:
- modal title: "Add Milestone" label
- divider bar
- Milestone Type Label (mandatory) with a single select dropdown with a list of available milestone types

### Scenario 2: 

GIVEN a milestone modal is opened
WHEN I select the milestone type
THEN I see Title text field with prepopulated Milestone type and active cursor 
THEN I see a help text with identifier of how many characters are left

### Scenario 3: 

GIVEN a milestone modal is opened
WHEN I select the milestone type
THEN I see list of fields associated with this Milestone

**Comment by maria-kuzmenko** [comment]
References for Single and Multi-select dropdowns can be found here - https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=789-812&mode=design

**Comment by maria-kuzmenko** [comment]
References for Add Milestone Modal and its appearance based on Milestone Type can be found here - 
https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=1030-1893&mode=design

**Comment by maria-kuzmenko** [comment]
@dinesh-aot should this first go into UX review? 
@Connor1892 , please do not close this one

**Comment by maria-kuzmenko** [comment]
1. Can we change the size to Medium - 680 px. width?

**Comment by maria-kuzmenko** [comment]
2. My bad, can we have a reverse count starting from 150/150 characters left. Please add 's' to character

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFFiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96338f3fc16b67efa323644703e0163c628240e3/Screen%20Shot%202023-10-09%20at%207.29.19%20PM.png)

**Comment by maria-kuzmenko** [comment]
3. Delete button on hover should not change its size and have a hover effect of the Info button - https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=500-9476&mode=dev

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFliQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac1e4f1a6af21d21a7eb144b32912f616e24d0d4/Screen%20Shot%202023-10-09%20at%207.32.18%20PM.png)

**Comment by maria-kuzmenko** [comment]
4. Links do not work in the Notes part while being shown in the grid
5. **All notes disappear if I make any changes on Milestone modal**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGNiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1b5ec24cdf631828c6c162a69809124769c1562/Screen%20Shot%202023-10-09%20at%207.33.33%20PM.png)

**Comment by maria-kuzmenko** [comment]
not all fields for some types of milestones and weird grid behaviour + numerical values for text values

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVliQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bda29ff5b78d97ef9d9e46aadfcb7825b2cbf526/Screen%20Shot%202023-10-09%20at%207.46.05%20PM.png)

**Comment by maria-kuzmenko** [comment]
edit Milestone modal should have a different title

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWNiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e4448cfcac1573b56f7bc290b7dfb3a8101fd1f/Screen%20Shot%202023-10-09%20at%207.47.44%20PM.png)
