### ISSUE TITLE
Task Template - Task Templates available alert

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#878]
**As a** user

**I want** to know if there are available templates for this phase of my work

**so that** I can choose if I want to use one of them

### Scenario 1: 

GIVEN the workplan page is open
WHEN I open a phase
     AND there has not been a task added
     AND there are templates available 
THEN I will see an alert that says:

Task Templates are available!
Do you want to preview available Templates?
(Icon) Preview Templates (Ghost)

### Scenario 2:

GIVEN the Task Template alert is up
WHEN I select Preview Templates
THEN I see the available templates modal

### Screenshot 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcW80IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0c7d51e97f455bfe8e75aecbdd386a0a5d5914cf/Screen%20Shot%202023-08-24%20at%204.16.30%20PM.png)

**Comment by Connor1892** [comment]
system vs session
active button vs inactive button vs pop-up (convo needed)

**Comment by Connor1892** [comment]
@maria-kuzmenko new screenshot needed

**Comment by maria-kuzmenko** [comment]
@Connor1892 , added a new screenshot - a button with the icon - too much with the information icon - should be enough this way :(

**Comment by maria-kuzmenko** [comment]
@dinesh-aot, 
- when they press 'Preview Templates' button - we should hide the alert - there should not be two of them together.
- all of our alerts should have 4px border-radius - if we don't have it on others, we might not bother for now

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTUwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--358d7937867f231864c85927ba5edab47e856f65/Screen%20Shot%202023-09-06%20at%205.51.34%20PM.png)

**Comment by maria-kuzmenko** [comment]
- A popup appears even when the task is added - the button should be disabled and info window should not appear

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjEwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--61513f506f80b9a1e6cc7e3ea96607bef202c894/Screen%20Shot%202023-09-06%20at%206.12.11%20PM.png)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot, uploading lock icon here 

color: #C2C4C5 (Neutral/Accent/Light)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFoxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e219b201af5a1689b063c259a749c9d5e39757f8/lock.svg)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot , can we customize the text for the notification to let them know which phase those template belongs to?
OR **(second option is way better as nobody reads)**
If the other phase is opened, the notification for the one that is closed disappears automatically, and if there is a template for the phase that is opened, the popup appears - basically to tie popup to the phase, so they won't accidentally click on smth else?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1dJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7e14c8fd8d8c7431bac08629a662ec649d14a98f/Screen%20Shot%202023-09-11%20at%2010.10.36%20AM.png)
