### ISSUE TITLE
Task Template - Select Template Modal

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#879]
**As a** user

**I want** to be able to preview all the available template options

**so that** I can pick the best option for my team

### Scenario 1: 

GIVEN the task Template modal is opened
WHEN I click on an option from the left menu
THEN I see the list of tasks associated with it on the right and the number of tasks above it.

### Scenario 2:
 
GIVEN I have clicked on an option from the left menu
WHEN I select Get Template button (Primary)
THEN I see a confirmation warning with the following text:

Upload this Template?
(---)
Once uploaded, Templates will be locked for this Phase.
No (ghost) Upload (Primary)

### Scenario 3:

GIVEN the confirmation message is opened
WHEN I select upload option
THEN the tasks from the template are inserted into the workplan

### Validation Rules? 

(If yes, list here)

### Screenshot 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1lJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bce06a43e6b7fb70eabc4b32d7736629240f0bf2/template%20modal2.PNG)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2dJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f2dc9ffe09412db1f6e18989aaac87a48cff139f/template%20modal3.PNG)

**Comment by Connor1892** [comment]
all days (length) are set to 1 day regardless of what number is in the template file

**Comment by maria-kuzmenko** [comment]
1. Can we fix the right side and scroll only the list with Tasks?
2. The divider for the buttons should be visible all the time

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1V2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5db02fdf7ec80672f95f68854bfe25bd792901ff/Screen%20Shot%202023-08-23%20at%2010.23.40%20AM.png)

**Comment by maria-kuzmenko** [comment]
Minor fixes:
- all corners for the selected option should be 4px 
- Can we get rid of 8px margins top bottom? (green), so the text would be almost at the same level as the right part
- List of Tasks and Indicator should be vertically aligned 
- The number of tasks should be wrapped up the same way we did for Teams and First Nations (examples attached)


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEF2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--20b704991c740040adfae370e1a71dfcb0edd048/Screen%20Shot%202023-08-23%20at%2010.25.25%20AM.png)

Examples
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEl2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6bbe711bd627bcd8633816fd8c3fcea5998743a4/Screen%20Shot%202023-08-23%20at%2010.27.33%20AM.png)

**Comment by maria-kuzmenko** [comment]
verbiage fix - no ? at the end of the sentence 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFV2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--51ea95ff0b791c29d1a4bf23d6e891500c9eb2d0/Screen%20Shot%202023-08-23%20at%2010.28.20%20AM.png)

**Comment by maria-kuzmenko** [comment]
Hover items - need to fix the style

NOW
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDR2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5dfe986832fd8e7dc18c1ee671e63753d18bc45a/Screen%20Shot%202023-08-23%20at%2010.39.51%20AM.png)

Should be
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDh2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7a4a94fd8cad737f47388f901085ef772aee8ea4/Screen%20Shot%202023-08-23%20at%2010.40.26%20AM.png)

background-color: rgba(73, 73, 73, 1);
    border-radius: 4px;
    color: rgb(255, 255, 255);
    padding: 4px 8px;
    font-size: 0.75rem;
    max-width: 300px;
    margin: 2px;
    overflow-wrap: break-word;
    font-weight: 400;
    line-height: 16px;
    text-align: center;

**Comment by maria-kuzmenko** [comment]
Need to fix colors 
1. Hover - rgba (240, 248, 255, 1) - Primary Background Light
2. Selected - rgba (214, 235, 255, 1) - Primary Background Main

The only thing I don't like, is when you hove over the selected - really weird color combination :( 

**NOW**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWt2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a3e182f94ee2df27a3d1c837e3ed98769159b116/Screen%20Shot%202023-08-23%20at%2010.49.41%20AM.png)

**When changed**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjB2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b859e74040939ce747fe8cf178924c9ebcf57127/Screen%20Shot%202023-08-23%20at%2011.05.50%20AM.png)

**Hover option on selected**
[Uploading... Screen Shot 2023-08-23 at 11.12.04 AM.png]
