### ISSUE TITLE
Team Tab - user view

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#881]
**As a** user

**I want** to see high level information about the team and be able to add team members

**so that** I can assign Fraser Tasks

### Scenario 1: 

GIVEN I am on the Team tab for my work
WHEN there is no one assigned to the work
THEN I see the following text:

You don't have any Team Members yet
Start adding your team

+ Team Member (Primary)

### Scenario 2:
 
GIVEN I am on the team tab
WHEN I select the add Team member button
THEN I see the add team modal

### Scenario 3:
 
GIVEN I am on the team tab
WHEN I look at the right side
THEN I see high level team information (as seen below)

### Validation Rules? 

(If yes, list here)

### Screenshot 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEVJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--de1a3eef13ee448bbc5987c5fcd0ec3c79d4c55f/Team%20tab%20-%20user1.PNG)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot , folder icon

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamFDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--84abc798c1c622f6a16207d36db1770ec6e3559f/folder%20icon.svg)

**Comment by Connor1892** [comment]
on my laptop screen, the grid is too wide and gets cut off.

we should probably shrink the name column width to length of longest name, or allow email to be concatenated more to allow Active to show.
we could also shrink the Team info section on the right slightly?

Which is best @maria-kuzmenko

**Comment by maria-kuzmenko** [comment]
@Connor1892 , can you upload your screenshot? I have a different resolution

**Comment by Connor1892** [comment]
![image](https://github.com/bcgov/EPIC.track/assets/126211473/ea2437e2-7e87-4ea2-9082-99f98c36deaa)

**Comment by maria-kuzmenko** [comment]
yeah, I think, we can't do anything about it for now - that's a different screen resolution, so we'll see what they're using first to understand whether we need to adapt designs to different viewports 
@dinesh-aot
