### ISSUE TITLE
Team Tab - Team Member Modal

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#883]
**As a** user

**I want** to be able to select staff

**so that** I can add them to a work

### Scenario 1: 

GIVEN the add team member modal is open
WHEN I select search for a name field (typeahead)
THEN I can see the list of active staff to choose from

### Scenario 2:

GIVEN the name field is opened
WHEN I have selected a staff member to add
THEN I will see the following information populated by the system (label fields):

Email
Phone number

THEN I see role dropdown
THEN I see Active/Inactive Toggle (Active set as default)

### Validation Rules? 

(If yes, list here)

### Screenshot 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDBJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5b29cd09f8e1702abca2f2b3040efb36a8fdbf3a/Team%20Tab%20-%20modal1.PNG)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDRJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--43372852fc7754f74f1fbf2d318c1c0434855465/Team%20Tab%20-%20modal2.PNG)

**Comment by maria-kuzmenko** [comment]
1. Font is different - should be H4/Bold - Font size: 1.25 em (20px)
2. Somehow margins are different as the modal itself has additional width, so they are misaligned
3. Background for the main information should be #F9F9FB
4. This control is probably from MUI as different icons, stroke font and font family
5. Can we make the Add button the same size as Cancel? Doesn't look good that narrow, harder to press

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2VaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--da250d89cc29ea9227e366c34d06b15477e2092b/Add%20Team%20Member%20modal.png)

**Comment by maria-kuzmenko** [comment]
dropdown fields should have same style as custom ones 
border: 2px solid var(--neutral-100, #DBDCDC)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUx4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2a63014551ef86eda08a9809f3f2219e3088dcb7/Screen%20Shot%202023-09-29%20at%201.34.29%20PM.png)
