### ISSUE TITLE
Team Tab - Grid

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#884]
**As a** user

**I want** to see the full list of people assigned to my work

**so that** I can understand the scope of the team

### Scenario 1: 

GIVEN I have selected a team member on add team member modal
WHEN I press add button
THEN I see them in a grid with the following information:

- name (search filter)
- role (select filter)
- email (search)
- phone (search)
- status (select)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUlJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0667f8ac6c82ae73574b292a6831d696ae7721ab/Team%20tab%20-%20user2.PNG)

**Comment by maria-kuzmenko** [comment]
1. Wrong font for the Title - should be H3/Regular - font size 1.5 em (24px), Line height: 32 (1.3)
2. There should not be the 'x' icon for the default search filter behaviour - it appears only when the user starts typing to help them erase. We can either show nothing or 'search' icon. (including both)
3. Icon size as well as colors are wrong, which creates different margins for search and filter dropdowns
4. Search text should be the same color as Filter (couldn't check, but they look like different fonts)
5. For all Ingrid options if those are not milestones - they should be font-weight 400 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGlaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cb161dfd7771d91eb1ff9f268a9b72ed00d241ad/team%20tab_grid.png)

**Comment by maria-kuzmenko** [comment]
**icons**

close icon - [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUdaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ce2fd4041fccefdcf538305c724119064b02d7f4/16.svg)
search icon - [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVNaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--76ea913f7973ea9e1d7a535b06bd22c7e0039bcc/16.svg)

**Comment by maria-kuzmenko** [comment]
This hover effect might have come from the MUI, we need to redo the Search filter as it has lots of MUI stuff, we do not need the hover over clear icon

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTJaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--abc89eb954573c39a8f40e66a9824e411f80a6c2/hover.png)

**Comment by maria-kuzmenko** [comment]
Don't know whether it is in testing environment, doesn't show filter options

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbStaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d26ca2b46710ab10d3a0024cf5e2ed0f42cbe6a7/Filters.png)

**Comment by maria-kuzmenko** [comment]
Can we do the same highlight on the Names as well?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkNaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--49bf6155ceb012033c57ca31dfeb9a5be48ad9e9/search.png)

**Comment by maria-kuzmenko** [comment]
We need to truncate Filtered do prevent it from jumping on another line

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmVaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7ca357fa601998f21437f8dcdb1427171c42baa7/broken.png)

**Comment by maria-kuzmenko** [comment]
Don't know whether it is a bug, but I tried selecting just 'Active' and it keeps selecting 'Inactive'

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmlaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5e65e01a7a1bf9c629dfadca5606c699f709df34/bug_.png)
