### ISSUE TITLE
Nation Tab - empty

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#885]
**As a** user

**I want** to see when the work doesn't have any nation

**so that** I can start adding one

### Scenario 1: 

GIVEN Nation tab is open
WHEN there is no Nation assigned to the work
THEN I see the following text in the middle:

You don't have any First Nations yet
Add Nations or Import them from existing Works

+ Team Member (Primary) Import Nations (Ghost)

### Scenario 2:
 
GIVEN Scenario 1
WHEN I look at the right side
THEN I see 2 tabs:
- Notes (rich text) - Active
- high level information relating to Nations (as seen below) - Inactive

### Scenario 3:

GIVEN Scenario 1
WHEN I click on 'Resources' tab
THEN I see list of helpful links
- Link to Consultative Areas Database (CAD) (with the link) and explanation 'A version of iMapBC that allows users to view First Nation territorial and reserve boundaries, as well as cultural, heritage, and traditional use sites.'
- Link to Profile of Indigenous Peoples (PIP) (with the link) and explanation 'Resource for contact information, consultation advice, and consultation area maps for Indigenous Peoples in BC and neighbouring regions.'
- Link to Agreement, Rights and Title System (ARTS) (with the link) and explanation 'Database of agreements between Indigenous organizations and the government and Indigenous organization's established rights or title as decided by a court.'
- Link to E-Guide (with the link) and explanation 'EAO procedural information, templates, policies and guidance for all aspects of the 2018 Environmental Assessment process.'
- Link to Consultation Guide (C-Guide) (with the link) and explanation 'Information, guidance and tools regarding the government's section 35 consultation obligations.'

### Screenshot Scenario 1-2
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2pzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e69bdef3d7799724999a994e4b03964cf11a1b62/Screen%20Shot%202023-09-28%20at%202.36.48%20PM.png)

### Screenshot Scenario 3
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ25zIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f32488a01e67cbd74fe24db028c50f69fd2cede9/Screen%20Shot%202023-09-28%20at%202.37.11%20PM.png)

**Comment by maria-kuzmenko** [comment]
@salabh-aot 
Link to prototype

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/For-Development?type=design&node-id=3890-83340&mode=design

Import Icon
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaExzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bb7bfd8e415e15e897735a5ac1e6efc7398396bc/file-import-bold.svg)

**Comment by maria-kuzmenko** [comment]
Links to FN Resources

[Links for Resources (FN).xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1VGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ca6b96fc36e40eebc5679f8dd8b7905eb1fdeec/Links%20for%20Resources%20%28FN%29.xlsx)

**Comment by dinesh-aot** [comment]
Notes are not getting reloaded. @salabh-aot

**Comment by carlygreenehill** [comment]
The Notes Tab is active, rich text works and is there, and auto save is working. The typing cursor gets sent back to the beginning randomly (I think it's everytime the auto save happens. The Notes section is also kind of hard to tell where it begins and ends. Happy to close this ticket and open a bug. 

The note is saving though :) I also hear that these considerations are being addressed in #797 - brava!

![image](https://github.com/bcgov/EPIC.track/assets/101662408/c7f89b71-ecde-4be3-a090-b5eed7541d75)

**Comment by maria-kuzmenko** [comment]
@carlygreenehill we can close this one, as Jad and I will work separately on enhancements for all right text notes - they need to have a proper style and identifiable borders as now both on Modals and here they are not ideal. 

I think we have a separate ticket for it, working on it. Will grab those comments there as well in order not to lose it. 
Thanks, Carly, excellent catch!
