### ISSUE TITLE
Nation Tab - Add Nation Modal

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#886]
**As a** user

**I want** to be able to add a Nation

**so that** I can add them to a work

### Scenario 1: 

GIVEN The Nation Tab is open
WHEN I click on 'Add Nation' button
THEN 'Add Nation' Modal appears with the following fields

- Nation with dropdown (mandatory)
- Relationship holder with ghost text 'Relationship holder' (disabled)
- PIP link with ghost text 'Link' (disabled)
- PIN with dropdown ('Yes'/'No') and ghost text 'Select / Confirm PIN Status'
- Toggle (active by default)

### Screenshots:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHZzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--91903ceae4db06ae78f70aebba14defaef742b90/Screen%20Shot%202023-09-28%20at%202.58.06%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHpzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--082a49a84806364146c968ad8724b09dc2995ca0/Screen%20Shot%202023-09-28%20at%202.58.16%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDdzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--02314f4aee27ed2ff1b9db09a22d3e9627584ab5/Screen%20Shot%202023-09-28%20at%202.58.46%20PM.png)

**Comment by Connor1892** [comment]
Pin Status may be changed to "Pending", "Confirmed", etc.
not confirmed yet.

**Comment by maria-kuzmenko** [comment]
@salabh-aot 

link to prototype
https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/For-Development?type=design&node-id=3890-83994&mode=design

**Comment by salabh-aot** [comment]
@maria-kuzmenko @dinesh-aot The `Work` -> `IndigenousNation` mapping table have a foreign key relation with `IndigenousCategory`, but the field for it is not present in the design.
