### ISSUE TITLE
Nation tab - Grid

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#887]
**As a** user

**I want** to see the full list of Nations assigned to my work

**so that** I can understand the scope of the Work

### Scenario 1: 

GIVEN Add Nation is open and all the information is filled in
WHEN I press add button
THEN I see them in a grid with the following information:

- nation (search filter)
- role (select filter)
- relationship holder (search)
- PIP (search)
- status (select)

THEN above the grid I see 
- '+ Add Nation' Primary button to the left
- Import Nation Button, Download Button, and the Pagination options to the right

### Scenario 2: 

GIVEN Nation Tab is open and grid is there
WHEN I hover over an avatar near name of the relationship holder
THEN I see information about that person

### Scenario 3: 

GIVEN Nation Tab is open and grid is there
WHEN I press Import Nation button
THEN I see Import Nation modal

### Scenario 4: 

GIVEN Nation Tab is open and grid is there
WHEN I press Download Nation button
THEN Nations in the list is exported in .xlx format

### Scenario 5: 

GIVEN Nation Tab is open and grid is there
WHEN I click on Nation's name
THEN I Nation Modal is open with the following changes to the title

- 'Nation Name' as a title

### Screenshots

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWpzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fff99b511b8905d477d8f69813042fa8eb69fd53/Screen%20Shot%202023-09-28%20at%203.08.47%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaW5zIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9987cadb391dc99f63d08a46748c21299368db9a/Screen%20Shot%202023-09-28%20at%203.08.58%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanZzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--061d5629f5ab607003591fcb2ab495fd4cf3c2f5/Screen%20Shot%202023-09-28%20at%203.27.02%20PM.png)

**Comment by maria-kuzmenko** [comment]
@salabh-aot 

link to the prototype
https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/For-Development?type=design&node-id=3890-84700&mode=design

**Comment by dinesh-aot** [comment]
@salabh-aot 
Indigenous Nations in list management should be first nations
Saved notification for the notes all the time for every focus changes
Editing not working
If no nations to import, just disable the button
Import nations button also has to be disabled if there is nothing to import
Show the active ones count in the chip in the tab
Clear Button Style
import nations from the empty tab is  not working

**Comment by maria-kuzmenko** [comment]
have additional margins for Resources - should get rid of them to mirror the same view as for the Team tab

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjgxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2744279cbbc6805e98414a63b230afb34800db4d/nations-comments.png)

**Comment by maria-kuzmenko** [comment]
Inactive Nations are in the list, so the user can select them without knowing they are inactive. However, when they try to add them, it won't give any message, so it is unclear why this happen. 

**we should not show inactive nations in the list**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0kxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82cb254a31e4130eb86c8fe4e4f24b23368ddbac/Screen%20Shot%202023-10-13%20at%2011.27.30%20AM.png)

**Comment by maria-kuzmenko** [comment]
We should make only avatar on hover as having the whole cell on hover prevents to copy information from the card as it immediately jumps to show the next avatar's credentials

[Uploading... Screen Shot 2023-10-13 at 11.43.25 AM.png]

**Comment by maria-kuzmenko** [comment]
Text on Hover for importing should be 'Import Nations from existing Works'

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFE5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad62b8b682b359eb4e7225a3d154376a6982e4a7/Screen%20Shot%202023-10-16%20at%2010.19.05%20AM.png)

**Comment by Connor1892** [comment]
when downloading the Nations list from Scenario 4, the file is called Ajax mine even though that is not the Work I am on.
