### ISSUE TITLE
Nations Tab - Import Nations Modal

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#888]
**As a** user

**I want** to import Nation from other Works

**so that** I can save time

### Scenario 1: 

GIVEN Nation Tab is open 
WHEN I click 'Import Nation' button
THEN I see the 'Import Nations' modal with the following fields

(left part) 
- All Work Types with the number of unique nations in the list (selected by default)
- List of all Works associated with this Project

(right part)
- Title of the selected option
- 'Select Nations to import' text with '0' identifier
- checkboxes with 'Select all' option at the top and all unique nations

'Clear Selection' button 
'Import' primary button
'Cancel' secondary button

### Scenario 2:
 
GIVEN Import Nation modal is open
WHEN I click on an option from the left menu
THEN I see the list of nations linked to this work

### Scenario 3:

GIVEN Import Nation modal is open and nations are selected
WHEN I click on 'Clear Selection'
THEN all checkboxes become unchecked

### Scenario 3:

GIVEN Import Nation modal is open and nations are selected
WHEN I click 'Import' button
THEN Nations are imported into the grid

### Screenshot 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakhzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a84412beb0cd9dd60c200666b83ce128ad05f0f3/Screen%20Shot%202023-09-28%20at%203.23.53%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalBzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--253014d2ab97230fdbf1ae2d3a6095904d0040d0/Screen%20Shot%202023-09-28%20at%203.24.06%20PM.png)

**Comment by maria-kuzmenko** [comment]
@salabh-aot 

link to prototype
https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/For-Development?type=design&node-id=3908-85772&mode=design

**Comment by salabh-aot** [comment]
@maria-kuzmenko  any suggestions on what to do when there is no Work types or first nations to import?

**Comment by maria-kuzmenko** [comment]
@salabh-aot, when there are no nations to import, the 'import nations' button would be disabled
