### ISSUE TITLE
Workplan Page - Bulk Actions

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#900]
**As a** User

**I want** do bulk actions 

**so that** I can apply the same parameters to multiple tasks/milestones

### Scenario 1: 

GIVEN Workplan page is opened with tasks in it
WHEN I select Tasks OR/AND Optional Milestones (individually or by clicking on 'select all' checkbox)
THEN I will see the following information appear to the right of 'Add Milestone' button 

- number of selected items in the format 'x selected'
- separator with 8px margins left and right
- 'Assign To' Information button with a dropdown icon
- 'Responsibility' Information button with a dropdown icon
- 'Progress' Information button with a dropdown icon
- 'Delete' Information button

### Scenario 2:
 GIVEN Tasks OR/AND Optional Milestones are selected
WHEN I click on 'Assign to' Information button
THEN I see a **multi select** with a list of Team members derived from Teams Tab with 'Apply' and 'Cancel' buttons

### Scenario 3:
 GIVEN Tasks OR/AND Optional Milestones are selected
WHEN I click on 'Responsibility' Information button
THEN I see a **multi select** with a list of Responsibility roles with 'Apply' and 'Cancel' buttons

### Scenario 4:
 GIVEN Tasks OR/AND Optional Milestones are selected
WHEN I click on 'Progress' Information button
THEN I see a single select with radio button for the following options and in the following order
- Not Started
- In Progress
- Complete
With 'Apply' and 'Cancel' buttons

### Scenario 5:
 GIVEN Tasks OR/AND Optional Milestones are selected
WHEN I click on 'Delete' Information button
THEN I see a confirmation popup saying 'Are you sure you want to delete this?' with buttons 'No' and 'Yes'

Screenshots

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1FxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--566a28f70b4ac077619db0cae374acef78ec4b37/Screen%20Shot%202023-08-22%20at%202.54.44%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1VxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fbbda3e6663de62e29810ed785d531c7a3d3b7b9/Screen%20Shot%202023-08-22%20at%202.55.03%20PM.png)

**Comment by Connor1892** [comment]
@maria-kuzmenko

**Comment by dinesh-aot** [comment]
@salabh-aot 
- Edit task not working
- Perform deletion by selecting one task and optional milestone. The selection count and delete button keep visible and you can perform deletion many times. You will need to refresh to get the selection gone.
- Select a task, try to select responsibility, the selection not working. same for progress if you click on the radio button. It works when you click on the text.
- Responsibility is not loading in to the grid. 
- When you perform an action, the list should be unselected.

**Comment by maria-kuzmenko** [comment]
@salabh-aot , @dinesh-aot 

AC for Scenario 3 and Scenario 5 do not work as they should based on the acceptance criteria
- there should be a multiselect for Responsibility dropdown
- there should be a delete confirmation window after the delete button is pressed

**Comment by maria-kuzmenko** [comment]
@dinesh-aot , 

documenting it there - All Milestones are greyed out and are unable to choose for the bulk operation

**Comment by maria-kuzmenko** [comment]
There are duplicates in the list - the list loads also those users that are inactive - we should restrict to show only the list of active users.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejhiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5d8be651759105e7f2d3a70d94d70951acd80d1/Screen%20Shot%202023-10-09%20at%207.12.33%20PM.png)

**Comment by maria-kuzmenko** [comment]
UI needs some polishing up:

- all buttons for bulk actions are Info Buttons and should have the following states - https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=500-9476&mode=design
- space between icon and text in the button - 8px (now assign to, responsibility, progress have way bigger space)
- there is a movement while pressing the button - probably, because the size is not 40px - should be 40px on active state as well

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME1iQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4aeea708f803da39f8447817285c9caf7887ad2d/Screen%20Shot%202023-10-09%20at%207.23.50%20PM.png)

**Comment by maria-kuzmenko** [comment]
For Progress radio check boxes should be the same color as the text - #1A5A96

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEliQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6eba99c1e6e2a9ba2e2c8376050fbc12476acf83/Screen%20Shot%202023-10-09%20at%207.22.46%20PM.png)

**Comment by salabh-aot** [comment]
@maria-kuzmenko  
>     * all buttons for bulk actions are Info Buttons and should have the following states - https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=500-9476&mode=design

This applies to `Delete` button as well? or other buttons only?

**Comment by maria-kuzmenko** [comment]
@salabh-aot , applies to all buttons including Delete as well, thanks! :)

**Comment by carlygreenehill** [comment]
Looks good! - CGH
