### ISSUE TITLE
Create Template - no automatic reload

### ISSUE THREAD

**Issue by maria-kuzmenko** [bcgov/EPIC-FLOW#904]
**As a** User

**I want** see the added templates right away

**so that** I can see what I've added

### Scenario 1: 

GIVEN Template tab is open and I filled in Tab's all required fileds
WHEN I pressed 'Add' Button
THEN see the new created template in the grid

Current view for a newly added template "Test Template" - need to manually reload to see it
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGN4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--25e6c2235296ab75afa57cc0bb3063da2b8f20b8/Screen%20Shot%202023-08-23%20at%209.59.36%20AM.png)

**Comment by Connor1892** [comment]
this bug is still active. I get the notification that a template has been added, but it's still not appearing in the list.

Is there a way to force a reload of just the grid component?
