### ISSUE TITLE
Issues Tab - First Issue

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#921]
**As a** team member

**I want** to add a Issue to my Work

**so that** I can populate Reports

### Scenario 1: 

GIVEN I am on the Issues Tab
WHEN I click the Add Issues Button
THEN I see the Add Issues Modal with the following:
- Title (Add Issue)
- Title Field (text field) (required) (50 char limit)
- Description (Text box) (250 character limit) (Required)
- Active toggle (on by default) (hoverstate is: "Issue must be Active to appear on reports")
- High Priority toggle (hoverstate is: "Issue must be High Priority to appear on 30-60-90")
- Start Day (date picker) (required)
- Expected Resolution Day (date picker)
- Save (Primary)
- Cancel (Ghost)

### Scenario 2:

GIVEN Add Issues modal is open
WHEN I click on save button
THEN I see the Issues Accordion with the following:
- Issue Title
- Last update Date
- status
- Issue box
    - Date
    - Tags ("Need Approval") 
    - Issue text
    - Approval button
    - Edit button

### Scenario 3:

GIVEN An Issue is not approved
WHEN I press the edit button
THEN I see the Edit Issue Modal with the Description active

### Scenario 4:
 
GIVEN I am on the Issues tab
WHEN I have the Report Preview tab open
THEN I see the following:
- refresh button (ghost)
- Report Preview panel
    - Status
    - preview box (with text: "Once approved, Issue will appear here" (ghost text))

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
link to prototype

https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus)?type=design&node-id=4771-10105&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/921?planning-poker) with Zenhub @TomChapmanGov @jadmsaadaot @saravanpa-aot

**Comment by maria-kuzmenko** [comment]
checking the UI for this one - the functionality of adding an issue will be done further on - this is a dummy data

@jadmsaadaot 
- color for the date and issue text - #313132 

- font for the date
/* Caption/01/Bold */
font-family: BC Sans;
font-size: 13px;
font-style: normal;
font-weight: 700;
line-height: 16px; /* 123.077% */
letter-spacing: 0.39px;
text-transform: uppercase;

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot 

icons for edit, clone, and approve

[Private Zenhub Image]
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWU0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3c309032066f69f7a922684a7e5c6c1142eddc3/check-circle-regular.svg)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWk0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--782405c345081bb0af01a9188f18e177101e25c1/clone-regular.svg)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW00QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ab7bb6f4d070016bf5d255fe94d0745c555f4d0/edit-regular.svg)

**Comment by jadmnsaad** [comment]
@maria-kuzmenko Thanks, the tweaks you raised will be address in https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/922

**Comment by Connor1892** [comment]
all works in test seem to have the same 2 issues and while I can bring up the Add Issue modal, I cannot add new ones.
the issues that are there cannot be approved, and do not show on the reports previews.

**Comment by maria-kuzmenko** [comment]
@Connor1892, approved issues is another ticket - this is dummy data to check the UI changes and the grid. 
all this will be covered in #922
