### ISSUE TITLE
Issues Tab - Approved Issue

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#922]
**As a** user

**I want** to approve an Issue

**so that** it will appear on reports

### Scenario 1: 

GIVEN I am on the Issue tab
WHEN I click on the Approve button of a "Needs Approval" Issue
THEN I see a confirmation Modal with the following:
- Title (Approve this Issue)
- Once approved, this Issue will be automatically added to the Report
- Confirm (Primary)
- Cancel (Ghost)

### Scenario 2:

GIVEN approve this Issue Modal is open
WHEN I click confirm
THEN I see the Issue box update to the following:
- Date
- Tags ("Approved")
- Issue text
- Clone button

THEN I won't see Exclamation icon next to the 'Issues' tab

### Scenario 3:
 
GIVEN I am on the Issue tab
WHEN I have the Report Preview tab open
THEN I see the following:
- Issue
- Date (when Issue was approved)
- preview box (with most recently approved Issue)

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot 
icons for Edit buttons 

1. Default
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEYxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ae8733031448525fe7b0fb943f97c25ccbcbf93e/edit.svg)

2. Hover
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEoxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--034027232684c506ea12b723fa1d7fb59ff549b4/edit-bold.svg)

**Comment by maria-kuzmenko** [comment]
link to prototype

https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus)?type=design&node-id=4771-11359&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/922?planning-poker) with Zenhub @TomChapmanGov @jadmsaadaot @saravanpa-aot
