### ISSUE TITLE
List Management - Add Nations Modal

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#925]
**As a** user

**I want** to add a Nation to the Nations List Page

**so that** I can live my life

### Scenario 1: 

GIVEN First Nation tab within List Management is open
WHEN I click the 'Create First Nation' button
THEN I see 'Add Nation' Modal

- Name (Text Field)
- Relationship Holder (Dropdown)
- PIP Organization Type (Dropdown) (See Comments)
- PIP URL (Text field)
- Notes (Rich text editor)
- Active (Toggle)
- Buttons 'Cancel' and 'Add'

### Scenario 2:
GIVEN First Nation tab within List Management is open
WHEN I click on any nation's name
THEN I see a 'Edit Nation' Modal 

and buttons 'Cancel' and 'Save'

### Screenshot 

![image](https://github.com/bcgov/EPIC.track/assets/126211473/b7008aba-a406-4b69-b68b-dca35d4de4f4)

**Comment by Connor1892** [comment]
PIP ORG Types:

- Clan
- First Nation
- First Nation Group
- House
- Keyoh
- Metis
- Tribal Council
- Wilp

**Comment by maria-kuzmenko** [comment]
@TomChapmanGov 

When creating a Nation, Active should be by default on

**Comment by Connor1892** [comment]
@maria-kuzmenko should we have active toggle above notes?

Notes are usually the last thing on a modal and on the standard screen size it can get lost under the notes.

**Comment by maria-kuzmenko** [comment]
@Connor1892 agree! complete missed that one. 
@TomChapmanGov , can we move that blue guy up before notes?
