### ISSUE TITLE
List Management - Filters fixes

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#926]
**As a** user

**I want** to be able to filter and search my workplans

**so that** I can live my life

### Scenario 1: 

GIVEN I am in List Management 
WHEN I open any page
THEN I see the following filtering options above the grid:

Staff:
- Name (search)
- Number (search)
- email (search)
- position (multiselect)
- active (multiselect) **!this should be changed from a toggle to a proper select with Select all, Active, Inactive options)**

Nation:
- Name (search)
- relationship holder (multiselect)
- active (multiselect) **!this should be changed from a toggle to a proper select with Select all, Active, Inactive options)**

Proponents:
- Name (search)
- relationship holder (multiselect)
- active (multiselect) **!this should be changed from a toggle to a proper select with Select all, Active, Inactive options)**

Projects:
- Name (search)
- type (multiselect)
- subtype (multiselect)
- region (multiselect)
- active (multiselect) **!this should be changed from a toggle to a proper select with Select all, Active, Inactive options)**

Work Staff 
- Name (search)
- work title (multiselect)
- team (multiselect)
- EPD (multiselect)
- lead (multiselect)

**Comment by Connor1892** [comment]
@maria-kuzmenko pls confirm these for filter types
@Connor1892 , done

**Comment by jadmnsaad** [comment]
Duplicate
