### ISSUE TITLE
Create Work - Project list order

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#929]
---
project list should be alphabetical when creating a new work

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by carlygreenehill** [comment]
The project list appears to bee alphabetical when creating a new work! Well done!
