### ISSUE TITLE
All works page - Filter by ministry

### ISSUE THREAD

**Issue by TomChapmanGov** [bcgov/EPIC-FLOW#954]
---
On all works page when selecting a ministry to filter, it filters by title and not acronym so it does not show any works.

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
show short names in both filter and column

**Comment by Connor1892** [comment]
select all is coming in Jad's card 1074 so this is perfect
