### ISSUE TITLE
Work staff page - Not recognizing soft delete

### ISSUE THREAD

**Issue by TomChapmanGov** [bcgov/EPIC-FLOW#958]
---
Work staff still shows after work has been deleted.

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
might not be needed if we're rebuilding the Work-Staff page from ground up
