### ISSUE TITLE
Staff page - Searching staff by full name

### ISSUE THREAD

**Issue by TomChapmanGov** [bcgov/EPIC-FLOW#964]
**As a** user

**I want** to be able to search by full name

**so that** I can find the staff member

### Scenario 1: 

GIVEN I am on the staff page
WHEN I search for first name last name
THEN I see the staff member

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
sorry @TomChapmanGov.
it's not a thing
