### ISSUE TITLE
Template page - Delete confirmation modal

### ISSUE THREAD

**Issue by TomChapmanGov** [bcgov/EPIC-FLOW#965]
---
Delete confirmation is different than rest of site.
It is the only modal that does not say 'Cancel' (Ghost) and 'Delete' (Primary)
---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Onaivio** [comment]
1. Design: Choose a distinct color scheme, style buttons differently, use clear typography, and incorporate icons for visual cues.

2. Interactions: Apply hover effects to buttons, create smooth modal opening/closing animations, and offer immediate feedback on button interactions.

3. Modal Component: Develop a reusable modal component that accepts customization props like `isOpen`, `onConfirm`, `onDismiss`, and `confirmationText`.

4. Code: Inside the modal component, render the modal structure with tailored styling, buttons, icons, and text. Use conditional rendering for different button labels based on modal type.

5. Testing: Thoroughly test the modal component in various scenarios to ensure proper functionality and appearance.

6. Documentation: Document how to use the modal component, including available props and their purposes.
