### ISSUE TITLE
Template preview modal - Double scroll

### ISSUE THREAD

**Issue by TomChapmanGov** [bcgov/EPIC-FLOW#966]
---
We should not have double scroll on this info modal.
Moved buttons to right of modal to match other modals and added primary button.

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
@TomChapmanGov
