### ISSUE TITLE
Update staff modal - Position field

### ISSUE THREAD

**Issue by TomChapmanGov** [bcgov/EPIC-FLOW#967]
---

Position dropdown has an 'X' and an arrow that do the same thing
REMOVE THE X!

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
@dinesh-aot the x now does something, but the modal cannot be saved while position is empty. so the x still has no purpose.
is there a reason I can't see why we want to keep the x? or is it hard to remove?
