### ISSUE TITLE
Reporting - Resource Forecast Rebuild

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#970]
---
rebuild Resource Forecast ONLY

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by dinesh-aot** [comment]
Consider work_phase_id instead of phase_id to get the min(event_configuration.id) in the phase_query @salabh-aot

**Comment by Connor1892** [comment]
The Resource forecast from formsflow had colour coded phases in the Q1 & Q2 columns. how much effort would it be to reimplement those?

![image](https://github.com/bcgov/EPIC.track/assets/126211473/fcb41fbb-a8ee-4bbb-915f-a6a7b161c901)
