### ISSUE TITLE
All Works - Grid View Chip widths

### ISSUE THREAD

**Issue by TomChapmanGov** [bcgov/EPIC-FLOW#972]
---
Active column has different widths.

Make Active chip the same width as the Inactive chip so they line up nicely.

This is needed on:
- All works page
- Templates page
- Staff page
- Indigenous page
- Proponents page
- Projects page
---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFcvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d9cd8ea26235e3da0ef98a63428e6e7760030048/image.png)

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
@TomChapmanGov is this still an issue?

**Comment by TomChapmanGov** [comment]
@Connor1892 No this is done
