### ISSUE TITLE
Teams page - Update team member modal

### ISSUE THREAD

**Issue by TomChapmanGov** [bcgov/EPIC-FLOW#974]
---
Says 'Add Team Member' when you are actually just updating a team member.
Button on bottom of modal to submit the form says 'Add', should be 'Update'

---

**As a** (type of user)

**I want** (goal)

**so that** (reason/ why/ value)

### Scenario 1: 

GIVEN ... (you or your condition)
WHEN ... (what you do)
THEN ... (what you see)

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by Connor1892** [comment]
edit modal should say save instead of ADD
the title of the modal should be the name of what you're editing.
applies to staff and nation tabs

**Comment by maria-kuzmenko** [comment]
@djnunez-aot, doesn't work like that based on this comment


Connor1892
commented 21 days ago
edit modal should say save instead of ADD
the title of the modal should be the name of what you're editing.
applies to staff and nation tabs
