### ISSUE TITLE
Edit Milestone Modals - Basic (1-day and Multiple days Milestones)

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#977]
**As a** user

**I want** to fill in all necessary fields for basic types of Milestones

**so that** I get all the needed information about them in the system

### Scenario 1: 

GIVEN Workplanpage is open with pre-populated Milestones
WHEN I click on the Milestone title
THEN Milestone Modal appears with the following fields:

**1-day Milestone**
- The 'Milestone Title' as the name
- The Type (Dropdown) (disabled)
- The Title (Text field: 150 char max)
- Description (Text field)
- High Priority (Toggle) with information tiptool
- Anticipated Date (Date Picker)
- Actual Date (Date Picker)
- Notes (Rich text editor)

**Multiple days Milestone**
Optional Fields (White)
- Number of Days (text field) (numbers restricted)
- End Date (calendar picker) (disabled)

### Scenario 2: 
GIVEN Workplanpage is open and an optional Milestone was added
WHEN I click on the Optional Milestone title
THEN Milestone Modal appears with the Delete information button

### Scenario 3: 
GIVEN Optional Milestone modal is open
WHEN I click on the Delete information button
THEN Delete confirmation window appears

### Scenario 4: 

GIVEN Scenario 1
WHEN I hover over the information tooltip
THEN I see the tooltip with the text 'High Priority Milestones will appear on reports'

### Screenshot 1-day Milestones
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2ZrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c1430d9e24b8b5a6fe4d170391737eae6f584b4c/Screen%20Shot%202023-09-27%20at%203.05.20%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2prIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--57b33632c4913e4955c5b968d9462b5ddfa35903/Screen%20Shot%202023-09-27%20at%203.05.39%20PM.png)

### Screenshot Multiple days Milestones
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc25rIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--40ceea8a3e56e93a69c5ec34c78f887f307e8e05/Screen%20Shot%202023-09-27%20at%203.05.57%20PM.png)

**Comment by maria-kuzmenko** [comment]
Link to Prototype

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/For-Development?type=design&node-id=3738-34955&mode=design

**Comment by maria-kuzmenko** [comment]
icon for information tooltip

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVRrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6b63947ac011d4c574a4865c9ac4a431030b34b0/circle-info.svg)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot , the only thing here - we need to have a tooltip for the High priority 

Scenario 4

**Comment by Connor1892** [comment]
Scenario 2-4 are good.
No milestone types are giving me the multi day options (Scenario 1b)
