### ISSUE TITLE
Edit Milestone Modals - Decision

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#978]
**As a** user

**I want** to fill in all necessary fields for Decision type of Milestones

**so that** I get all the needed information about them in the system

### Scenario 1: 

GIVEN Workplan page is open
WHEN I click on optional Milestone
THEN Milestone modal appears with the following fields:

- The 'Milestone Title'as modal title
- The Type (Dropdown) (disabled)
- The Title (Text field: 150 char max)
- Description (Text field)
- High Priority (Toggle)
- Anticipated Date (Date Picker)
- Actual Date (Date Picker)
- Notes (Rich text editor)

### Scenario 2: 

GIVEN Milestone modal is open
WHEN I put Actual Date
THEN following mandatory fields appeared

- Decision Maker (Dropdown)
- Decision (Dropdown)

### Screenshot Scenario 1
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDNrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8afce033ca0c709b3d72f8b0bbae81ef45366cf3/Screen%20Shot%202023-09-27%20at%203.19.24%20PM.png)

### Screenshot Scenario 2
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFBrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dd37ac2e5be2cc34c628a4b7de6acf63c32ace1d/Screen%20Shot%202023-09-27%20at%203.16.02%20PM.png)

**Comment by maria-kuzmenko** [comment]
Link to Prototype:

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/For-Development?type=design&node-id=3738-76822&mode=design
