### ISSUE TITLE
Edit Milestone Modals - PCP

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#979]
**As a** user

**I want** to fill in all necessary fields for PCP type of Milestones

**so that** I get all needed information about them in the system

### Scenario 1: 

GIVEN Workplan page is open and system Milestones are prepopulated
WHEN I click on the 1-day mandatory PCP Milestone (e.g. Open House or Virtual Information Session) title
THEN I see the Milestone edit Modal with the following fields:

- The 'Milestone Title' as Modal title
- The Type (Dropdown) (disabled)
- The Title (Text field: 150 char max)
- Description (Text field)
- High Priority (Toggle)
- Anticipated Date (Date Picker)
- Actual Date (Date Picker)

- Number of Attendees (text field) (numbers restricted)

- Notes (Rich text editor)

### Scenario 2: 

GIVEN Workplan page is open and system Milestones are prepopulated
WHEN I click on the Multiple-day mandatory PCP Milestone (e.g. Comment period) title
THEN I see the Milestone edit Modal with the following fields:

- The 'Milestone Title' as Modal title
- The Type (Dropdown) (disabled)
- The Title (Text field: 150 char max)
- Description (Text field)
- High Priority (Toggle)
- Anticipated Date (Date Picker)
- Actual Date (Date Picker)

- Number of Days (text field) (numbers restricted)
- End Date (Date Picker) (disabled)
- Number of Responses (text field) (numbers restricted)
- Topic (Text Field: 60 char max)

- Notes (Rich text editor)

### Screenshot
OPEN HOUSE
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHJHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--08ca205c0912e0c296bb5e1efe79a1c58664bcde/image.png)

VIS
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHZHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--839fea0b625613348b90826b337638f1b737ebd5/image.png)

COMMENT PERIOD
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDNHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--006d45ac85510a9fdcb110ec45d1b6dcdbf4188b/image.png)

**Comment by maria-kuzmenko** [comment]
Link to Prototype

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/For-Development?type=design&node-id=3789-77701&mode=design

**Comment by maria-kuzmenko** [comment]
@dinesh-aot 
we should have a 'Number of Attendees' field for Virtual Information Session & Open House

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEl1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5da1e377a8d80c7c2671390563207b48d463da3c/Screen%20Shot%202023-10-12%20at%2010.24.09%20AM.png)

**Comment by Connor1892** [comment]
when I try to save the Comment period Milestone after adding an actual date the save button on the confirmation Modal isn't working. the popup doesn't go away

**Comment by dinesh-aot** [comment]
@Connor1892  Please test it now

**Comment by Connor1892** [comment]
still same behaviour.
