### ISSUE TITLE
Milestone Modals - Locked Milestones

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#980]
**As a** user

**I want** to view locked Milestones

**so that** I can change its description and notes for the team

### Scenario 1: 

GIVEN Workplan page is open and there are locked Milestones 
WHEN I click on the title of the locked Milestone
THEN I see the Milestone Modal with all disabled fields except:

- Description (Text field)
- Notes (Rich text editor)

'Delete' button disappears for Optional locked Milestones

### Screenshot 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWZHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--238358dd533693501648c9f5c8bec917b915664c/image.png)

**Comment by maria-kuzmenko** [comment]
link to the Prototype

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/For-Development?type=design&node-id=3795-78354&mode=design

**Comment by Connor1892** [comment]
Disable the ability to Delete if actual is selected

**Comment by maria-kuzmenko** [comment]
1. Can we change the verbiage on Modals? With the line-height = 1.6rem

**Comment by maria-kuzmenko** [comment]
Locked Milestones in test env don't have a lock symbol and the progress stays 'Not Started'
