### ISSUE TITLE
Milestone Modals - Adding Optional Milestones

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#981]
**As a** user

**I want** to add Optional Milestones in the system

**so that** I can capture additional information on the project

### Scenario 1: 

GIVEN Workplan page is open
WHEN I click on 'Add Milestone' button
THEN the Milestone modal appears

- "Add Milestone" as a Modal title
- Type (Dropdown), mandatory
- Title (Text field: 150 char max), mandatory
- Description (Text field)
- High Priority (Toggle)
- Anticipated Date (Date Picker), mandatory
- Actual Date (Date Picker)
- Notes (Rich text editor)

### Scenario 2: 

GIVEN Add Milestone modal is open
WHEN I select Milestone Type
THEN additional fields appear based on the Milestone Type

- Type (Dropdown) 
- Title (Text field: 150 char max)
- Description (Text field)
- High Priority (Toggle) (Hoverstate)
- Anticipated Date (Date Picker)
- Actual Date (Date Picker)

Optional Fields (White)
- Applicable to selected Milestone Type

Required Field (Grey)
- Notes (Rich text editor)

### Screenshot 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcm5HIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9c5934dba4679c59559438bba7652751b1bc43c9/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnpHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3ba2d2f79e9546ecdaad210dc3084984508cf94e/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjNHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--abcc89cb6494b58c591c51746799bd9ea351b3f3/image.png)

**Comment by maria-kuzmenko** [comment]
Link to Prototype

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/For-Development?type=design&node-id=3795-78863&mode=design

**Comment by Connor1892** [comment]
Disable the ability to Delete if actual is selected

**Comment by Connor1892** [comment]
I'm able to delete even after adding an actual date.
We need the delete button to be gone after actual date is selected.
