### ISSUE TITLE
Milestone Modals - Adding Extenstion

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#982]
**As a** user

**I want** to add an Extension/Suspension to the system

**so that** I can capture additional information on the project

### Scenario 1: 

GIVEN Add Milestone modal is open
WHEN I select Suspension or Extension type of Milestone
THEN I see the following fields pertain to this type of Milestone:

- Hight Priority toggle switched on by default

- Number of Days (text field) (numbers restricted), mandatory
- End Date (Date Picker) (disabled)
- Act Section (Dropdown), mandatory
- Reason (Text Field: 60/60 characters left)

### Screenshot 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzdsIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4c49fc3251a48901202e68a53b4bc9041ee57b3b/Screen%20Shot%202023-09-27%20at%204.09.24%20PM.png)

**Comment by maria-kuzmenko** [comment]
Link to the Prototype

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/For-Development?type=design&node-id=3807-79317&mode=design

**Comment by maria-kuzmenko** [comment]
@dinesh-aot ,

Verbiage change - New Phase End Date instead End Date.
When can we put Acts to properly test it?

**Comment by Connor1892** [comment]
@dinesh-aot I see s.38 Extension of Time Limit in the Milestone list, is that the official name for it if the act selection decides extension or suspension?
@EAO-App-Admin will that be clear to staff?

**Comment by maria-kuzmenko** [comment]
@Connor1892 , Suspension is another card together with Resumption #1075

**Comment by EAO-App-Admin** [comment]
Here is the Act:
![image](https://github.com/bcgov/EPIC.track/assets/22035754/3134f40d-214d-4ad3-a381-ffdb46c12178)

Staff should be aware of this, and if not, this is a great reminder for them...
