### ISSUE TITLE
Proponent Modal - Enhancements

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#990]
**As a** user

**I want** to add and make changes to the Proponent

**so that** I have a database is up to date

### Scenario 1: 

GIVEN 'Proponents' tab within List Management is open 
WHEN I click 'Create Proponent' button
THEN I 'Create Proponent' modal appears with the following information:

- "Create Proponent" Modal Title
- Name (required text field) with the ghost text "Proponent Name"
- Relationship holder (optional dropdown)
- Active toggle (set to 'on' by default)

### Scenario 2:

GIVEN 'Proponents' tab within List Management is open 
WHEN I click on Proponent's Name
THEN I 'Proponent Name' modal appears with the following changes to the fields from Scenario 1:

- 'Proponent name' is the title of the Modal
- Name field is disabled with the lock button

### Screenshot 

Create Proponent
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdURWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eee016235b6903985ced7c830beb34949c838a2b/Screen%20Shot%202023-09-25%20at%205.57.50%20PM.png)

Edit Proponent
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakhWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b410b00325ca62a664b1afcc187f6eae523fc466/image.png)

**Comment by maria-kuzmenko** [comment]
Icons

Lock icon - [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdG5WIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3d5b56e04c4f6ecf9c87db1fff0c68b96f8a1da4/lock-keyhole-bold.svg)

**Comment by maria-kuzmenko** [comment]
link to the prototype

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/Workplan?type=design&node-id=3346-97127&mode=design

**Comment by Connor1892** [comment]
the active toggle is not on by default. When saved, the proponent is active in the grid so this may just be a visual glitch?

**Comment by Connor1892** [comment]
![image](https://github.com/bcgov/EPIC.track/assets/126211473/9fa8dc31-d5f0-4cf1-96a7-5e2e4bbc37ee)

is it okay for the title to be "Update _ProponentName_"? or do you want the "Update" part removed @maria-kuzmenko

**Comment by carlygreenehill** [comment]
GREAT WORK @TomChapmanGov !!!
