### ISSUE TITLE
Project Modal - Enhancements

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#991]
**As a** user
**I want** to add and make changes to Projects
**so that** I have a database that is up to date

### Scenario 1: 

GIVEN Project tab withing the List Management is open
WHEN I click on 'Create Project' button
THEN I 'Create Project' modal appears with the following fields

- Name (Ghost text "Project Name") (required)
- Proponent (dropdown) (required)
- Type (dropdown) (required)
- Subtype (dropdown) (required)

- Project Description (required)
- Location Description (required) (Ghost text "Provide a detailed description of project's location")

- Latitude (Ghost text "e.g. 22.2222") (number restriction)
- Longitude (Ghost text "e.g. 22.2222") (number restriction)
- ENV Region (dropdown) (required)
- NRS Region (dropdown) (required)
- Capital Investment
- Est. FTE Positions Created (number restricted)
- EPIC GUID
- Certificate Number
- Abbreviation (Ghost text 'EDRMS retrieval code')

- Active (toggle) (default active)
- Closed (toggle) (default inactive)

### Scenario 2:
 
GIVEN Project tab within the List Management is open
WHEN I click on any project name
THEN 'Project Title' modal appears with the following changes to the fields from Scenario 1:

- Name (label) (disabled) with the special history lock button
- Proponent (dropdown) (disabled) with the special history lock button

### Scenario 3:

GIVEN Project modal is open
WHEN I put text value for numerical fields (Latitude, Longtitude, Jobs Created)
THEN I see the error message:

'Please provide numerical values'

### Screenshot 

Create Project
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUlnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac84b59f50674b506e28aa3bce8431e14447bdc7/Screen%20Shot%202023-10-10%20at%2010.05.12%20AM.png)

Edit Project
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU1nQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ac34261c0aa11d24552d62f241c01774b05dbc2/Screen%20Shot%202023-10-10%20at%2010.05.27%20AM.png)

Error State
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVlnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--380c09792b3007b1f2ac5d026385df85407380a1/Screen%20Shot%202023-10-10%20at%2010.05.41%20AM.png)

**Comment by maria-kuzmenko** [comment]
Icons

Lock icon - [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEhWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--53b95dc8fad8a21e4138a7d1b6c9bef1c56ca97b/lock-keyhole-bold.svg)

**Comment by maria-kuzmenko** [comment]
link to prototype
https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/Workplan?type=design&node-id=3346-105172&mode=design

**Comment by maria-kuzmenko** [comment]
@TomChapmanGov 

These fields should have numerical values only. Currently, if I put gibberish in there - fields show it there, but the modal can't be saved without giving reasons. 
Since I've saved it with numerical values successfully, fields are restricted, we just need to add error message same as for Latitude

- Capital Investment
- Est. FTE Positions in Construction
- Est. FTE Positions in Operation

**Comment by maria-kuzmenko** [comment]
@TomChapmanGov 

When the modal is being edited, can we leave just the name of the project. 

BEFORE: 'Update Kitimat LNG Terminal' 
AFTER: 'Kitimat LNG Terminal'
