### ISSUE TITLE
Special History - Change history for Project Proponent

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#993]
**As a** user
**I want** change the history of Proponents on the project
**so that** I can track it

### Scenario 1: 

GIVEN Project Tab within List Management is open
WHEN I click on any Project's Name
THEN I see the modal window with the following changes to the fields:
- Name greyed out with the lock symbol to the right
- Proponent dropdown greyed out with the lock symbol to the right

### Screenshot for Scenario 1:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGpWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e75b0f1cd050bba1c08770f01c43bb35b8077969/Screen%20Shot%202023-09-25%20at%204.31.58%20PM.png)

### Scenario 2:
GIVEN Project Edit Modal Window is open
WHEN I click the Lock button next to the Proponent dropdown
THEN lock button changes to unlock button
THEN the Proponent History modal opens with the following information:
- 'Proponent History' title
- Explanation text - 'Update the Proponent of this Project. Click this link for detailed instructions.'
- '+ New Entry' button (primary)
- Table with the fields: Proponent Name (dropdown list), From (date picker), To (date picker OR 'Today' for the last entry) and Actions (edit button by default)
THEN all other fields on the modal window
 are greyed out

### Screenshot for Scenario 2:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1hjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f645e2ba56bf3c5116fa534fae22f1902ba04e2b/Screen%20Shot%202023-09-26%20at%202.27.37%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWJWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--91284d834dd1fc3d198a7c6729ca9a3f4cfd1ebd/Screen%20Shot%202023-09-25%20at%204.53.17%20PM.png)

### Scenario 3: 

GIVEN The Modal window with Proponent History is open
WHEN I click on 'Cancel' button
THEN The modal windown closes as no changes have been made

**Comment by maria-kuzmenko** [comment]
corresponding icons:

lock - locked - [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcC9WIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0875d292d30a58cdeb242eac84a736b86d6c083b/lock-keyhole-bold.svg)
lock - unlocked - [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcURWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--aff70c89cc0c4c1e3a0160a2eff51f6fd22f995f/lock-keyhole-bold-unlock.svg)
edit button - default - [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUhWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--445fa6b4439c00271fa8f19e9203fe1e12b0d06f/edit-regular.svg)
edit button - on hover - [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUxWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--78ca7169f0aedcec2826aa930ba5b330f83a99e2/edit-bold.svg)

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/993?planning-poker) with Zenhub @jadmsaadaot @saravanpa-aot @TomChapmanGov

**Comment by Connor1892** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/993?planning-poker) with Zenhub @dinesh-aot

**Comment by jadmnsaad** [comment]
I think this has been done by @salabh-aot here https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/1359
