### ISSUE TITLE
Special History - Add a new entry for Project Proponent

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#994]
**As a** user
**I want** to be able to add a new Proponent and corresponding dates when this Proponent was on a Project
**so that** I can have legally relevant information

### Scenario 1: 

GIVEN Proponent History on Project Modal is unlocked
WHEN I click on a '+ New Entry' button
THEN new fields appear on top of the table with the following information:
- Editable **Proponent Name** with Select Proponent ghost text
- Editable **From** filed with MM-XX-YYYY 
- Non-editable **To** field with text field 'Today'
- **Actions** with green confirm and red cancel icon buttons 

THEN 'To' field for the previous entry would be populated with the date that will be 'today's' date
THEN 'Save' button on the Modal is disabled

### Screenshot Scenario 1: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1BWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f12644a021eb5bce06e3d9d4bc38d5cce7f34c13/Screen%20Shot%202023-09-25%20at%205.14.33%20PM.png)

### Scenario 2:
GIVEN fields for Proponent Name and From fields are filled in
WHEN I click confirm icon button
THEN Proponent's name on the Modal is updated with the latest changes
THEN Edit icon button will be displayed in the Actions column
THEN 'To' date for the previous entry becomes the same as the date from 'From' field for the new entry 
THEN 'Save' Modal button is active

### Screenshot Scenario 2: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1RWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2d57fa1ca35288b2129cf4ed7da864f1f8eb1ca4/Screen%20Shot%202023-09-25%20at%205.15.42%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2JWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c4f3b4f37e85190639db268c0596f68524616692/Screen%20Shot%202023-09-25%20at%205.15.53%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcy9WIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7b57d1b8eed288ef6046339acb33c3cb306db9df/Screen%20Shot%202023-09-25%20at%205.27.41%20PM.png)

### Scenario 3:
GIVEN fields for Proponent Name and From fields are filled in
WHEN I click on cancel icon button
THEN I see empty states of both fields

### Scenario 4:
GIVEN fields for Proponent Name and From fields are filled in
WHEN I click on unlock icon button
THEN I see the error message 'Please, save or discard your changes first'

### Screenshot Scenario 4
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTdjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--36b99e363434d2b136796263583ea7e6657e4fa2/Screen%20Shot%202023-09-26%20at%202.19.59%20PM.png)

### Scenario 5: 

GIVEN  fields for Proponent Name and From fields are filled in
WHEN I click on 'Cancel' button
THEN I see the Modal window 'Are you sure?' with Cancel confirmation 

### Scenario 6:
GIVEN fields for Proponent Name and/or From fields are not filled in 
WHEN I click on unlock icon button
THEN Empty fields turn red
THEN I see the error message with an exclamation icon and the text 'Please fill in the required fields'

### Screenshot Scenario 6: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2pWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--30b696b8501c6a2b2009500f1698d7df500726ce/Screen%20Shot%202023-09-25%20at%205.18.17%20PM.png)

### Scenario 7:
GIVEN fields for Proponent Name and/or From fields are not filled in 
WHEN I click on cancel icon button
THEN new entry fields are deleted

### Scenario 8:
GIVEN 'From' field is filled in with wrong data format   
WHEN I click on save icon button
THEN I see the error message with an exclamation icon and the text 'Please put an accurate date'

### Screenshot Scenario 8
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczdWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a98476374fd53e50a842a0f0ade3157259c6abf6/Screen%20Shot%202023-09-25%20at%205.25.39%20PM.png)

**Comment by maria-kuzmenko** [comment]
Corresponding icons

Save icon for icon button - [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3ZWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a5a959dc297c56f8bde2519274a861ede761aefb/save.svg)
Cancel icon for icon button - [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3pWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bf18c1ca2938ee8de43dd73ab2c7c18e562ff438/cancel.svg)
exclamation icon for error message - [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczNWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb8e15868ec8ad9822fee9131283219f143932bc/circle-exclamation.svg)

**Comment by maria-kuzmenko** [comment]
For **Icon Button behaviour** refer to the Design System

https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=500-9476&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/994?planning-poker) with Zenhub @jadmsaadaot @saravanpa-aot @TomChapmanGov

**Comment by Connor1892** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/994?planning-poker) with Zenhub @dinesh-aot

**Comment by jadmnsaad** [comment]
This has been done by @salabh-aot here https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/1359
