### ISSUE TITLE
Special History - Edit entries for Project Proponent 

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#995]
---

**As a** Superuser

**I want** to be able to update history of Proponents on a Project

**so that** I can have legally relevant information

### Scenario 1: 

GIVEN Proponent History on Project Modal is unlocked
WHEN I click on the Edit icon button
THEN Proponent Name has a dropdown and Primary/Accent/Light (#0070E0) outline 
THEN From field has a calendar picker and Primary/Accent/Light (#0070E0) outline
THEN Action field has two icon buttons: confirm and cancel

THEN 'Save' button on the Modal is disabled

### Screenshot Scenario 1
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUhjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0ed21e9c0547fb045472cec7fff2d2d0d183d07f/Screen%20Shot%202023-09-26%20at%202.15.41%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUxjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7d8597b56a81df79fb54412856713c1157ab2877/Screen%20Shot%202023-09-26%20at%202.15.53%20PM.png)

**Comment by maria-kuzmenko** [comment]
link to prototype
https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/Workplan?type=design&node-id=3550-128539&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/995?planning-poker) with Zenhub @jadmsaadaot @saravanpa-aot @TomChapmanGov

**Comment by Connor1892** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/995?planning-poker) with Zenhub @dinesh-aot
