### ISSUE TITLE
Special History - Change history for Project Name

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#996]
**As a** Superuser

**I want** change the history of the Project’s name

**so that** I can track it

### Scenario 1:
GIVEN Project Edit Modal Window is open
WHEN I click the Lock button next to the Name field
THEN lock button changes to unlock button
THEN the Project Name History modal opens with the following information:
- 'Project Name' title
- Explanation text - 'Update the legal name of the Project and the dates each name was in legal use. Click this link for detailed instructions'
- '+ New Entry' button (primary)
- Table with the fields: Project Name (dropdown list), From (date picker), To (date picker OR 'Today' for the last entry) and Actions (edit button by default)
THEN all other fields on the modal window are greyed out

### Screenshot Scenario 1
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFBjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cf1febced8c369eb424d4b551e102579e02d1b0a/Screen%20Shot%202023-09-26%20at%202.34.44%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFhjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--caee84451aa8304d766259163bbbe4d12012b4e9/Screen%20Shot%202023-09-26%20at%202.34.55%20PM.png)

**Comment by maria-kuzmenko** [comment]
link to prototype

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/Workplan?type=design&node-id=3550-130691&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/996?planning-poker) with Zenhub @jadmsaadaot @saravanpa-aot @TomChapmanGov

**Comment by Connor1892** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/996?planning-poker) with Zenhub @dinesh-aot
