### ISSUE TITLE
Special History - Add a new entry for Project Name

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#997]
**As a** user
**I want** to be able to add a new Project name and corresponding dates when this Project's name existed
**so that** I can have legally relevant information

### Scenario 1: 

GIVEN Project Name History on Project Modal is unlocked
WHEN I click on a '+ New Entry' button
THEN new fields appear on top of the table with the following information:
- Editable **Project Name** text field
- Editable **From** filed with MM-XX-YYYY
- Non-editable **To** field with text field 'Today'
- **Actions** with green confirm and red cancel icon buttons 

THEN 'To' field for the previous entry would be populated with the date that will be 'today's' date
THEN 'Save' button on the Modal is disabled

### Screenshot Scenario 1: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHpkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--01e3565f634813808a7309b715e70247098629b0/Screen%20Shot%202023-09-26%20at%203.32.30%20PM.png)

### Scenario 2:
GIVEN fields for Project Name and From fields are filled in
WHEN I click save icon button
THEN Proponent's name on the Modal is updated with the latest changes
THEN Edit icon button will be displayed in the Actions column
THEN 'To' date for the previous entry becomes the same as the date from 'From' field for the new entry 

### Screenshot Scenario 2: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDNkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--acf939c0e1325f3d5d63fc10a7c4319a0adf62cb/Screen%20Shot%202023-09-26%20at%203.33.27%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDdkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a7aca3fc62a37cfcf9127374ff388f43b18f76e8/Screen%20Shot%202023-09-26%20at%203.33.37%20PM.png)

### Scenario 3:
GIVEN fields for Project Name and From fields are filled in
WHEN I click on cancel icon button
THEN I see empty states of both fields

### Scenario 4:
GIVEN fields for Project Name and From fields are filled in
WHEN I click on unlock icon button
THEN I see the error message 'Please, save or discard your changes first'

### Scenario 5: 
GIVEN  fields for Project Name and From fields are filled in
WHEN I click on 'Cancel' button
THEN I see the Modal window 'Are you sure?' with Cancel confirmation 

### Scenario 6:
GIVEN fields for Project Name and/or From fields are not filled in 
WHEN I click on unlock icon button
THEN Empty fields turn red
THEN I see the error message with an exclamation icon and the text 'Please fill in the required fields'

### Scenario 7:
GIVEN fields for Proponent Name and/or From fields are not filled in 
WHEN I click on cancel icon button
THEN new entry fields are deleted

### Scenario 8:
GIVEN 'From' field is filled in with wrong data format   
WHEN I click on save icon button
THEN I see the error message with an exclamation icon and the text 'Please put an accurate date'

**Comment by maria-kuzmenko** [comment]
link to prototype

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/Workplan?type=design&node-id=3584-131713&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/997?planning-poker) with Zenhub @jadmsaadaot @saravanpa-aot @TomChapmanGov

**Comment by Connor1892** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/997?planning-poker) with Zenhub @dinesh-aot
