### ISSUE TITLE
Special History - Edit entries for Project Name

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#998]
---

**As a** Superuser

**I want** to be able to update Project’s Name

**so that** I can have legally relevant information

### Scenario 1: 

GIVEN Project Name History on Project Modal is unlocked
WHEN I click on the Edit icon button
THEN Project Name text field has Primary/Accent/Light (#0070E0) outline 
THEN From field has a calendar picker and Primary/Accent/Light (#0070E0) outline
THEN Action field has two icon buttons: confirm and cancel

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWpkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c29dec7d3fd61b293fa2b5e5d5c99e0f14ce8955/Screen%20Shot%202023-09-26%20at%203.43.11%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXJkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--51d245ea71b9faa01f78c8b50acfcc433230e284/Screen%20Shot%202023-09-26%20at%203.43.25%20PM.png)

**Comment by maria-kuzmenko** [comment]
link to prototype 

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/Workplan?type=design&node-id=3607-133884&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/998?planning-poker) with Zenhub @jadmsaadaot @saravanpa-aot @TomChapmanGov

**Comment by Connor1892** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/998?planning-poker) with Zenhub @dinesh-aot

**Comment by maria-kuzmenko** [comment]
@salabh-aot , @dinesh-aot 

Proponent should not jump on the another line

now:
<img width="810" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEtUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--726f33654c3cce9e944b8b3dcfb0bbbf949746f2/Screen%20Shot%202024-01-02%20at%202.15.49%20PM.png" alt="Screen Shot 2024-01-02 at 2.15.49 PM.png" />

should be:
<img width="1094" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFNUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--98440b760d75b77d10e46191db0fb539873af499/Screen%20Shot%202024-01-02%20at%202.16.30%20PM.png" alt="Screen Shot 2024-01-02 at 2.16.30 PM.png" />

**Comment by jadmnsaad** [comment]
@Connor1892 @maria-kuzmenko. Maria and I discussed the above comments, we concluded that we could accept those UI sacrifices for the reusability and maintainability in the code

**Comment by jadmnsaad** [comment]
@Connor1892 @maria-kuzmenko. Maria and I discussed the above comments, we concluded that we could accept those UI sacrifices for the reusability and maintainability in the code
