### ISSUE TITLE
Special History - Proponent name

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#999]
**As a** user
**I want** change the history of Proponent's name
**so that** I can track it

### Scenario 1: 

GIVEN Proponent Tab within List Management is open
WHEN I click on any Proponent's Name
THEN I see the modal window with the following changes to the fields:
- Name greyed out with the lock symbol to the right

### Screenshot for Scenario 1:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1RkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--336525e5127dac43603b78294c53409293ed5be2/Screen%20Shot%202023-09-26%20at%204.01.03%20PM.png)

### Scenario 2:
GIVEN Proponent Edit Modal Window is open
WHEN I click the Lock button next to the Name field
THEN lock button changes to unlock button
THEN the Proponent Name History modal opens with the following information:
- 'Proponent Name' title
- Explanation text - 'Update the legal name of the Proponent and the dates each name was in legal use. Click this link for detailed instructions'
- '+ New Entry' button (primary)
- Table with the fields: Proponent Name (text field), From (MM-DD-YYYY ghost text), To ('Today' for the last entry) and Actions (edit button by default)
THEN all other fields on the modal window are greyed out

### Screenshot for Scenario 2:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1hkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--760833c91094fdfcef2ddd868dfdf23a3303f340/Screen%20Shot%202023-09-26%20at%204.01.20%20PM.png)

### Scenario 3: 

GIVEN The Modal window with Proponent History is open
WHEN I click on 'Cancel' button
THEN The modal windown closes as no changes have been made

**Comment by maria-kuzmenko** [comment]
For new entries or editing entries - same logic as for #997 and #998

**Comment by maria-kuzmenko** [comment]
prototype

https://www.figma.com/file/j5onJ5RZGAxahxhYp68N8m/Workplan?type=design&node-id=3614-135069&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/999?planning-poker) with Zenhub @jadmsaadaot @saravanpa-aot @TomChapmanGov

**Comment by Connor1892** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/999?planning-poker) with Zenhub @dinesh-aot

**Comment by maria-kuzmenko** [comment]
@dinesh-aot , @salabh-aot 

Regardless of the changes that should be apply to common components (all in a separate #1515 card), this is just text changes 

1. Proponent spelled wrong - 'Proponet' now should be 'Proponent'
2. The description should have not 'the Project' but 'the Proponent' as we are changing the information about the Proponent here. 

<img width="773" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeldUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aebbd9bfe52a63352e5b23f79b5e31fa1c1a943d/Screen%20Shot%202024-01-02%20at%2012.12.23%20PM.png" alt="Screen Shot 2024-01-02 at 12.12.23 PM.png" />

**Comment by Connor1892** [comment]
Relationship holder is not locked when working on special history for name

**Comment by Connor1892** [comment]
@dinesh-aot 
The name is still not disabled for me.
![image](https://github.com/bcgov/EPIC.track/assets/126211473/c866b129-eb5f-4eeb-b169-55c0d4f0cfd1)

**Comment by Connor1892** [comment]
@dinesh-aot the Proponent name is still not disabled in TEST or DEV
